### ISSUE TITLE
Στοιχεία εταίρων μετόχων

### ISSUE THREAD

**Issue by apanagio** [mou-gr/regions#10]
Στα στοιχεία των εταίρων/ μετόχων τα πεδία ΑΦΜ, ΑΔΤ, έτος ίδρυσης (περίπτωση μετόχου νομικό πρόσωπο), θέση εταιρου/μετόχου, είδος επαγγελματικής εμπειρίας και έτη επαγγελματικής εμπειρίας

**Comment by apanagio** [comment]
Δεν είναι ξεκάθαρο το αίτημα

**Comment by mariaelanet** [comment]
Στα στοιχεία των εταίρων/ μετόχων τα πεδία ΑΦΜ, ΑΔΤ, έτος ίδρυσης (περίπτωση μετόχου νομικό πρόσωπο), θέση εταιρου/μετόχου, είδος επαγγελματικής εμπειρίας και έτη επαγγελματικής εμπειρίας να είναι υποχρεωτική η συμπλήρωση

**Comment by galanosel** [comment]
Έχει υλοποιηθεί και θα ανέβει staging
