### ISSUE TITLE
5.2 Δαπάνες -Πεδία πίνακα

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#100]
το "Κατηγορία Δαπάνης" καθώς και το "Μονάδα Μέτρησης", να είναι κενά προς συμπλήρωση (και όχι με τιμές που φαίνεται να έχουν κατά το άνοιγμα του πίνακα).

Να είναι required.

**Comment by Aris-93** [comment]
Επιλύθηκε

**Comment by sadamaki** [comment]
οκ

**Comment by sadamaki** [comment]
οκ
