### ISSUE TITLE
5.2 Δαπάνες-

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#101]
Ποια από τα παρακάτω πεδία συμφωνείτε να είναι required :

Ποσότητα = required
Περιγραφή= required
Τιμή Μονάδας= required
Προμηθευτής = required, εφόσον το αφήσουμε να υπάρχει σαν πεδίο στο 5.2
ΑΦΜ Προμηθευτή= required, εφόσον το αφήσουμε να υπάρχει σαν πεδίο στο 5.2
Σειριακός Αριθμός= required, εφόσον το αφήσουμε να υπάρχει σαν πεδίο στο 5.2
Τεχνικά Χαρακτηριστικά=required
Τεκμηρίωση Συμβατότητας με την Επένδυση και Επιβεβαίωση του Εύλογου του Κόστους= required

**Comment by galanosel** [comment]
Υλοποιήθηκε παρακαλώ ελέγξετε staging

**Comment by sadamaki** [comment]
Έχει υλοποιηθεί ως εξής : 
Ποσότητα = required
Περιγραφή= required
Τιμή Μονάδας= required
Σειριακός Αριθμός= προαιρετικό πεδίο
Τεχνικά Χαρακτηριστικά=required
Τεκμηρίωση Συμβατότητας με την Επένδυση και Επιβεβαίωση του Εύλογου του Κόστους= required
