### ISSUE TITLE
Επιλέξιμοι ΚΑΔ

### ISSUE THREAD

**Issue by apanagio** [mou-gr/regions#11]
Ως ΚΑΔ επένδυσης θα πρέπει να υπάρχουν στη λίστα μόνο οι επιλέξιμοι σύμφωνα με τον οδηγό. Ειδικά οι επιχειρήσεις της κατηγορίας Β θα πρέπει να έχουν ως επιλογή τους α) 41.20.20.01 και 41.20.20.02 β) τους επιλέξιμους ΚΑΔ που ξεκινούν από 55

**Comment by apanagio** [comment]
Ο έλεγχος των ΚΑΔ διενεργείται προς το παρόν στον έλεγχο ορθότητας.
Μπορεί να μπει bannerάκι κατά την υποβολή που θα ενημερώνει τους επενδυτές.
Επίσης δεν γίνεται να ελέγχονται διαφορετικοί ΚΑΔ ανάλογα με τον τύπο της επιχείρησης. Αν κάτι τέτοιο απαιτείται από την πρόσκληση τότε θα πρέπει να ελέγχεται κατά την αξιολόγηση.

**Comment by mariaelanet** [comment]
Θα μπορούν να γίνονται έλεγχοι από το ΣΕΠ?

**Comment by mariaelanet** [comment]
Στην επιλογή ΚΑΔ μπορούν να μπουν μόνο οι επιλέξιμοι σύμφωνα με τον οδηγό του προγράμματος ανεξάρτητα από την κατηγορία?

**Comment by apanagio** [comment]
Από το ΣΕΠ έλεγχοι μπορούν να γίνονται κανονικά, αλλά αφού μπορούν να γίνονται κατά την οριστικοποίηση της υποβολής δεν ξέρω τι παραπάνω μας δίνει.
Για τον έλεγχο στο user interface, είναι κάτι που το κοιτάμε, αλλά ίσως δεν υπάρχει ο χρόνος για να το υλοποιήσουμε για αυτή τη δράση
