### ISSUE TITLE
6. Ποσό δόσης - Υλοποιηθήσες Επιχορηγούμενες Δαπάνες

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#119]
Ν7ΕΕ-0000884-
Στο πεδίο "Υλοποιηθήσες Επιχορηγούμενες Δαπάνες" γιατί φέρνει τιμή 0,00??

Ας το δει και ο ΕΦΕΠΑΕ και ας μας επιβεβαιώσει το αν θα έπρεπε να φέρνει το ποσό 50.990

**Comment by galanosel** [comment]
Το πεδίο μετονομάστηκε σε "Πιστοποιημένος Π/Υ (Σύνολο)".
Το πεδίο αυτό δείχνει το ποσό των πιστοποιημένων επιχορηγούμενων δαπανών, γι' αυτό στο πρώτο αίτημα ελέγχου έχει τιμή 0.
