### ISSUE TITLE
6. Ποσό δόσης -  Ποσοστά Υλοποίησης

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#120]
Ν7ΕΕ-0000884- 
Γιατι φέρνει τιμή 0,00 στα παρακάτω πεδία?

-Ποσοστό Υλοποίησης Οικονομικού Αντικειμένου =( Επιχορηγούμενος Προϋπολογισμός βάσει παραστατικών/  Επιχορηγούμενος Προϋπολογισμός βάσει ένταξης ή τυχόν τροποποίησης)

-Ποσοστό υλοποίησης ως προς το συνολικά εγκεκριμένο προϋπολογισμό= (Αιτούμενος Προϋπολογισμός βάσει παραστατικών/  Αιτούμενο Προϋπολογισμός βάσει ένταξης ή τυχόν τροποποίησης)

**Comment by galanosel** [comment]
Υλοποίηθηκε παρακαλώ ελέγξετε staging

**Comment by galanosel** [comment]
Φτιάχτηκε θα φανεί με την επόμενη αναβάθμιση
