### ISSUE TITLE
6. Ποσό δόσης - Πληρωτέα Ποσά

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#122]
Ν7ΕΕ-0000884
Πρέπει να φέρνουν τιμές τα παρακάτω πεδία (και όχι 0,00 που είναι τώρα, αν δεν έχει τιμολόγιο escrow καλά κάνει και είναι 0,00 το "Πληρωτέο ποσό Αιτήματος (Escrow)")

-Πληρωτέο ποσό Αιτήματος (ΕΦΔ) 
-Πληρωτέο ποσό Αιτήματος (Escrow)

**Comment by galanosel** [comment]
Επιλύθηκε
Θα φανεί στην επόμενη αναβάθμιση της staging

**Comment by sadamaki** [comment]
Φάνηκε
