### ISSUE TITLE
6. Ποσό δόσης  ( bug)

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#123]
Ν7ΕΕ-0000884

Μετά την καταχώρηση εγγραφών στον πίνακα "Απομειώσεις" σκάει στο tab 6, το εξής μήνυμα 

Specified cast is not valid.

**Comment by apanagio** [comment]
Διορθώθηκε θα ανέβει staging στην επόμενη αναβάθμιση

**Comment by sadamaki** [comment]
ok
