### ISSUE TITLE
Kαρτέλα 6 ΑΙΤΗΜΑ ΕΝΔΙΑΜΕΣΗΣ ΕΠΑΛΗΘΕΥΣΗΣ ΕΠΙΧΕΙΡΟΥΜΕ ΕΞΩ

### ISSUE THREAD

**Issue by tsitsopoulosexo** [mou-gr/regions#129]
ΚΑΡΤΕΛΑ 6

1) Ο τίτλος να γίνει "ΟΙΚΟΝΟΜΙΚΑ ΣΤΟΙΧΕΙΑ ΕΡΓΟΥ- ΥΠΟΛΟΓΙΣΜΟΣ ΔΟΣΗΣ" αντί "ΠΡΟΟΔΟΣ ΥΛΟΠΟΙΗΣΗΣ ΦΥΣΙΚΟΥ ΟΙΚΟΝΟΜΙΚΟΥ ΑΝΤΙΚΕΙΜΕΝΟΥ

2) Στα ποσοστά Υλοποίησης ένα εκ των δύο θα πρέπει να φύγει. Να κρατηθεί το εξής :   
Ποσοστό υλοποίησης οικονομικού αντικειμένου σε σχέση με εγκεκριμένο επιχορηγούμενο προϋπολογισμό.  
Το εν λόγω ποσοστό μπορεί να παράγεται αυτόματα.

3) Παρατηρήση : Θα πρέπει να διευκρινίσετε στην έννοια ΠΙΣΤΟΠΟΙΗΜΕΝΟ Π/Υ αν αναφέρεστε στον ΣΥΝΟΛΙΚΟ ΠΙΣΤΟΠΟΙΗΜΕΝΟ ή στον ΣΥΝΟΛΙΚΟ ΠΙΣΤΟΠΟΙΗΜΕΝΟ ΕΠΙΧΟΡΗΓΟΥΜΕ Π/Υ. 
Το ίδιο όταν αναγράφετε την ΕΝΝΟΙΑ : ΣΥΝΟΛΙΚΟΣ Π/Υ. 
Εχει σημασία. Σε κάθε περίπτωση να υπάρχει το κατάλληλο διευκρινιστικό λεκτικό.

**Comment by apanagio** [comment]
υλοποιήθηκε
