### ISSUE TITLE
Ενημέρωση πεδίων τίτλων πράξης

### ISSUE THREAD

**Issue by apanagio** [mou-gr/regions#13]
Στον πίνακα  τα πεδία  Τίτλος Πράξης και Τίτλος Πράξης (Αγγλικά να αντλούνται  αυτόματα από τα πεδία  Επωνυμία Δικαιούχου και Επωνυμία Δικαιούχου (Αγγλικά) της καρτέλας ΓΕΝΙΚΑ ΣΤΟΙΧΕΙΑ ΔΙΚΑΙΟΥΧΟΥ

**Comment by apanagio** [comment]
Είναι δύσκολο να γίνει. 
Τι πειράζει να μπορεί ο επενδυτής να δώσει τίτλο στην επένδυσή του;

**Comment by cbouras** [comment]
Το λογικό είναι να συμπληρώνει Τίτλο Πράξης ο Δικαιούχος. Η λογική του να αντιγράφεται απλά η επωνυμία ΔΕΝ ΑΠΟΤΕΛΕΙ ΤΙΤΛΟ ΠΡΑΞΗΣ ΓΙΑ ΤΑ ΣΥΓΧΡΗΜΑΤΟΔΟΤΟΥΜΕΝΑ μετά από αναφορά της ΕΥΣΣΑ. Στις προηγούμενες δράσεις του ΕΠΑΝΕΚ κάναμε ένα συνδυασμό ΔΡΑΣΗ + ΕΠΩΝΥΜΙΑ χωρίς να είναι το καλύτερο δυνατό.

**Comment by cbouras** [comment]
Το πεδίο Είδος Επένδυση δεν πρέπει να εξαφανιστεί.  Αν επιτρέπεται Νέα Κατασκευή, Επέκταση, ή Μετροπή / Εκσυγχρονισμός τουριστικής Μονάδας τότε αυτό θα πρέπει να δηλωθεί στο ΟΠΣ ΕΣΠΑ.
Προτείνω να μπουν τα πεδία και επιλέξει τις τιμές ο δικαιούχος.

<xsd:enumeration value="5221"/>
<xsd:enumeration value="5222"/>
<xsd:enumeration value="5223"/>
<xsd:enumeration value="5224"/>
<xsd:enumeration value="5225"/>
<xsd:enumeration value="5226"/>
<-- Νέα Κατασκευή -->
<-- Επέκταση -->
<-- Μετατρ./εκσυγχρ. -->
<-- Αλλαγή τόπου -->
<-- Δημ. με εξαγορά -->
<-- Αλλο -->
