### ISSUE TITLE
ΚΑΡΤΕΛΑ 2 ΑΙΤΗΜΑ ΕΝΔΙΑΜΕΣΗΣ ΕΠΑΛΗΘΕΥΣΗΣ ΕΠΙΧΕΙΡΟΥΜΕ ΕΞΩ 

### ISSUE THREAD

**Issue by tsitsopoulosexo** [mou-gr/regions#130]
Παρατηρήσεις  προς διευκρίνιση/διευθέτηση 
2.1 Καρτέλα 2.1 Στοιχεία Εκχώρησης
Στο πεδίο «Διάρκεια σε μήνες» όταν δεν υπάρχει (συμβαίνει) πολλές φορές διάρκεια στη σύμβαση τι θα συμπληρώνει ο επενδυτής;

2.2. Καρτέλα 2.2 Στοιχεία Δανείου

1) Όπως και στην καρτέλα 2.1. στο πεδίο «Διάρκεια σε μήνες» όταν δεν υπάρχει (συμβαίνει) πολλές φορές διάρκεια στη σύμβαση τι θα συμπληρώνει ο επενδυτής;

**Comment by galanosel** [comment]
2.1 Το πεδίο «Διάρκεια σε μήνες» έγινε μη υποχρεωτικό προς συμπλήρωση επομένως δεν είναι αναγκασμένος ο χρήστης να βάλει τιμή
2.2 Το πεδίο «Διάρκεια σε μήνες» έγινε μη υποχρεωτικό προς συμπλήρωση επομένως δεν είναι αναγκασμένος ο χρήστης να βάλει τιμή
