### ISSUE TITLE
ΚΑΡΤΕΛΑ 3 ΑΙΤΗΜΑ ΕΝΔΙΑΜΕΣΗΣ ΕΠΑΛΗΘΕΥΣΗΣ ΕΠΙΧΕΙΡΟΥΜΕ ΕΞΩ

### ISSUE THREAD

**Issue by tsitsopoulosexo** [mou-gr/regions#131]
ΚΑΡΤΕΛΑ 3/ Kαρτέλα 3.2  
Υλοποίηση Επένδυσης (2)
Δεδομένου ότι προστέθηκε εκ των υστέρων για άλλη Δράση επιπλέον ερώτηση για τον Escrow Account παρακαλώ όπως η φράση :

«Στις ερωτήσεις όπου ο Δικαιούχος έχει επιλέξει ΟΧΙ, υποχρεούται να αναγράψει σχετική τεκμηρίωση. Για τη Δράση ΕΠΙΧΕΙΡΟΥΜΕ ΕΞΩ, ο ΔΙΚΑΙΟΥΧΟΣ συμπληρώνει ΔΕΝ ΑΠΑΙΤΕΙΤΑΙ στις ερωτήσεις 1.4 και 1.5.»

να αντικατασταθεί με τη φράση :
 
«Στις ερωτήσεις όπου ο Δικαιούχος έχει επιλέξει ΟΧΙ, υποχρεούται να αναγράψει σχετική τεκμηρίωση. Για τη Δράση ΕΠΙΧΕΙΡΟΥΜΕ ΕΞΩ, ο ΔΙΚΑΙΟΥΧΟΣ συμπληρώνει ΔΕΝ ΑΠΑΙΤΕΙΤΑΙ στις ερωτήσεις 1.5 1,6 στο Φυσικό Αντικείμενο και 2.7. στο Οικονομικό Αντικείμενο»

**Comment by galanosel** [comment]
DONE
