### ISSUE TITLE
Καρτέλα 6 ΕΠΙΧΕΙΡΟΥΜΕ ΕΞΩ- ΑΙΤΗΜΑ ΕΝΔΙΑΜΕΣΗΣ ΕΠΑΛΗΘΕΥΣΗΣ

### ISSUE THREAD

**Issue by tsitsopoulosexo** [mou-gr/regions#133]
Καρτέλα 6   Επισημάνσεις/Διευκρινίσεις προς απάντηση :

•Τα ποσά θα έρχονται αυτόματα η θα τα συμπληρώνει ο Δικαιούχος;

•Στον Πίνακα «Τυχόν Προηγούμενες Πιστοποιήσεις» (όπως προτάθηκε ΙΣΧΥΕΙ ΟΤΙ :
Πιστοποιημένος Π/Υ (ΕΦΔ) + Πιστοποιημένος Π/Υ (Escrow)=Πιστοποιημένος Π/Υ (Σύνολο)
Σωστά;
Στο Επιχειρούμε Έξω είναι εύκολο καθώς δεν έχουμε ΕSCROW ACCOUNT. Για τις άλλες δράσεις;
Οι Δικαιούχοι πρέπει να γνωρίζουν προκειμένου να συμπληρώνουν σωστά τα πεδία.

•Επίσης όταν αναφέρεται Πιστοποιημένος Π/Υ εννοούμε τον Πιστοποιημένο Επιχορηγούμενο; Διότι άλλο είναι η έννοια «Πιστοποιημένος Π/Υ» και άλλο «Πιστοποιημένος Επιχορηγούμενος Π/Υ». 
Θέλει Οπωσδήποτε διευκρίνιση ποια τιμή βάζουμε.

•Στον Πίνακα Τρέχον Αίτημα :
α) η φράση να γίνει : Τρέχον Αίτημα Επαλήθευσης
β) να υπάρξει γραμμή κάτω από τον Αιτούμενο Προϋπολογισμό και ο Αιτούμενος Χρηματοδοτούμενος-Ενισχυόμενος Προϋπολογισμός διότι υπάρχουν έργα που έχουν υποβάλλει και μη ενισχυόμενο π/υ και πρέπει να το ξεχωρίζουμε στις δαπάνες. 

Στον πίνακα με τα ποσοστά υλοποίησης, όπως αναγράφεται να μας δοθούν διευκρινίσεις :
Α) Ποσοστό Υλοποίησης Οικονομικού Αντικειμένου. Σε τι αναφέρεται; Στο αίτημα μόνο ;  Είναι περιττό εφόσον υπάρχει η άλλη ερώτηση.

Υπενθυμίζω ότι είναι άλλο η έννοια του Συνολικού Προϋπολογισμού και άλλο η έννοια του Επιχορηγούμενου Προϋπολογισμού. Ποια εννοείται εσείς; Θα γίνει μεγάλο μπέρδεμα με τα ποσά και ποσοστά που θα αναγράφονται αν δεν το ξεκαθαρίσουμε για να δοθούν σαφείς οδηγίες συμπλήρωσης στους Δικαιούχους.

Επισημαίνω ότι :
Συνολικά εγκεκριμένος= Επιχορηγούμενος +Μη ενισχυόμενος-επιχορηγούμενος π/υ. Δύναται να ταυτίζονται όταν ο μη ενισχυόμενος-επιχορηγούμενος είναι 0.

Τα ανωτέρω είχαν ζητηθεί να διευκρινιστούν και σε προηγούμενες αποστολές παρατηρήσεων.

**Comment by apanagio** [comment]
υλοποιήθηκαν
