### ISSUE TITLE
ΕΠΙΧΕΙΡΟΥΜΕ ΕΞΩ- ΕΛΕΓΧΟΣ ΑΙΤΗΜΑΤΟΣ ΕΠΑΛΗΘΕΥΣΗΣ ΔΙΚΑΙΟΥΧΟΥ ΑΠΟ ΕΦΕΠΑΕ

### ISSUE THREAD

**Issue by tsitsopoulosexo** [mou-gr/regions#139]
Σε συνέχεια της συνάντησής μας σας αποστέλλω με οριζόντια λογική των δράσεων τις παρατηρήσεις για τον έλεγχο του αιτήματος επαλήθευσης του Δικαιούχου απο τον ΕΦΕΠΑΕ (έκθεση επαλήθευσης)

**ΕΛΕΓΧΟΣ ΑΙΤΗΜΑΤΟΣ ΕΝΔΙΑΜΕΣΗΣ ΕΠΑΛΗΘΕΥΣΗΣ ΔΙΚΑΙΟΥΧΟΥ ΑΠΟ ΕΦΕΠΑΕ.**
To αίτημα θα αποτελείται από τις καρτέλες του αιτήματος του Δικαιούχου με επιπρόσθετη καρτέλα για θέματα που αφορούν την επαλήθευση (διοικητική/επιτόπια).

**Α. ΠΡΟΔΙΑΓΡΑΦΕΣ**
-Ολες οι καρτέλες που θα έρχονται προσυμπληρωμένες από το αίτημα του Δικαιούχου θα είναι ΑΝΟΙΚΤΕΣ.
-Θα πρέπει να υπάρχει μία καρτέλα με στοιχεία ελέγχου. 
- Οι καρτέλες να έρχονται προσυμπληρωμένες από αίτημα δικαιούχου και ανοικτές για επεξεργασία. --Να αναγράφονται τα επικαιροποιημένα στοιχεία. 
- Πρέπει κάπου να υπάρχει η έγκριση/απόρριψη αιτημάτων αλλαγών που διαπιστώθηκαν , ειδικά εάν δεν υπάρχει χωριστό αίτημα.
-ΠΟΛΥ ΣΗΜΑΝΤΙΚΟ : ΛΕΙΤΟΥΡΓΙΚΟΤΗΤΑ ΔΙΑΣΥΝΔΕΣΗΣ ΤΡΟΠΟΠΟΙΗΣΕΩΝ ΦΟΑ, κ.λπ. ΣΤΟΙΧΕΙΩΝ ΜΕ ΑΙΤΗΜΑΤΑ ΕΠΑΛΗΘΕΥΣΗΣ ΣΤΙΣ ΚΑΡΤΈΛΕΣ 1 ΚΑΙ 5.
-Ορθός υπολογισμός δόσης
-Ονοματεπώνυμα ελεγκτών

**Β.Επιχειρησιακές Παρατηρήσεις ΠΣΚΕ**

**1.Υποκαρτέλα Καρτέλα 1.1.**

Η καρτέλα 1.1. έρχεται κλειδωμένη από το αίτημα του Δικαιούχου. Είναι η καρτέλα 6 του αιτήματος του Δικαιούχου. Ισχύουν οι παρατηρήσεις που έχουμε αναγράψει ανωτέρω για την καρτέλα 6 προκειμένου αφού υλοποιηθούν να έρχονται ορθά στην 1.1.

**2.Υποκαρτέλες Καρτέλες 1.2-1.7**

Οι υποκαρτέλες 1.2, 1.3, 1.4, 1.5, 1.6 και 1.7 έρχονται προγεμισμένες από το αίτημα έλεγχου (έχει υλοποιηθεί από τη ΜΟΔ). Θα πρέπει να υπάρχει δυνατότητα επεξεργασίας των πεδίων τους, δηλαδή   όλα τα πεδία να είναι ελεύθερα/ανοικτά για επεξεργασία από τον ελεγκτή, ώστε να γίνονται οι αναγκαίες διορθώσεις σε περίπτωση τροποποιήσεων που διαπιστώνονται, καθώς το αίτημα πρέπει να αποτυπώνει τα ακριβή και ορθά στοιχεία της πράξης που ισχύουν.

**3.Καρτέλα 5**

Στην καρτέλα 5 εφόσον υλοποιηθούν σωστά οι παρατηρήσεις μας στο αίτημα του Δικαιούχου τότε θα μεταφέρονται ορθά και στον έλεγχο-επαλήθευση.

**4. Kαρτέλα 6**

Στην καρτέλα 6 :
α) Ισχύουν οι αντίστοιχες παρατηρήσεις με το αίτημα δικαιούχου

β)  Στα Πληρωτέα Ποσά η σειρά να γίνει ως εξής :
Πληρωτέο ποσό Αιτήματος (ΕΦ) :……………
Πληρωτέο ποσό Αιτήματος (Escrow):………………..
Ποσό Προηγούμενων Πληρωμών (ΕΦ) :………………..
Αναλογούν Ποσό προς καταβολή:…………… (το ποσό αυτό = Πληρωτέο (Ποσό Αιτήματος (ΕΦ)+Πληρωτεό Ποσό Αιτήματος (Escrow))-Ποσό προηγούμενων Πληρωμών).
Ποσό από ποινές/διορθώσεις : …………………. (για περιπτώσεις για συμψηφισμού το οποίο θα αφαιρείται από το Αναλογούν ποσό προς καταβολής)
Τελικό Ποσό προς καταβολή :………… (Αναλογούν ποσό – ποσό από τυχόν ποινές/διορθώσεις συμψηφισμού).

γ) Να μπει πεδίο για σχόλια όσον αφορά στη δόση που έχει υπολογισθεί. (π.χ. αναφορά για τυχόν συμψηφισμό σε σχέση με προηγούμενες πληρωμές, κ.λ.π.).

**4.Καρτέλα 7** 

Να υπάρξει πλήρης Κατάργησης της υπάρχουσας Καρτέλας 7- Έλεγχος φυσικού και Οικονομικού αντικειμένου καθώς καλύπτεται από τις καρτέλες 3.1,3.2 και 3.3 και δεν έχει νόημα η επανάληψή της.

**5.Καρτέλα 8 (πλέον θα είναι η Καρτέλα 7 καθώς στο νυν ΠΣΚΕ προτείναμε τη διαγραφή της υπάρχουσας καρτέλας 7).**

α) Ο τίτλος να γίνει «Σύνοψη ενδιάμεσης επαλήθευσης»
β) Οι ερωτήσεις που πρέπει να υπάρχουν στην καρτέλα με τη σειρά τους και την ορθή έννοια βάση ΣΔΕ και τις οποίες συμπληρώνει ο ελεγκτής του ΕΦΕΠΑΕ να είναι οι εξής :

1. Είδος επαλήθευσης (DROP MENOY) : Διοικητική/Επιτόπια
Παρατηρήσεις : Πεδίο ελεύθερο για Σχόλια

2.Ημερομηνία επιλεξιμότητας δαπανών :…/…./…. 

Την εν λόγω ημερομηνία για το ΠΡΟΓΡΑΜΜΑ ΕΠΙΧΕΙΡΟΥΜΕ ΕΞΩ λόγω ΓΑΚ και δυνατότητας επανυποβολής θα τη βάζει ο ελεγκτής. Για τα υπόλοιπα προγράμματα ψηφιακό βήμα , ψηφιακό άλμα , ποιοτικός εκσυγχρονισμός και τουρισμός (νομίζω) μπορεί να εξάγεται αυτόματα καθώς είναι η ημερομηνία προκήρυξης της δράσης για όλους. 
Παρατηρήσεις : Πεδίο ελεύθερο για σχόλια

3. H επιχείρηση έχει συμμορφωθεί με τους όρους του καθεστώτος στο οποίο έχει υπαχθεί το επιχειρηματικό σχέδιο; (ΝΑΙ/ΟΧΙ)
Παρατηρήσεις : Πεδίο ελεύθερο για σχόλια

4. Ημερομηνία κατάθεσης/παραλαβής φυσικού φακέλου υλοποίησης δαπανών με τα απαιτούμενα δικαιολογητικά από το Δικαιούχο
Παρατηρήσεις : Πεδίο ελεύθερο για σχόλια

5.Ημερομηνία αποστολής εκκρεμοτήτων επαλήθευσης από ΕΦ :………..
Παρατηρήσεις : Πεδίο ελεύθερο για σχόλια

6.Ημερομηνία παραλαβής εκκρεμοτήτων επαλήθευσης από ΕΦ:………..
Παρατηρήσεις : Πεδίο ελεύθερο για σχόλια

7.Ημερομηνία τακτοποίησης και ολοκλήρωσης επαλήθευσης Φυσικού & Οικονομικού Αντικειμένου Δικαιούχου :………….
Παρατηρήσεις : Πεδίο ελεύθερο για σχόλια

8.Ημερομηνία επαλήθευσης ……./……/………..
Παρατηρήσεις: Πεδίο ελεύθερο για σχόλια

9. Ημερομηνία αποστολής δικαιολογητικών μετά την επιτόπια επαλήθευση …/…./…
Παρατηρήσεις : Πεδίο ελεύθερο για σχόλια

Το εν λόγω πεδίο όταν ο έλεγχος είναι διοικητικός δεν απαιτείται να συμπληρωθεί.

10. Ημερομηνία παραλαβής εκκρεμοτήτων μετά την επαλήθευση από ΕΦ:………..
Παρατηρήσεις : Πεδίο ελεύθερο για σχόλια
Το εν λόγω πεδίο όταν ο έλεγχος είναι διοικητικός δεν απαιτείται να συμπληρωθεί.

11. Ημερομηνία τακτοποίησης εκκρεμοτήτων μετά την επαλήθευση από ΕΦ :…………..
Παρατηρήσεις : Πεδίο ελεύθερο για σχόλια

12. Η επαλήθευση κρίνεται θετική; (ΝΑΙ/ΟΧΙ)
Παρατηρήσεις : Πεδίο ελεύθερο για σχόλια

13.Διαπιστώθηκαν αλλαγές στο αίτημα επαλήθευσης σε σχέση με το εγκεκριμένο ΤΠ; (ΝΑΙ/ΟΧΙ)
Παρατηρήσεις : Πεδίο ελεύθερο για σχόλια
Εδώ ο επαληθευτής του ΕΦΕΠΑΕ απαντά στο ερώτημα εάν υπάρχουν οι όχι τροποποιήσεις σε σχέση και με τις απαντήσεις που έχει δώσει στην καρτέλα 3.
Αυτό είναι σημαντικό διότι υπάρχουν τροποποιήσεις που πρέπει να ενσωματώνονται στο αίτημα και τροποποιήσεις που δεν πρέπει.

14.Απαιτείται αίτημα τροποποίησης εκτός αιτήματος επαλήθευσης σύμφωνα με την Αναλυτική Πρόσκληση;  (ΝΑΙ/ΟΧΙ)
Παρατηρήσεις : Πεδίο ελεύυθερο για σχόλια
Εάν ο επαληθευτής του ΕΦΕΠΑΕ απαντήσει με ΝΑΙ τότε :
Η επαλήθευση σταματά και η απάντηση στο ερώτημα 5 είναι ΟΧΙ  καθώς κρίνεται αρνητική. 
Ο δικαιούχος καλείτε μέσω επιστολής να ανοίξει από το μενού των τροποποιήσεων το είδος του αιτήματος που επιθυμεί να υποβάλλει. Το αίτημα τροποποίησης θα αξιολογηθεί και μόλις ολοκληρωθεί η διαδικασία έγκρισης/μη έγκρισης της τροποποίησης από τον Ε.Φ./Επιτροπή Παρακολούθησης, θα μπορεί ο επαληθευτής του Ε.Φ. να περάσει στην έκθεση Πιστοποίησης προκειμένου να ολοκληρώσει την πιστοποίηση.
Αυτή η διαδικασία ακολουθείται και στις 4 δράσεις του ΕΠΑνΕΚ ΚΑΙ ΣΥΝΙΣΤΟΥΜΕ ΝΑ ΙΣΧΥΣΕΙ ΚΑΙ ΣΕ ΟΛΕΣ ΤΙΣ ΝΕΕΣ ΔΡΑΣΕΙΣ.

15.Οι αλλαγές γίνονται δεκτές; (ΝΑΙ/ΟΧΙ)
Παρατηρήσεις : Πεδίο ελεύθερο για σχόλια
Εδώ απαντά ο επαληθευτής του ΕΦΕΠΑΕ όταν έχουμε τροποποποιήσεις ήσσονος σημασίας.

16.Το έργο παραπέμπεται στην Επιτροπή Παρακολούθησης προς εξέταση; (ΝΑΙ/ΟΧΙ)
Παρατηρήσεις : Πεδίο ανοικτό για σχόλια

17. Γενικές Παρατηρήσεις -Συμπεράσματα για την επαλήθευση
Πεδίο ανοικτό για σχόλια.

18. Ονοματεπώνυμα Οργάνου Επαλήθευσης
1.
2. 
Τα ονοματεπώνυμα είναι σημαντικό να υπάρχουν, καθώς ο χρήστης που περνά στοιχεία δεν είναι υποχρεωτικό να ταυτίζεται με τον επαληθευτή.

**6.Καρτέλα 9 (πλέον 8 καθώς προτάθηκε η κατάργηση της 7 που υπάρχει τώρα στο ΠΣΚΕ)** 

Στην καρτέλα αυτή έρχονται τα συνημμένα αρχεία από τον Δικαιούχο 
Συνεπώς θα πρέπει να μπει εδώ το κείμενο που υπάρχει τώρα στο HELP της καρτέλας 10 το οποίο είναι : 
O υποψήφιος υποχρεωτικά πρέπει να υποβάλλει στο ΠΣΚΕ όλα τα κατά περίπτωση απαιτούμενα δικαιολογητικά του ΠΑΡΑΡΤΗΜΑΤΟΣ VIII ΔΙΚΑΙΟΛΟΓΗΤΙΚΑ ΥΠΟΒΟΛΗΣ-ΕΝΤΑΞΗΣ σε μη επεξεργάσιμη ηλεκτρονική μορφή αρχείου (πχ αρχείο τύπου pdf). 
Σας ενημερώνουμε ότι η Αναλυτική Πρόσκληση της δράσης «Επιχειρούμε Έξω» του ΕΠΑνΕΚ (ΕΣΠΑ 2014-2020) έχει τροποποιηθεί με την απόφαση (ΥΠΟΑΝ 4481/1413/Α3/20.07.2018). Παρακαλείσθε όπως ενημερωθείτε για την 2η τροποποίηση της δράσης, πριν την οριστική υποβολή της Αίτησης Χρηματοδότησης
Ανακοίνωση 2ης Τροποποίησης Πρόσκλησης (Link στην τροποποίηση)

**7.Καρτέλα 10 (πλέον 9 καθώς προτάθηκε η κατάργηση της 7 που υπάρχει τώρα στο ΠΣΚΕ)**
Η συγκεκριμένη καρτέλα αφορά τα συνημμένα έγγραφα από τον ΕΦΕΠΑΕ. 
Να διαγραφεί το HELP καθώς αυτό αφορά στον επενδυτή στην καρτέλα 9.
Στο εν λόγω πεδίο αναρτάται το xls για τις δράσεις που έχουν αρκετά όρια 
ποσοτικά εντός κατηγορίας (ΒΗΜΑ, ΑΛΜΑ) και τα οποία δύναται να 
υπολογίζονται εξωσυστημικά (βλέπε ανωτέρω τεχνική επισήμανση).

**8.	Καρτέλα 11**
Στην καρτέλα 11 να υπάρχουν έλεγχοι ορθότητας :
 α) Οι έλεγχοι ορθότητας που αναφέρθηκαν στο Δικαιούχο
β) Στην καρτέλα 5.9 να υπάρχουν υποχρεωτικά σχόλια
γ) Στην καρτέλα 8 με βάση την πρόταση μας να υπάρχει έλεγχος ορθότητας στις ημερομηνίες.
Π.χ  Η ημερομηνία αποστολής εκκρεμοτήτων, δεν μπορεί να είναι προγενέστερη της ημερομηνίας παραλαβής τους, ή της ημερομηνίας διοικητικής επαλήθευσης. 

**9.**Να δημιουργηθεί το εκτυπωτικό της έκθεσης επαλήθευσης των επαληθευτών με αναφορά στα ονοματεπώνυμα που θα υπάρχουν στην καρτέλα 7 (με βάση τη νέα αρίθμηση).

**Comment by apanagio** [comment]
υλοποιήθηκαν
