### ISSUE TITLE
Έλεγχος τόπων υλοποίησης

### ISSUE THREAD

**Issue by apanagio** [mou-gr/regions#14]
Όταν δηλώνονται παραπάνω από ένας τόπος υλοποίησης να ελέγχεται αν ανήκει στην ίδια περιφέρεια

**Comment by apanagio** [comment]
Είναι δύσκολο να γίνει με γενικό τρόπο. Μπορεί να μπει banner και να ελέγχεται στην αξιολόγηση. Εναλλακτικά μπορεί να επιτρέπεται μόνο ένας τόπος επένδυσης.

**Comment by mariaelanet** [comment]
Στον έλεγχο ορθότητας χτυπάει ότανέχει πάνω από έναν τόπο υλοποίησης ενώ ο οδηγός δεν το απαγορεύει

**Comment by galanosel** [comment]
Έχει υλοποιηθεί και θα ανέβει staging
