### ISSUE TITLE
ΕΠΙΧΕΙΡΟΥΜΕ ΕΞΩ - ΠΙΣΤΟΠΟΙΗΣΗ ΕΝΔΙΑΜΕΣΗΣ ΕΠΑΛΗΘΕΥΣΗΣ

### ISSUE THREAD

**Issue by tsitsopoulosexo** [mou-gr/regions#140]
Σε συνέχεια της συνάντησης μας την Παρασκευή 19/10/2018 σας αποστέλλω τις προδιαγραφές για την πιστοποίηση αιτήματος ενδιάμεσης επαλήθευσης.

**ΠΙΣΤΟΠΟΙΗΣΗ-ΕΚΘΕΣΗ ΠΙΣΤΟΠΟΙΗΣΗΣ**
Η ενέργεια της θα αποτελείται επίσης από 10 καρτέλες.
Στην ουσία θα έρχεται η επαλήθευση (έλεγχος) του ΕΦ προσυμπληρωμένα και ανοικτά προς επεεξεργασία. 
Ισχύουν όλες οι προηγούμενες παρατηρήσεις που αφορούν στην έκθεση επαλήθευσης (ελέγχου). 
**Η μόνη καρτέλα που θα διαφοροποιηθεί σε σχέση με την επαλήθευση(έλεγχος) είναι η καρτέλα 7.**

**Καρτέλα 7**
Η καρτέλα 7 θα διαμορφωθεί σε δύο υποκαρτέλες ως εξής :

1)	**Υποκαρτέλα 7.1** 
Θα υπάρχουν οι ερωτήσεις 1-18 που θα έρχονται προσυμπληρωμένες από το προηγούμενος στάδιο της επαλήθευσης.
2)	**Υποκαρτέλα 7.2**
7.2.1 : Το έργο παραπέμπεται στην Επιτροπή Παρακολούθησης προς εξέταση; (Επιλογή από drop menu ΝΑΙ/ΟΧΙ)
Η απάντηση μπορεί να έρχεται από την ερώτηση 11 της υποκαρτέλας 7.1.
Παρατηρήσεις : Ελεύθερο πεδίο για σχόλια

7.2.2 : Εισήγηση ΕΦΕΠΑΕ προς την Επιτροπή Παρακολούθησης (Επιλογή από drop menu Θετική/αρνητική)
Παρατηρήσεις : Ελεύθερο πεδίο για σχόλια

7.2.3 : Ημερομηνία Παραπομπής στην Επιτροπή Παρακολούθησης : …/…./….
Όταν η απάντηση στο 7.2.1 είναι ΟΧΙ τότε δεν είναι υποχρεωτική η συμπλήρωση
Παρατηρήσεις : Ελεύθερο πεδίο για σχόλια

7.2.4 : Ημερομηνία συνεδρίασης της Επιτροπής Παρακολούθησης : …/…./…
Δεν είναι υποχρεωτική η συμπλήρωση όταν η απάντηση στο 7.2.1 είναι ΟΧΙ.
Παρατηρήσεις : Ελεύθερο πεδίο για σχόλια

7.2.5 : Συμπέρασμα Επιτροπής Παρακολούθησης (ως προς την εισήγηση του ΕΦΕΠΑΕ) : Επιλογή από drop menu Θετική/αρνητική/Δεν απαιτείται)
Οταν η απάντηση στο 7.2.1 είναι ΟΧΙ τότε υποχρεωτικά η απάντηση είναι ΔΕΝ ΑΠΑΙΤΕΙΤΑΙ.
Παρατηρήσεις : Ελεύθερο πεδίο για σχόλια

7.2.6 Το αποτέλεσμα της επαλήθευσης μετά και τις όποιες τροποποιήσεις οδηγεί σε εγκριτική πιστοποίηση; (Επιλογή από drop menu ΝΑΙ/ΟΧΙ)
Παρατηρήσεις : Ελεύθερο πεδίο για σχόλια.
7.2.7 Ημερομηνία απόφασης πιστοποίησης (θετικής/αρνητικής) …/…./……
Παρατηρήσεις : Ελεύθερο Πεδίο για Σχόλια
Υποχρεωτικά θα αναγράφεται ο Α.Π. του πρακτικού της Επιτροπής Εργασιών.

7.2.8 Τυχόν παρατηρήσεις 
Παρατηρήσεις : Ελεύθερο Πεδίο για σχόλια. Μη υποχρεωτικά σχόλια.

**ΕΛΕΓΧΟΙ ΟΡΘΟΤΗΤΑΣ**
-Ισχύουν οι έλεγχοι ορθότητας στην επαλήθευση (έλεγχος)
- Επιπλέον έλεγχοι ορθότητας με τις ημερομηνίες. 

**ΕΚΥΠΩΤΙΚΑ.**
-Να υπάρξει εκτυπωτικό.
-Να διερευνηθεί η δυνατότητα από την πιστοποίηση να παράγεται ΤΠ όταν έχουμε έγκριση αλλαγών είτε από ΕΦ είτε από Επιτροπή Παρακολούθησης.

**Comment by apanagio** [comment]
υλοποιήθηκαν (εκοα από τα εκτυπωτικά)
