### ISSUE TITLE
ΕΠΙΧΕΙΡΟΥΜΕ ΕΞΩ ΚΑΙ ΠΟΙΟΤΙΚΟΣ ΕΚΣΥΓΧΡΟΝΙΣΜΟΣ- ΠΑΡΑΤΗΡΗΣΕΙΣ ΔΙΚΑΙΟΛΟΓΗΤΙΚΩΝ ΕΝΔΙΑΜΕΣΗΣ ΕΚΤΑΜΙΕΥΣΗΣ

### ISSUE THREAD

**Issue by tsitsopoulosexo** [mou-gr/regions#141]
Καλημέρα

Σας αποστέλλω τις παρατηρήσεις επί του ελέγχου δικαιολογητικών ενδιάμεσης εκταμίευσης που αναρτήθηκε στη staging.
Οι παρατηρήσεις έχουν διαμορφωθεί σε συνεργασία με τον υπεύθυνο Ποιοτικού Εκσυγχρονισμού και υποβάλλονται και για τις δύο μαζί. 

**ΠΑΡΑΤΗΡΗΣΕΙΣ**

**1.Στις καρτέλες 1-9, ισχύουν οι παρατηρήσεις μας που έχουν αποσταλεί και αφορούν στον έλεγχο και στην πιστοποίηση.** 
Ειδικότερα, επαναλαμβάνουμε ορισμένες εξ’ αυτών : 

-_Καρτέλα 1.1 Στοιχεία Αιτήματος επαλήθευσης_
Να έρχονται προσυμπηρωμένα και τα βασικά στοιχεία της επένδυσης από την προηγούμενη ενέργεια έκθεση Πιστοποίησης
-_Καρτέλα 7- Έλεγχος φυσικού και Οικονομικού Αντικειμένου_
Να καταργηθεί η καρτέλα (οι ερωτήσεις που υπάρχουν καλύπτονται από τις καρτέλες 3.1,3.2 και 3.3.)
-_Καρτέλα 8-Σύνοψη έκθεσης ενδιάμεσου ελέγχου_
Να προσαρμοσθεί η καρτέλα σύμφωνα με την αντίστοιχη στην ενέργεια της έκθεσης Πιστοποίησης με βάση τις παρατηρήσεις μας.
-_Καρτέλα 9-Αξιολόγηση από την Επιτροπή Παρακολούθησης_
Να προσαρμοσθεί η καρτέλα σύμφωνα με την αντίστοιχη στην ενέργεια της έκθεσης Πιστοποίησης με βάση τις παρατηρήσεις μας.

2. **Στο έλεγχο δικαιολογητικών θα πρέπει όταν εισέρχεται ο ελεγκτής να υπάρχει κατ’ αντιστοιχία με την αίτηση επαλήθευσης πεδίο όπου θα καταχωρείται η ημερομηνία παραλαβής του φακέλου του Δικαιούχου με τον Α.Π.** 

3. **Να υπάρχει εκτυπωτικό της διαδικασίας ελέγχου.  Να δούμε για εξοικονόμηση χρόνου και σελίδων η εκτύπωση να μην περιλαμβάνει το σύνολο των καρτελών αλλά τις καρτέλες 1, 10, 11, 12.**

**4. Καρτέλα 10**
**4.1 Υποκαρτέλα 10.1**
-Η καρτέλα 10  θα πρέπει να μετονομασθεί από (ΕΚΘΕΣΗ ΕΠΑΛΗΘΕΥΣΗΣ/ΠΙΣΤΟΠΟΙΗΣΗΣ ΔΑΠΑΝΩΝ) σε «ΕΛΕΓΧΟΣ ΔΙΚΑΙΟΛΟΓΗΤΙΚΩΝ ΚΑΤΑΒΟΛΗΣ ΕΝΙΣΧΥΣΗΣ»

- Εδώ θα υπάρχει ΥΠΟΧΡΕΩΤΙΚΑ διαφοροποίηση και Παραμετροποίηση ανά Δράση στα λεκτικά των απαιτούμενων δικαιολογητικών.

_Προτείνεται η καρτέλα 10.1 να διαφοροποιείται ανά Δράση προκειμένου να αποφεύγονται άσκοπες συμπληρώσεις δικαιολογητικών με την επιλογή ΔΕΝ ΑΠΑΙΤΕΙΤΑΙ._
Ο ΕΦΕΠΑΕ ζητά η καρτέλα να αλλάζει όπως η καρτέλα 3.3 που αφορά στο ΦΟΑ κάθε Δράσης.

Συνεπώς η καρτέλα 10.1 :

**Α) Για τη Δράση «ΕΠΙΧΕΙΡΟΥΜΕ ΕΞΩ» τα δικαιολογητικά που πρέπει να αναγραφούν σύμφωνα με την πρόσκληση της Δράσης είναι :**
                             ΕΠΙΛΟΓΕΣ ΠΣΚΕ : ΝΑΙ/ΟΧΙ/ΔΕΝ ΑΠΑΙΤΕΙΤΑΙ

1.Κατάσταση ενεργών δραστηριοτήτων (ΚΑΔ) της επιχείρησης μέσω της ιστοσελίδας gsis.gr (πρόσφατη εκτύπωση)
2.Τροποποιήσεις του καταστατικού σύστασης της εταιρίας/μεταβολές στη ΔΟΥ (για ατομικές επιχειρήσεις), εφόσον έχουν υπάρξει.
3.Βεβαίωση περί μη περαιτέρω τροποποίησης του καταστατικού/ Για τις ατομικές επιχειρήσεις Υ.Δ. Ν1599/86 με θεώρηση για το γνήσιο της υπογραφής περί με μεταβολής ότι δεν έχουν τροποποιηθεί/ μεταβληθεί τα στοιχεία της ατομικής επιχείρησης από την ημερομηνία υποβολής έως σήμερα.
4.Αποδεικτικό φορολογικής ενημερότητας Κεντρικής Διοίκησης ή Βεβαίωση παρακράτησης (απόδοσης) φόρων.
5.Αποδεικτικό ασφαλιστικής ενημερότητας ή Βεβαίωση παρακράτησης (απόδοσης) ασφαλιστικών εισφορών .
6.Πιστοποιητικό περί μη Κατάθεσης Αίτησης Πτώχευσης.
7.Πιστοποιητικό περί μη Κατάθεσης Αίτησης για Πτωχευτικό Συμβιβασμό
8. Πιστοποιητικό περί μη Κατάθεσης Αίτησης για Παύση Πληρωμών
9. Πιστοποιητικό περί μη Κατάθεσης Αίτησης για Συνδιαλλαγή – Εξυγίανση κατ’ άρθρο 99 Ν. 3588/07 (αφορά και έκδοση απόφασης).
10. Πιστοποιητικό περί μη Κατάθεσης Αίτησης για Διορισμό ή Αντικατάσταση Εκκαθαριστή ή Συνεκκαθαριστή.
11. Πιστοποιητικό περί μη Κατάθεσης Αίτησης για Θέση σε Ειδική Εκκαθάριση( αφορά και έκδοση απόφασης).
12. Πιστοποιητικό περί μη Κατάθεσης Σχεδίου Αναδιοργάνωσης( αφορά και έκδοση απόφασης).
13. Πιστοποιητικό περί μη Θέσης σε Αναγκαστική Διαχείριση.
14. Πιστοποιητικό περί μη Κατάθεσης Αίτησης σε Αναγκαστική Διαχείριση.
15.Πιστοποιητικό περί μη Πτώχευσης.
16. Υπεύθυνη Δήλωση νομίμου εκπροσώπου με γνήσιο υπογραφής όπου δηλώνεται ότι δεν έχουν υποβληθεί σε βάρος της επιχείρησης οι κυρώσεις της παραγράφου 1 του άρθρου 40 του Ν. 4488/2017 (Α137/13.09.2017).
17. Απόδειξη είσπραξης επιχορήγησης ή έγγραφο ισοδύναμης αποδεικτικής αξίας.
18.Σύμβαση εκχώρησης επιχορήγησης έναντι δανείου και βεβαίωση εκταμίευσης αυτού, εφόσον έχει γίνει εκχώρηση
19.Υπεύθυνη Δήλωση νομίμου εκπροσώπου με θεώρηση για το γνήσιο της  υπογραφής όπου δηλώνεται ότι δεν έχει εκχωρηθεί η επιχορήγηση, εφόσον δεν έχει γίνει εκχώρηση.
20. Απόδειξη είσπραξης επιχορήγησης ή έγγραφο ισοδύναμης αποδεικτικής αξίας
21.Τυχόν δικαιολογητικά που απαιτούνται σύμφωνα με τους ειδικούς όρους που ενδεχομένως αναφέρονται στη σύμβαση ή στο Τεχνικό Παράρτημα
22. Άλλο (για ειδικές περιπτώσεις που απαιτηθεί δικαιολογητικό που δεν προβλέπεται στην Πρόσκληση αλλά είναι απαραίτητο)

**Β) Για τη Δράση «ΠΟΙΟΤΙΚΟΣ ΕΚΣΥΓΧΡΟΝΙΣΜΟΣ» τα δικαιολογητικά που πρέπει να αναγραφούν σύμφωνα με την πρόσκληση της Δράσης είναι **
                                      ΕΠΙΛΟΓΕΣ ΠΣΚΕ : ΝΑΙ/ΟΧΙ/ΔΕΝ ΑΠΑΙΤΕΙΤΑΙ

1.Κατάσταση ενεργών δραστηριοτήτων (ΚΑΔ) της επιχείρησης μέσω της ιστοσελίδας gsis.gr (πρόσφατη εκτύπωση).
2.Τροποποιήσεις του καταστατικού σύστασης της εταιρίας/μεταβολές στη ΔΟΥ (για ατομικές επιχειρήσεις), εφόσον έχουν υπάρξει.
3.Βεβαίωση περί μη περαιτέρω τροποποίησης του καταστατικού/ Για τις ατομικές επιχειρήσεις Υ.Δ. Ν1599/86 με θεώρηση για το γνήσιο της υπογραφής περί με μεταβολής ότι δεν έχουν τροποποιηθεί/ μεταβληθεί τα στοιχεία της ατομικής επιχείρησης από την ημερομηνία υποβολής έως σήμερα.
4.Αποδεικτικό φορολογικής ενημερότητας Κεντρικής Διοίκησης ή Βεβαίωση παρακράτησης (απόδοσης) φόρων.
5.Αποδεικτικό ασφαλιστικής ενημερότητας ή Βεβαίωση παρακράτησης (απόδοσης) ασφαλιστικών εισφορών .
6.Πιστοποιητικό μη πτώχευσης. 
7.Πιστοποιητικό μη αίτησης για πτώχευση.
8.Πιστοποιητικό μη θέσης σε εκκαθάριση.
9.Πιστοποιητικό μη θέσης σε αναγκαστική διαχείριση.
10.Σύμβαση εκχώρησης επιχορήγησης έναντι δανείου και βεβαίωση εκταμίευσης αυτού, εφόσον έχει γίνει εκχώρηση.
11.Υπεύθυνη Δήλωση νομίμου εκπροσώπου με θεώρηση για το γνήσιο υπογραφής όπου δηλώνεται ότι δεν έχει εκχωρηθεί η επιχορήγηση, εφόσον δεν έχει γίνει εκχώρηση.
12.Απόδειξη είσπραξης επιχορήγησης ή έγγραφο ισοδύναμης αποδεικτικής αξίας.
13.Τυχόν δικαιολογητικά που απαιτούνται σύμφωνα με τους ειδικούς όρους που ενδεχομένως αναφέρονται στη σύμβαση ή στο Τεχνικό Παράρτημα
14.Άλλο (για ειδικές περιπτώσεις που απαιτηθεί δικαιολογητικό που δεν προβλέπεται στην Πρόσκληση αλλά είναι απαραίτητο).

**4.2 Υποκαρτέλα 10.2**
Στην υποκαρτέλα 10.2 Τελική Κρίση απαιτούνται ορισμένες προσθήκες, εκφραστικές επαναδιατυπώσεις καθώς και αλλαγή σειράς των ερωτήσεων.
Η σειρά των ερωτημάτων και οι φράσεις που θα πρέπει να εμφανίζονται στην καρτέλα είναι η κάτωθι :

1.Ημερομηνία Ηλεκτρονικής Υποβολής Έκθεσης Επαλήθευσης Δαπανών από ΕΦ
(Ημερομηνία που ο ΕΦ υποβάλλει την έκθεση των ελεγκτών στο ΠΣΚΕ και πηγαίνει στο στάδιο της πιστοποίησης)
Σχόλια :……..

2. Ημερομηνία έγκρισης πιστοποίησης από ΕΦ : …./…/…. 
(Ημερομηνία που ο ΕΦ εγκρίνει την πιστοποίηση βάσει του πρακτικού της Επιτροπής Έγκρισης Εργασιών του ΕΦ)
Σχόλια :……….

3.Ημερομηνία Ηλεκτρονικής Υποβολής Έκθεσης Πιστοποίησης Δαπανών από ΕΦ
(Ημερομηνία αυτή αφορά πότε ο ΕΦ οριστικοποίησε στο ΠΣΚΕ την έκθεση πιστοποίησης δαπανών μετά την έκδοση του πρακτικού της Επιτροπής Εργασιών του ΕΦ).
Σχόλια :………

4.Ημερομηνία παραλαβής φακέλου δικαιολογητικών επιχορήγησης από ΕΦ  : …/…./……..
Σχόλια :……….

5. Ημερομηνία αποστολής εκκρεμοτήτων στο Δικαιούχο (επιχείρηση) :…./…../……
Σχόλια :………..

6. Ημερομηνία παραλαβής εκκρεμοτήτων Δικαιούχου από ΕΦ: ……/…./…….
Σχόλια :………..

7. Ημερομηνία τακτοποίησης και ολοκλήρωσης ελέγχου δικαιολογητικών από ΕΦ : …./…./………….
Σχόλια :………

8. Έγκριση Εκταμίευσης (ΝΑΙ/ΟΧΙ)
Σχόλια : ………..

9. -Ποσό προς καταβολή (Ε.Φ.) :…………..€.
(να έρχεται συμπληρωμένο αλλά ελεύθερο για επεξεργασία από την καρτέλα 6-πληρωτέα ποσά –ποσό προς καταβολή Ε.Φ.)
 -Ποσό προς Καταβολή Escrow :……………€.
(να έρχεται συμπληρωμένο αλλά ελεύθερο για επεξεργασία από την καρτέλα 6-πληρωτέα ποσά-πληρωτέο ποσό αιτήματος escrow)
Σχόλια :………….. 

10. Τράπεζα Δικαιούχου  (επιλογή από filter) :………….

11. Αριθμός Εταιρικού Λογαριασμού IBAN Δικαιούχου :  ………..
Σχόλια 
Στον αριθμό λογαριασμού να γίνεται έλεγχος ορθότητας του λογαριασμού.

**6. Δεν υφίσταται το πεδίο 13 για τον έλεγχο ορθότητας και την υποβολή του ελέγχου δικαιολογητικών.**

**Έλεγχοι ορθότητας (σε παρένθεση ο α/α σειράς των σημείων που περιγράφονται ανωτέρω) :**

Οι έλεγχοι αφορούν κυρίως στις ημερομηνίες του πεδίο 10.2 Τελική κρίση. Συγκεκριμένα :

1)Η ημερομηνία ηλεκτρονικής υποβολής της έκθεσης πιστοποίησης (1) από ΕΦ να είναι μεταγενέστερη της ημερομηνίας ηλεκτρονικής υποβολής της έκθεσης επαλήθευσης (3)

2) Η ημερομηνία έγκρισης πιστοποίησης (2) είναι προγενέστερη από την ημερομηνία ηλεκτρονικής υποβολής της έκθεσης πιστοποίησης (3) από ΕΦ και είναι μεταγενέστερη της ημερομηνίας ηλεκτρονικής υποβολής της έκθεσης επαλήθευσης (1).

3) Η ημερομηνία αποστολής εκκρεμοτήτων από το Δικαιούχο (5) είναι μεταγενέστερη από την ημερομηνία ηλεκτρονικής υποβολής της έκθεσης πιστοποίησης από ΕΦ (3) και την ημερομηνία ηλεκτρονικής υποβολής της έκθεσης επαλήθευσης (1).

4) Η ημερομηνία ελέγχου παραλαβής δικαιολογητικών (4) είναι μεταγενέστερη από την ημερομηνία αποστολής εκκρεμοτήτων (5).

5)Η προτεινόμενη να προστεθεί «Ημερομηνία τακτοποίησης και ολοκλήρωσης ελέγχου δικαιολογητικών από ΕΦ» (7) είναι μεταγενέστερη από την ημερομηνία αποστολής εκκρεμοτήτων (5) και την ημερομηνία παραλαβής εκκρεμοτήτων (6).

6)Η ημερομηνία ολοκλήρωσης του ελέγχου (7)  είναι μεταγενέστερη της ημερομηνίας υποβολής του φακέλου δικαιολογητικών (4), της ημερομηνίας αποστολής εκκρεμοτήτων (5) και της ημερομηνία παραλαβής των εκκρεμοτήτων (6)

Παρακαλούμε τη διευθέτηση των ανωτέρω παρατηρήσεων.

Ιωάννης Τσιτσόπουλος/ΕΠΙΧΕΙΡΟΥΜΕ ΕΞΩ     
Χριστόφορος Λιακόπουλος /ΠΟΙΟΤΙΚΟΣ ΕΚΣΥΓΧΡΟΝΙΣΜΟΣ

**Comment by apanagio** [comment]
υλοποιήθηκαν
