### ISSUE TITLE
ΠΕΠ : - "Αξιολόγηση Ένστασης"

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#150]
Δημιουργία νέου tab στο βήμα 11, με τίτλο : "Αποτέλεσμα Αξιολόγησης Έντασης από Επιτροπή"

-το tab αυτό θα έχει τα πεδία :
Ημερομηνία υποβολής ένστασης
Η Επιτροπή εξέτασε την αίτηση ένστασης;
Ημερομηνία εξέτασης της ένστασης
Εισήγηση Επιτροπής επί απόφασης ενστάσεως
Τεκμηρίωση Απόφασης Επιτροπής
Ημερομηνία Συνεδρίασης
Αριθμός Απόφασης (ΑΠ/Ημερομηνία)

-Θα είναι όλα  required, εκτός από το : (Αριθμός Απόφασης (ΑΠ/Ημερομηνία))

-Να επιβεβαιώσεις ότι δεν θα χαλάσει ο πίνακας στο διπλανό tab ΛΟΓΟΙ ΕΝΣΤΑΣΗΣ ΠΡΑΞΗΣ που θα παραμείνει,  όσον αφορά τα προσυμπληρωμένα πεδία του που έρχονται από το αίτημα ένστασης του δικαιούχου. 

-ΝΑ ΥΛΟΠΟΙΗΣΟΥΜΕ ΥΠΟΧΡΕΩΤΙΚΌ ΈΛΕΓΧΟ ΟΡΘΌΤΗΤΑΣ μιας εγγραφής στο νέο tab με τίτλο : Αποτέλεσμα Αξιολόγησης Έντασης από Επιτροπή

**Comment by galanosel** [comment]
Θα πρέπει να μετονομαστεί το ήδη υπάρχον tab με τίτλο "ΑΞΙΟΛΟΓΗΣΗ ΑΙΤΗΣΗΣ ΕΝΣΤΑΣΗΣ ΑΠΟ ΕΠΙΤΡΟΠΗ ΕΝΣΤΑΣΕΩΝ" καθώς στις δράσεις των ΠΕΠ η καρτέλα αυτή δεν θα περιέχει την αξιολόγηση του αίτηματος..
Τί τίτλο να βάλω;

**Comment by JimLavrentzos** [comment]
Υλοποιήθηκε για test στην Staging στην Δράση 'ΕΝΙΣΧΥΣΗ ΣΧΕΔΙΩΝ ΕΡΕΥΝΑΣ-ΑΝΑΠΤΥΞΗΣ ΕΠ. Ν. ΑΙΓΑΙΟΥ'

**Comment by sadamaki** [comment]
-οκ με : Έλεγχος ορθότητας για το νέο tab : [ΑΠΟΤΕΛΕΣΜΑ ΑΞΙΟΛΟΓΗΣΗΣ ΕΝΣΤΑΣΗΣ ΑΠΟ ΕΠΙΤΡΟΠΗ] Ελάχιστος αριθμός εγγραφών: 1
-οκ με πεδία νέου tab
