### ISSUE TITLE
ΠΕΠ : - "Αξιολόγηση Ένστασης" 

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#151]
Βήμα 11: tab "ΑΞΙΟΛΟΓΗΣΗ ΑΙΤΗΣΗΣ ΕΝΣΤΑΣΗΣ ΑΠΟ ΕΠΙΤΡΟΠΗ ΕΝΣΤΑΣΕΩΝ" : να βάλουμε helptext "όπως συμπληρωθούν τα πεδία που αφορούν την Κρίση αξιολογητή σχετικά με το λόγο ή τους λόγους ένστασης που έχει αιτηθεί ο δικαιούχος"

**Comment by sadamaki** [comment]
Σημείωση : για το ιστορικό, όλα τα παραπάνω γίνονται για το λόγο ότι δεν μπορεί να υλοποιηθεί έλεγχος ορθότητας υποχρεωτικής εγγραφής στον πίνακα

**Comment by galanosel** [comment]
Ο έλεγχος ορθότητας μπορεί να γίνει.
Θα πρέπει να ανοίξει όμως νέα καρτέλα όπου θα καταχωρείται η πληροφορία της της αξιολόγησης αίτησης ένστασης απο την επιτροπή ενστάσεων επομένως θα πρέπει να αλλάξει ο τίτλος της ήδη υπάρχουσας καρτέλας "ΑΞΙΟΛΟΓΗΣΗ ΑΙΤΗΣΗΣ ΕΝΣΤΑΣΗΣ ΑΠΟ ΕΠΙΤΡΟΠΗ ΕΝΣΤΑΣΕΩΝ".

**Comment by sadamaki** [comment]
Η  νέα καρτέλα προτείνω να έχει τίτλο όπως σου αναφέρω στο issue 150.
Kαι επειδή και στην υφιστάμενη καρτέλα έτσι όπως έχει σχεδιαστεί πρέπει να μπει να συμπληρώσει όλα τα πεδία που υπάρχουν στον 1ο πίνακα κάτω απο τα read onyl πεδία του δικαιούχου., προτείων να βάλουμε το helptext Που σου αναφέρω (μιας που σε αυτή την καρτέλα τεχνικά δεν μπορεί να αποτυπωθεί κάποιος έλεγχος ορθότητας για την συμπλήρωση των πεδίων του 1ου πίνακα)

**Comment by sadamaki** [comment]
Στο βήμα 11 και στο Tab ΑΞΙΟΛΟΓΗΣΗ ΑΙΤΗΣΗΣ ΕΝΣΤΑΣΗΣ ΑΠΟ ΕΠΙΤΡΟΠΗ ΕΝΣΤΑΣΕΩΝ" : να βάλουμε helptext 

"όπως συμπληρωθούν τα πεδία που αφορούν την κρίση αξιολογητή σχετικά με το λόγο ή τους λόγους ένστασης που έχει αιτηθεί ο δικαιούχος"

**Comment by JimLavrentzos** [comment]
Έχει υλοποιηθεί για όλα τα ΠΕΠ στην Staging

**Comment by sadamaki** [comment]
OK
