### ISSUE TITLE
ΑΙΤΗΜΑ ΕΛΕΓΧΟΥ-TAB 3.2- Πεδία

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#159]
Στο tab 3.2 για τα ΠΕΠ η ΕΥΚΕ θέλει να υπάρχουν μόνο τα εξής πεδία (λογικά θα αλλάξει η αρίθμηση τους). :

2. Σύντομη περιγραφή συνολικής προόδου φυσικού αντικειμένου μέχρι την υποβολή του παρόντος αιτήματος.

3. Το φυσικό αντικείμενο που υλοποιήθηκε είναι σύμφωνο με το εγκεκριμένο όπως ισχύει;

Παρατηρήσεις :

5. Έχουν εκδοθεί όλες οι τυχόν απαιτούμενες άδειες (π.χ. άδεια δόμησης, έγκριση εργασιών μικρής κλίμακας κλπ) για την υλοποίηση των εργασιών της επένδυσης;

Παρατηρήσεις :

6. Ο εξοπλισμός που προμηθεύτηκε ο Δικαιούχος είναι καινούργιος και αμεταχείριστος;

Παρατηρήσεις:

7. Η επένδυση που πραγματοποιήθηκε αφορά αποκλειστικά σε ΚΑΔ που ορίζονται στην αξιολόγηση;

Παρατηρήσεις :

**Comment by JimLavrentzos** [comment]
Εχει υλοποιηθεί για όλα τα ΠΕΠ στην Staging

**Comment by sadamaki** [comment]
Δημήτρη, βρήκα ένα ΠΕΠ που δεν έχει γίνει πχ ΚΡΗΡ3
Μήπως να δεις αν έχει ξεφύγει κάτι και από κάποιο άλλο ΠΕΠ σχετικά με το issue?

**Comment by sadamaki** [comment]
α΄ΚΥΡΟ είναι οκ τώρα και στο ΠΕΠ Κρ΄ήτης.

Ολοκληρώνω το issue
