### ISSUE TITLE
Βοηθητικά κείμενα

### ISSUE THREAD

**Issue by apanagio** [mou-gr/regions#16]
Προτείνεται να μπει πεδίο   το οποίο θα αναφέρει : Πιστοποίηση συστημάτων διασφάλισης ποιότητας και περιβαλλοντικής διαχείρισης/ μέχρι 3.000,00€ ανά πιστοποιητικό  συμπεριλαμβανομένων των προκαταρκτικών της πιστοποίησης δαπανών , Επαγγελματικές Εκθέσεις που γίνονται στην Ελλάδα, το συνολικό επιλέξιμο κόστος (κόστος συμμετοχής, διαμονή, μετακίνηση, μεταφορά υλικών κλπ) δεν θα υπερβαίνει τις 3.000€/ έκθεση, Επαγγελματικές Εκθέσεις που γίνονται στο Εξωτερικό το συνολικό επιλέξιμο κόστος (κόστος συμμετοχής, διαμονή, μετακίνηση, μεταφορά υλικών κλπ) δεν θα υπερβαίνει τις 6.000€/ έκθεση , Το κόστος παραμετροποίησης Λογισμικού/Εφαρμογών και εκπαίδευσης στη χρήση αυτών είναι επιλέξιμο ως δαπάνη μέχρι και 20% του κόστους αγοράς του λογισμικού/εφαρμογής.

**Comment by apanagio** [comment]
Αν καταλαβαίνω καλά θέλετε ένα banner κάπου στις δαπάνες;
Στείλτε το ακριβές κείμενο που θέλετε και θα μπει

**Comment by mariaelanet** [comment]
Όρια επιλεξιμότητας δαπανών σύμφωνα με την Πρόσκληση:
•	Πιστοποίηση συστημάτων διασφάλισης ποιότητας και περιβαλλοντικής διαχείρισης/ μέχρι 3.000,00€ ανά πιστοποιητικό συμπεριλαμβανομένων των προκαταρκτικών της πιστοποίησης δαπανών και μέχρι 12.000€.
•	Προβολή – Προώθηση μέχρι 15.000€
•	Το κόστος για τη δημιουργία ιστοσελίδας μέχρι 2.500€
•	Επαγγελματικές Εκθέσεις που γίνονται στην Ελλάδα, το συνολικό επιλέξιμο κόστος (κόστος συμμετοχής, διαμονή, μετακίνηση, μεταφορά υλικών κλπ) δεν θα υπερβαίνει τις 3.000€/ έκθεση
•	 Επαγγελματικές Εκθέσεις που γίνονται στο Εξωτερικό το συνολικό επιλέξιμο κόστος (κόστος συμμετοχής, διαμονή, μετακίνηση, μεταφορά υλικών κλπ) δεν θα υπερβαίνει τις 6.000€/ έκθεση 
•	Δαπάνες τεχνικών μελετών Μηχανικού και υπηρεσιών Φοροτεχνικού και Νομικού Συμβούλου μέχρι 40.000€
•	Λογισμικά και Υπηρεσίες Παραμετροποίησης Λογισμικού μέχρι 10.000€. 
•	Το κόστος παραμετροποίησης Λογισμικού/Εφαρμογών και εκπαίδευσης στη χρήση αυτών είναι επιλέξιμο ως δαπάνη μέχρι και 20% του κόστους αγοράς του λογισμικού/εφαρμογής.
•	Μεταφορικά μέσα μέχρι 25.000€. 
•	Σύνταξη και Παρακολούθηση υλοποίησης του Επενδυτικού Σχεδίου μέχρι 4.000€.
•	Η σύνταξη  της αίτησης χρηματοδότησης μέχρι  1.000 €.
