### ISSUE TITLE
ΠΟΙΟΤΙΚΟΣ ΕΚΣΥΓΧΡΟΝΙΣΜΟΣ : ΑΙΤΗΜΑ ΕΛΕΓΧΟΥ (δαπάνες διαφοροποιημένες κατά 20%)

### ISSUE THREAD

**Issue by chliakop** [mou-gr/regions#161]
Η Αναλυτική Πρόσκληση της Δράσης στο Κεφάλαιο 11.1-τροποποποιήσεις ΦΟΑ αναφέρει μετάξύ άλλων : "Αλλαγή δαπάνης/δαπανών συνολικής αξίας ίσης, ως ποσοστό, με το 20% του συνολικού
επιχορηγούμενου Π/Υ του επενδυτικού σχεδίου, με νέα/νέες δαπάνες εντός της ίδιας
Κατηγορίας δαπανών για τις οποίες, τις νέες δαπάνες, τεκμηριώνεται σωρευτικά ότι:
1) υπακούουν στους κανόνες επιλεξιμότητας δαπανών της κατηγορίας
2) εξυπηρετούν καλύτερα τις ανάγκες της επένδυσης
3) δεν ξεπερνούν το εγκεκριμένο συνολικό κόστος (συνολική τιμή) των αρχικών
δαπανών που αλλάζονται."

Οπότε σύμφωνα με το  ανωτέρω μπορείς να αλλάξεις δαπάνες μέσα στην ίδια κατηγορία, μέχρι το 20% του επιχ.Π/Υ και χωρίς να ξεπεράσεις το εγκεκριμένο συνολικό κόστος των αρχικά εγκεκριμένων δαπανών που αλλάζονται.
Αυτό σημαίνει ότι δεν μπορείς να κάνεις αύξηση ποσού σε κατηγορία δαπάνης πάνω από το ποσό που έχει εγκριθεί. 
Σε παράδειγμα που έκανα στη staging αυτή τι στιγμή σε αφήνει να πάς σε αύξηση ποσού σε κατηγορία δαπάνης σε σχέση με την έγκριση, έως το 20% του ποσού της εγκεκριμένης αξίας της δαπάνης. Αυτό όμως δεν συνάδει μ'αυτό που ανωτέρω αναφέρει η Πρόσκληση.
Προτείνω επομένως να επανέλθει το αίτημα σε προηγούμενο status (έλεγχος των ανώτατων εγκεκριμένων ποσών ανά ακτηγορία δαπάνης) και να δούμε συνολικά πώς θα εφαρμοσθούν οι τροποποποιήσεις ΦΟΑ εντός του αιτήματος.

**Comment by apanagio** [comment]
υλοποιήθηκε
