### ISSUE TITLE
ΑΙΤΗΜΑ ΕΛΕΓΧΟΥ-TAB 5.2 ΔΑΠΑΝΕΣ 

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#163]
-TAB 5.2 ΔΑΠΑΝΕΣ : 

Να βάλουμε το Helptext :

Κατά την εισαγωγή των δαπανών ο δικαιούχος θα πρέπει να μεριμνά ώστε να τηρούνται οι ποσοτικοί και ποσοστιαίοι περιορισμοί όπως αυτοί έχουν οριστεί στην πρόσκληση. 
Αυξομείωση ανά κατηγορία δαπάνης καθώς και προσθήκη νέας κατηγορίας δαπάνης, μη προβλεπόμενη κατά την υποβολή της πρότασης απαιτεί υποβολή ξεχωριστού αιτήματος τροποποίησης.

**Comment by JimLavrentzos** [comment]
Εχει υλοποιηθεί για όλα τα ΠΕΠ στην Staging

**Comment by sadamaki** [comment]
ok.
