### ISSUE TITLE
ΑΙΤΗΜΑ ΕΛΕΓΧΟΥ-TAB 5.3 ΠΑΡΑΣΤΑΤΙΚΑ

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#164]
TAB 5.3 ΠΑΡΑΣΤΑΤΙΚΑ-
Να βάλουμε helptext για το πώς θα τσεκάρει το check box ΧΡΗΣΗ .

 «Για να μπορέσετε να  συνδέσετε δαπάνη με  παραστατικό αγοράς,  κάνετε κλικ στο check box ΧΡΗΣΗ, στον πίνακα "Σύνδεση Δαπάνης στο Παραστατικό Αγορών"
".

**Comment by JimLavrentzos** [comment]
Εχει υλοποιηθεί για όλα τα ΠΕΠ στην Staging

**Comment by sadamaki** [comment]
ok
