### ISSUE TITLE
ΑΙΤΗΜΑ ΕΛΕΓΧΟΥ-TAB 5.5 ΠΛΗΡΩΜΕΣ

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#165]
TAB 5.5 ΠΛΗΡΩΜΕΣ -
Να βάλουμε helptext για το πώς θα τσεκάρει το check box ΧΡΗΣΗ .

«Για να μπορέσετε να συνδέσετε παραστατικό πληρωμής με παραστατικό αγοράς , κάνετε κλικ στο check box ΧΡΗΣΗ, στον πίνακα "Σύνδεση Παραστατικών Αγορών στο Παραστατικό Πληρωμής"

**Comment by JimLavrentzos** [comment]
Έχει υλοποιηθεί για όλα τα ΠΕΠ στην Staging

**Comment by sadamaki** [comment]
ok
