### ISSUE TITLE
αυτοματισμοί στο χρηματοδοτικό σχήμα

### ISSUE THREAD

**Issue by apanagio** [mou-gr/regions#17]
Στον πίνακα  ΧΡΗΜΑΤΟΔΟΤΙΚΟ ΣΧΗΜΑ το ποσό της ιδιωτικής συμμετοχής .της  Αιτούμενη Επιχορήγησης  καθώς και του μη επιχορηγούμενου να συμπληρώνονται αυτόματα (να αντλούνται από τον πίνακα δαπανών). Το ποσό στο πεδίο «Μη Επιχορηγούμενος Προϋπολογισμός»  να μην υπολογίζεται και ως ποσοστό επί του συνολικού π/υ

**Comment by apanagio** [comment]
Δεν θα αφήνουμε να συμπληρωθούν μη επιλέξιμες δαπάνες

**Comment by mariaelanet** [comment]
Στον έλεγχο ορθότητας βγάζει σφάλμα 7.3] Το ποσό στο πεδίο "Β. Αιτούμενη Επιχορήγηση" πρέπει να είναι ίσο με το άθροισμα των ποσών δημοσίας δαπάνης που έχουν δηλωθεί στο "7.1 Πίνακα Δαπανών". (110000 €) [7.3] Το ποσό στο πεδίο "Α. Ιδιωτική Συμμετοχή" πρέπει να είναι ίσο με το άθροισμα της ιδιωτικής συμμετοχής που έχει δηλωθεί στο "7.1 Πίνακα Δαπανών". (90000 €)
ενώ έχει δηλωθεί το επιπλέον 5%.
Διόρθωσα το χρηματοδοτικό σύμφωνα με το σφάλμα και εξακολουθεί και χτυπάει
