### ISSUE TITLE
ΔΡΑΣΕΙΣ ΠΕΡΙΦΕΡΕΙΩΝ - ΠΙΝΑΚΑΣ ΔΑΠΑΝΩΝ 7.1

### ISSUE THREAD

**Issue by cbouras** [mou-gr/regions#171]
Για τις δράσεις των περιφερειών στον Πίνακα Δαπανών στο 7.1 για τον ΚΑΔ και τον Τόπο Υλοποίησης να γίνει η ίδια υλοποίηση με τα Leader (όπου γίνεται narrow) η πληροφορία του ΚΑΔ και του Τόπου Υλοποίησης.

**Comment by JimLavrentzos** [comment]
Έχει εφαρμοστεί σε όλα τα καινούργια ΠΕΠ. όπως είχαμε συμφωνήσει τον Αύγουστο, αλλά στα παλιά ΠΕΠ αν εφαρμοστεί, θα χαθεί η πληροφορία που έχει περαστεί στην παραγωγική βάση

**Comment by sadamaki** [comment]
το κλείνω το issue.
