### ISSUE TITLE
ΔΡΑΣΕΙΣ ΠΕΡΙΦΕΡΕΙΩΝ - ΑΙΤΗΣΗ ΕΛΕΓΧΟΥ - ΒΗΜΑ 3.1 ΥΛΟΠΟΙΗΣΗ ΕΠΕΝΔΥΣΗΣ

### ISSUE THREAD

**Issue by cbouras** [mou-gr/regions#172]
Κατά την εισαγωγή δεδομένων στο 3.1. η φόρμα έσκασε και δεν αποθήκευσε

**Comment by cbouras** [comment]
ΚΡΗΡ1-0001200

**Comment by JimLavrentzos** [comment]
Το πρόβλημα έχει διορθωθεί σε όλα τα ΠΕΠ στην Staging
