### ISSUE TITLE
Interreg - Κ.Α.Δ. ΕΠΕΝΔΥΣΗΣ (NACE CODE)

### ISSUE THREAD

**Issue by cbouras** [mou-gr/regions#181]
Η ονομασία στα αγγλικά. 
Για τους ΚΑΔ έχει δοθεί μία λίστα με ΚΑΔ στα Αγγλικά.
[ELIGIBLE NACE CODES.docx](https://github.com/mou-gr/regions/files/2671680/ELIGIBLE.NACE.CODES.docx)

**Comment by sadamaki** [comment]
Xρήστο άρα στο πεδίο επιλογής ΚΑΔ θα υπάρχει μόνο η παραπάνω λίστα να επιλέξει;

**Comment by izirganou** [comment]
Η λίστα με τους ΚΑΔ σε excel σύμφωνα με την Πρόσκληση 
[NACE codes_5thCall_GR-BG.xlsx](https://github.com/mou-gr/regions/files/2787075/NACE.codes_5thCall_GR-BG.xlsx)

**Comment by Aris-93** [comment]
Πρόσθεσα τους ΚΑΔ. Μπορείτε να τους δείτε
