### ISSUE TITLE
Interreg - 1.5. Επιπλέον Πληροφορίες για τον Δικαιούχο

### ISSUE THREAD

**Issue by cbouras** [mou-gr/regions#182]
Είναι στα Ελληνικά και είναι παρουσιάζουν στοιχεία την Επιχείρησης. Να γίνει Not Applicable. Αν αποφασίσει το Interreg να προσθέσει στοιχεία εκεί, το βλέπουμε.

**Comment by Aris-93** [comment]
Επιλύθηκε
