### ISSUE TITLE
BASIC GEOGRAPHIC LOCATION INFORMATION OF ASSISTED PLANTS/FACILITIES (NUTS LAU CLASSIFICATION)

### ISSUE THREAD

**Issue by cbouras** [mou-gr/regions#185]
Δεν εμφανίζει την χώρα και δεν έχει την γεωγραφική αποτύπωση της Βουλγαρίας
Επίσης για τον τόπο υλοποίησης το intereg έχει ζητήσει περιορισμό των επιλογών σε συγκεκριμένες επιλέξιμες περιοχές. Της επισυνάπτω (αν δεν είναι δυνατόν να περιοριστεί δεν πειράζει) ωστόσο πρέπει να προστεθούν οι Βουλγάρικες
[NUTS LAU classification GR.docx](https://github.com/mou-gr/regions/files/2671878/NUTS.LAU.classification.GR.docx)
[NUTS LAU classification BG.docx](https://github.com/mou-gr/regions/files/2671880/NUTS.LAU.classification.BG.docx)

**Comment by cbouras** [comment]
Στην λίστα για το 4.2. αφαιρέστε το fax και το zip code και προσθέσετε country και municipality είτε Ελλάδα είτε Βουλγαρία

**Comment by izirganou** [comment]
Διορθώθηκε  το server error, αλλά όταν χώρα Βουλγαρία ζητάει στον έλεγχο ορθότητας : [4.2 - Subscription 3]  Υou have not completed the mandatory field: 'Municipality', 
δες IN1GB-0001230]

**Comment by izirganou** [comment]
επιλύθηκε
