### ISSUE TITLE
Interreg - ΤΗΡΗΣΗ ΕΘΝΙΚΩΝ ΚΑΙ ΕΝΩΣΙΑΚΩΝ ΚΑΝΟΝΩΝ

### ISSUE THREAD

**Issue by cbouras** [mou-gr/regions#186]
Τα drop down να έχουν επιλογές YES/NO/NOT APPLICABLE

**Comment by Aris-93** [comment]
Επιλύθηκε

**Comment by Aris-93** [comment]
Επιλύθηκε

**Comment by sadamaki** [comment]
Άρη, ποια αλλαγή έγινε ακριβώς εκτός από το να υπάρχουν επιλογές YES/NO/NOT APPLICABLE.
Δεν εντόπισα κάτι.

**Comment by sadamaki** [comment]
Xρήστο θεωρώ πως τα πεδία του πίνακα δεν συνάδουν με τα αντίστοιχα πεδία του ίδιου πίνακα που υπάρχει στα ΠΕΠ.
Ο πίνακας που έχει φτιαχθεί στο Interreg είναι αυτός του ΕΠΑΝΕΚ

Φαίνεται να λείπουν τα 2 παρακάτω πε΄δια στο Interreg και πρέπει να μπουν : 
1.Ο δικαιούχος δεσμεύεται ότι το επιχειρηματικό σχέδιο περιλαμβάνει σαφείς και συγκεκριμένες δεσμεύσεις ως προς την τήρηση των εθνικών και ενωσιακών κανόνων περί δημοσιότητας και πληροφόρησης
2. Ο δικαιούχος δεσμεύεται να τηρήσει τους εθνικούς και ενωσιακούς κανόνες που αφορούν τις κρατικές ενισχύσεις κατά το στάδιο της πρόσκλησης, της απόφασης ένταξης και πιθανών τροποποιήσεων αυτής;

**Comment by sadamaki** [comment]
όπως μας το επιβεβαι΄βσει η ΕΥΚΕ
