### ISSUE TITLE
Interreg - INVESTMENT PLAN FINANCES - Επιλέξιμες Δαπάνες

### ISSUE THREAD

**Issue by cbouras** [mou-gr/regions#188]
[ELIGIBLE EXPENSE CATEGORIES.docx](https://github.com/mou-gr/regions/files/2672000/ELIGIBLE.EXPENSE.CATEGORIES.docx)

Επισυνάπτεται η λίστα κατηγοριών δαπανών.

**Comment by Aris-93** [comment]
Προστέθηκαν οι δαπάνες

**Comment by sadamaki** [comment]
1. να διορθωθούν οι υποκατηγορίες δαπανών που είναι λάθος : 

4.5  σε :   Subscription fees for IT service such as «Software as a Service», «Cloud Computing», etc.
5.3 σε :  Travel and lodging expenses of staff who participates in the fair/exhibition/ business forum. 
5.9 σε :  Business meeting expenses and associated hospitality expenses

 2. να διορθωθεί το server error που χτυπάει στην καρτέλα 7 σε κωδικούς εργων :
IN1GB-00012230 και  IN1GB-00012231

**Comment by Aris-93** [comment]
Επιλύθηκε
