### ISSUE TITLE
Interreg - INVESTMENT PLAN FINANCES

### ISSUE THREAD

**Issue by cbouras** [mou-gr/regions#189]
Το πεδίο State Aid δεν χρειάζεται διότι αφορά μόνο έναν κανονισμό. Αφαιρείται.
Τα πεδία Investment Location και Nace Code έρχονται προσυμπληρωμένα από τις αντίστοιχες επιλογές:
1.4 ΚΑΔ Δικαιούχου
και 4.2 Τόπος Υλοποίησης

**Comment by sadamaki** [comment]
Το πεδίο State Aid, γιατί να αφαιρεθεί; όταν έχουμε έναν Κανονισμό στα ΠΕΠ ΣΤΟ ΠΕΔΊΟ "καθεστώς ενίσχυσης" (State Aid)  βάζουμε λιστα με το καθεστώς ή τα καθεστώτα ενίσχυσης, και όταν έχουμε 1 καθεστώς ενίσχυσης (όπως τώρα το 65%) στο πεδίο "εντασης ενίσχυσης"  (Aid Intensity (%) φέρνουμε πάντα κλειδωμένο με το ένα και μοναδικό ποσοστό που υπάρχει.

**Comment by sadamaki** [comment]
Αν ακολουθήσουμε το απλοποιημένο των ΠΕΠ λειτουργεί όπως παραπάνω.

**Comment by sadamaki** [comment]
Για το ΚΑΔ και Τόπο, το έχουμε ήδη αναθέσει προς υλοποίηση στους τεχνικούς.

**Comment by izirganou** [comment]
να μπουν οι εξής κανόνες με έλεγχο ορθότητας :
-Οι δαπάνες της κατηγορίας 3 (ήτοι 3.1,3.2, 3.3, 3.4, 3.5, 3.6), πρέπει να είναι μέχρι και το 15% του επιλέξιμου π/υ (με υποχρεωτικό έλεγχο ορθότητας).
-	Η ΚΔ «6.3 Expenses for services associated with the implementation and monitoring of the investment plan», πρέπει να είναι το ανώτατο μέχρι και 20.000 ευρώ (με υποχρεωτικό έλεγχο ορθότητας).

**Comment by izirganou** [comment]
ειχε υλοποιηθεί αλλά χαλασε ο έλεγχος 
-Οι δαπάνες της κατηγορίας 3 (ήτοι 3.1,3.2, 3.3, 3.4, 3.5, 3.6), πρέπει να είναι μέχρι και το 15% του επιλέξιμου π/υ (με υποχρεωτικό έλεγχο ορθότητας).

**Comment by izirganou** [comment]
Αφαιρούμε εντελώς τον έλεγχο ορθότητας για τις υποκατηγορίες της δαπάνης 3, με ανώτατο ποσοστό 15%.
απάντηση από υπηρεσία  interreg Α.Λ. σε mail 05/03/2019
"Σε αυτήν την περίπτωση, είναι προτιμητέο να καταργήσουμε τον έλεγχο ορθότητας και να το ελέγχουμε εμείς κατά τη φάση της αξιολόγησης. "
