### ISSUE TITLE
Interreg - Indicators

### ISSUE THREAD

**Issue by cbouras** [mou-gr/regions#190]
Θα αντικατασταθούν οι δείκτες που υπάρχουν στα ελληνικά με τους κάτωθι
CO01 - Productive investment: number of enterprises receiving support
CO02 Productive investment: Number of enterprises Receiving grants
CO08 Productive investment: Employment increase in supported enterprises

**Comment by sadamaki** [comment]
To έχουμε ήδη αναθέσει με asana.

**Comment by Aris-93** [comment]
Πόσους δείκτες τελικά θα χρειαστούμε ?

**Comment by sadamaki** [comment]
Στην Πρόσκληση υπάρχουν οι προαναφερόμενοι 3, όπως επειδή τα στελέχη του Interreg έστειλαν μόνο 1 στις προδιαγραφές τους θα το επιβεβαιώσουμε ξανά και θα σε ενημερώσουμε για τον αριθμό.
