### ISSUE TITLE
INTERREG-7.4 Indicators

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#191]
-Να γίνουν required τα πεδία των δεικτών που θα έχει ο πίνακας 
(κατά τη συμπλήρωση του)

**Comment by sadamaki** [comment]
όταν ανοίγει το παράθυρο να καταχωρήσει τιμή στο πεδίο "CO02 - Productive investment: number of enterprises receiving suppor" , δεν πρέπει να του επιτρέπουμε να κλείσει το παράθυρο με κενό το πεδίο.

Με άλλα λόγια να γίνει  required το πεδίο.

**Comment by sadamaki** [comment]
Να είναι υποχρεωτικά μέσα στον πίνακα όλα τα πεδία που αφορούν δείκτες εκροών

**Comment by Aris-93** [comment]
Το έκανα υποχρεωτικό. Ενημερώστε με για το πόσους δείκτες θα βάλουμε και ποιους
