### ISSUE TITLE
Interreg - 7.1 INVESTMENT PLAN FINANCES

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#192]
Στον πίνακα  7.1 θεωρώ πως πρέπει να γίνουν τα εξής (όπως πρώτα συναινέσει η ΕΥΚΕ ) :

-Το πεδίο "Expense Type" μιας που έχει τη λίστα με τις υποκατηγορίες δαπανών πρέπει να έχει λεκτικό "Eligible Expense Categories"

-Στο πεδίο "State Aid" να υπάρχει η εξής επιλογή: EU 1407/2013 (de minimis) 65%

-΄Το πεδίο "Amount(Excluding VAT) IN €¨, μήπως καλύτερα να γινότανε "Eligible Amount in € Excluding VAT)"??

-Θεωρώ πως πρέπει να μπει επιπλέον και το πεδίο που αφορά "μη επιλέξιμο ποσό" (όπως στα ΠΕΠ) :Iineligible Amount in € excluding VAT)

-To πεδίο "VAT IN" στα ΠΕΠ είναι ανοιχτό για να το συμπληρώσει ο χρήστης με το χέρι (προαιρετικό). Εδώ φαίνεται να το υπολογίζει αυτόματα το ΠΣΚΕ και μάλιστα λάθος. 

-Στο πεδίο "Public Financing" υπολογίζεται λάθος η τιμή του (θα πρέπει να υπολογίζεται πολλαπλασιάζοντας το ποσοστό ενίσχυσης (65%) με το ποσό που έχει δηλώσει στο πεδίο Amount(Excluding VAT) IN )
-Θεωρώ πως στο τέλος του πίνακα πρέπει να μπει επιπλέον και το πεδίο "Justification" και να είναι required

**Comment by sadamaki** [comment]
To Πεδίο  "Aid Intensity (%)"  θα  πρέπει να είναι πάντα κλειδωμένο με τιμή 65% -(επιβεβαίωση πρώτα από ΕΥΚΕ)

**Comment by cbouras** [comment]
Συμφωνώ με τα παραπάνω. Ομως το πεδίο State Aid δεν χρειάζεται διότι αφορά μόνο deminimis. Να κρυφτεί.
Τα πεδία ποσών δεν λειτουργούν σωστά.
Πρέπει να διορθωθούν.

**Comment by sadamaki** [comment]
Μετά από επιβεβαίωση ΕΥΚΕ 

-Το πεδίο "Expense Type" μιας που έχει τη λίστα με τις υποκατηγορίες δαπανών πρέπει να έχει λεκτικό "Eligible Expense Categories"

-Να μην υπάρχει, να βγει το πεδίο state aid

-΄Το πεδίο "Amount(Excluding VAT) IN €¨, να γινότανε "Eligible Amount in € Excluding VAT)"

-Nα μπει επιπλέον και το πεδίο που αφορά "μη επιλέξιμο ποσό" (όπως στα ΠΕΠ) :Iineligible Amount in € excluding VAT)

-To πεδίο "VAT IN" πρέπει να είναι  ανοιχτό για να το συμπληρώσει ο χρήστης με το χέρι (προαιρετικό). Εδώ φαίνεται να το υπολογίζει αυτόματα το ΠΣΚΕ και μάλιστα λάθος.

-To Πεδίο "Aid Intensity (%)" θα πρέπει να είναι πάντα κλειδωμένο με τιμή 65% -(επιβεβαίωση πρώτα από ΕΥΚΕ)

-Στο πεδίο "Public Financing" υπολογίζεται λάθος η τιμή του (θα πρέπει να υπολογίζεται πολλαπλασιάζοντας το ποσοστό ενίσχυσης (65%) με το ποσό που έχει δηλώσει στο πεδίο Amount(Excluding VAT) IN )
-Θεωρώ πως στο τέλος του πίνακα πρέπει να μπει επιπλέον και το πεδίο "Justification" και να είναι required
