### ISSUE TITLE
Interreg - 7.1 INVESTMENT PLAN FINANCES

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#193]
7.1  Tab 7.1- Στους πίνακες που ανοίγουν όταν πατάς  ΠΡΟΕΠΙΣΚΟΠΗΣΗ, να μεταφραστούν οι τίτλοι στης στήλες αυτών

**Comment by sadamaki** [comment]
Κατηγορίες Δαπανών
Κατηγορία Δαπάνης-Συνολικό- Μη Επιλέξιμο- Επιλέξιμο- Δημόσια Δαπάνη -Eπιλέξιμος / Σύνολο Επιλέξιμου (%)


Κατηγορίες Δαπανών - Ομαδοποίηση


Ομάδα Κατηγοριών Δαπάνης - Συνολικό - Μη Επιλέξιμο - Επιλέξιμο- Δημόσια Δαπάνη - Επιλέξιμος / Σύνολο Επιλέξιμου (%)

**Comment by cbouras** [comment]
Η προεπισκόπηση των δαπανών αν μπορεί να γίνει στα αγγλικά θα βοηθήσει. Αν δεν γίνεται θα πρέπει να το προβλέψουμε το εγχειρίδιο χρηστών

**Comment by izirganou** [comment]
υλοποιήθηκε από τον Γιάννη
