### ISSUE TITLE
Στο searchforms της υποβολής να φαίνεται το όνομα της Πρόσκλησης στη στήλη ΕΠ / άξονας

### ISSUE THREAD

**Issue by apanagio** [mou-gr/regions#2]

**Comment by jpsarakis** [comment]
ΟΚ έγινε.
Αρχεία που πρέπει να μπούνε στην εγγραφή του wizard:

C:\inetpub\wwwroot\AuditorCIS_13\SAMIS\GDE01\GDE01_DataActons.xml **<<< NEW**
C:\inetpub\wwwroot\AuditorCIS_13\SAMIS\GDE01\Lists\GDE01_ActivitiesList.aspx **<<< NEW**

C:\inetpub\wwwroot\AuditorCIS_13\WebConfiguration\DataUtilsDefinitions.config: GDE01_DataActions
C:\inetpub\wwwroot\AuditorCIS_13\Resources\files\menu-config.xml: **samis_submission_gde01.list?callid=204**
C:\inetpub\wwwroot\AuditorCIS_13\Resources\files\searchforms-config.xml: **samis_submission_gde01**
