### ISSUE TITLE
INTERREG 1.3 BENEFICIARY ENTERPRISE PARTNER/SHAREHOLDER INFORMATION (IF ANY)

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#201]
1.3 ΣΤΟΙΧΕΙΑ ΕΤΑΙΡΩΝ ΜΕΤΟΧΩΝ-Υποχρεωτικά πεδία κατά το άνοιγμα- 
 το πεδίο Type Of Entity,  να γίνει required (και όχι προσυμπληρωμένο by default όπως είναι τώρα)

**Comment by Aris-93** [comment]
Επιλύθηκε
