### ISSUE TITLE
INTERREG -2.  [ΣΤΟΙΧΕΙΑ ΕΤΑΙΡΩΝ/ ΜΕΤΟΧΩΝ/ ΣΥΝΔΕΔΕΜΕΝΩΝ]	

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#204]
TAB 2.1 και 2.2 θεωρώ πρέπει να γίνουν NOT APPLICABLE ( όπως πρώτα συναινέσει η ΕΥΚΕ)

**Comment by Aris-93** [comment]
Επιλύθηκε
