### ISSUE TITLE
INTERREG -4.1 INVESTMENT PLAN IDENTITY

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#206]
-To πεδίο Type Of Investment, να μην έρχεται συμπληρωμένο με τιμή (όπως κάνει τώρα) αλλά κατά το άνοιγμα του πίνακα να είναι ασυμπλήρωτο
-Να γίνουν required όλα τα πεδία του πίνακα.

**Comment by Aris-93** [comment]
Επιλύθηκε
