### ISSUE TITLE
INTERREG 4.2 BASIC GEOGRAPHIC LOCATION INFORMATION OF ASSISTED PLANTS/FACILITIES 

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#208]
-Στο πεδίο MUNICIPALITY θα βάλουμε και λίστα για Βουλγαρία;

-Να είναι required όλα τα πεδία του πίνακα 4.2

**Comment by sadamaki** [comment]
Επιβεβαίωση απο ΕΥΚΕ

**Comment by cbouras** [comment]
Θα πρέπει να προστεθεί η Χώρα (Country) και να μπουν και οι περιοχές στην Βουλγαρία.

**Comment by sadamaki** [comment]
Φαίνεται να έχει προστεθεί μόνο το πεδίο "Implementation Location Index" το οποίο φαίνεται να έχει λίστα Βουλγάρικων περιοχών.

Τα πεδία του πίνακα (πριν την προσθήκη του πεδίου Implementation Location Index" ), είχαμε ζητήσει να είναι υποχρεωτικά. Τι θα γίνει όμως τώρα που του ζητάμε να συμπληρώσει και τα 2 πεδία που αφορούν "municipality" Και ""Implementation Location Index" ? ? 
ΈΤσι όπως έχει διαμορφωθεί ο πίνακας, ένα πεδίο πρέπει να συμπληρώνει, ανάλογα με το αν είναι στην Ελλάδα ή αν είναι στη Βουλγαρία.

**Comment by sadamaki** [comment]
Στο νέο πεδίο country η επιλογή τιμής ΕΛΛΑΔΑ να γίνει Greece.
