### ISSUE TITLE
INTERREG  6.1 INVESTMENT PLAN (ΦΥΣΙΚΟ ΑΝΤΙΚΕΙΜΕΝΟ) -

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#210]
6.1 INVESTMENT PLAN (ΦΥΣΙΚΟ ΑΝΤΙΚΕΙΜΕΝΟ) -

Να βγει η λέξη ΩΦΕΛΗ,  από το πεδίο "ANTICIPATED BENEFITS FROM THE INVESTMENT ΩΦΕΛΗ"

**Comment by Aris-93** [comment]
Επιλύθηκε
