### ISSUE TITLE
INTERREG 7.3  FINANCIAL SCHEME-

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#214]
7.3 ΧΡΗΜΑΤΟΔΟΤΙΚΟ ΣΧΗΜΑ  FINANCIAL SCHEME-

-Στο πεδίο "Eligible Investment budget (A+B)" , να μπει αρίθμηση C.

**Comment by sadamaki** [comment]
7.3 ΧΡΗΜΑΤΟΔΟΤΙΚΟ ΣΧΗΜΑ  FINANCIAL SCHEME 

-Στο πεδίο ". Ineligible budget )(Private Financing) " να μπει αρίθμηση D

- Στο πεδίο "Investment Grand Total" στην παρένθεση του,  πρέπει να του να βάλουμε (C+D) (και όχι αυτό που υπάρχει τώρα)

**Comment by cbouras** [comment]
Δεν υπολογίζει σωστά.

**Comment by sadamaki** [comment]
7.3 ΧΡΗΜΑΤΟΔΟΤΙΚΟ ΣΧΗΜΑ FINANCIAL SCHEME-

-Στο πεδίο "Eligible Investment budget (A+B)" , να μπει αρίθμηση C.
--Στο πεδίο ". Ineligible budget )(Private Financing) " να μπει αρίθμηση D
-Στο πεδίο "Investment Grand Total" στην παρένθεση του, πρέπει να του να βάλουμε (C+D) (και όχι αυτό που υπάρχει τώρα)

**Comment by sadamaki** [comment]
Δεν υπολογίζει σωστά.
