### ISSUE TITLE
INTERREG 8.1 ΑΠΟΔΟΧΗ ΌΡΩΝ ΚΑΙ ΠΡΟΫΠΟΘΕΣΕΩΝ

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#215]
όπως συναινέσει πρώτα η ΕΥΚΕ : 

-  O τίτλος του πίνακα Nα μεταφραστεί σε ACCEPT TERMS AND CONDITIONS
 
- Το πεδίο του πίνακα " Αποδέχομαι όλους τους παραπάνω όρους" , να μεταφραστεί σε 
Accept all terms and conditions , και να έχει μόνο την επιλογή τιμής  : ACCEPT

- Nα μεταφραστεί το κείμενο του πίνακα  (βλέπε comment)
The “Terms and Conditions” are:
1.    The Beneficiary accepts that messages sent from the Managing Authority via e-mail, and in particular to the email address stated in the Application Form, shall be considered official notifications and will activate all legal consequences and deadlines.

2.    The application for funding is considered a “Sworn Statement” of article 8 of Legal Act 1599/1986 (Government Gazette A75) with regards to the data contained in it. Therefore, the information contained in the application should be identical to the information contained in the relevant supporting documents. Any inaccurate or false information provided in the application can be subject to the penalties foreseen in Legal Act 1599/1986. Beneficiaries are responsible for the complete and correct completion of their online application for funding. No correction or modification or addition of any missing data to the applications, albeit supplementary data or clarifications specifically requested by the MA/JS, will be allowed after the electronic submission of the application.

**Comment by cbouras** [comment]
Συμφωνώ

**Comment by sadamaki** [comment]
O τίτλος του πίνακα Nα μεταφραστεί σε ACCEPT TERMS AND CONDITIONS

Το πεδίο του πίνακα " Αποδέχομαι όλους τους παραπάνω όρους" , να μεταφραστεί σε
Accept all terms and conditions , και να έχει μόνο την επιλογή τιμής : ACCEPT

Nα μεταφραστεί το κείμενο του πίνακα (βλέπε comment)
The “Terms and Conditions” are:

The Beneficiary accepts that messages sent from the Managing Authority via e-mail, and in particular to the email address stated in the Application Form, shall be considered official notifications and will activate all legal consequences and deadlines.

The application for funding is considered a “Sworn Statement” of article 8 of Legal Act 1599/1986 (Government Gazette A75) with regards to the data contained in it. Therefore, the information contained in the application should be identical to the information contained in the relevant supporting documents. Any inaccurate or false information provided in the application can be subject to the penalties foreseen in Legal Act 1599/1986. Beneficiaries are responsible for the complete and correct completion of their online application for funding. No correction or modification or addition of any missing data to the applications, albeit supplementary data or clarifications specifically requested by the MA/JS, will be allowed after the electronic submission of the application.
