### ISSUE TITLE
INTERREG- 9.  ΣΥΝΝΗΜΕΝΑ ΑΡΧΕΙΑ

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#216]
όπως συναινέσει πρώτα η ΕΥΚΕ

9.-O τίτλος του πίνακα " Επισυναπτόμενα Έγγραφα"  να αλλαχθεί σε :

 LIST OF ATTACHMENTS TO THE APPLICATION

**Comment by cbouras** [comment]
Εφόσον είναι εφικτό. Να το αλλάξουμε. Προτείνω το "ATTACHMENT DOCUMENTS"

**Comment by sadamaki** [comment]
Εφόσον είναι εφικτό.9.-O τίτλος του πίνακα " Επισυναπτόμενα Έγγραφα" να αλλαχθεί σε "ATTACHMENT DOCUMENTS"

**Comment by sadamaki** [comment]
Κάτι νεώτερο; Αλλιώς αν δεν είναι εφικτό να γίνουν ας απαντηθεί να ολοκληρώνουμε τα issue.
Εφόσον είναι εφικτό.9.-O τίτλος του πίνακα " Επισυναπτόμενα Έγγραφα" να αλλαχθεί σε "ATTACHMENT DOCUMENTS"

**Comment by izirganou** [comment]
υλοποιήθηκε από τον Γιάννη
