### ISSUE TITLE
INTERREG- 9. ΣΥΝΝΗΜΕΝΑ ΑΡΧΕΙΑ 

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#217]
“όπως συναινέσει πρώτα η ΕΥΚΕ :
Να αλλαχθεί το λεκτικό των πεδίων :
-Φορέας”να γίνει Beneficiary
-“Κατηγορία Εγγράφου”, να γίνει category of document
και να έχει επιλογή από τιμή  : 1 document
-“Στοιχεία – Περιγραφή Εγγράφου”, να γίνει description
“-Παρατηρήσεις” να γίνει comments
-“Αρχείο”, να γίνει file name.
-Το ΕΠΙΛΕΞΤΕ ΑΡΧΕΙΟ να γίνει : "press  to select the document"

Τα ΕΝΗΜΕΡΩΣΗ και ΑΚΥΡΩΣΗ να αλλαχθούν στην αγγλική (θεωρώ όπως τα έχετε στον κώδικα)

**Comment by cbouras** [comment]
Συμφωνώ.

**Comment by sadamaki** [comment]
όπως γίνουν οι αλλαγές: 
Να αλλαχθεί το λεκτικό των πεδίων :
-Φορέας”να γίνει Beneficiary
-“Κατηγορία Εγγράφου”, να γίνει category of document
και να έχει επιλογή από τιμή : 1 document
-“Στοιχεία – Περιγραφή Εγγράφου”, να γίνει description
“-Παρατηρήσεις” να γίνει comments
-“Αρχείο”, να γίνει file name.
-Το ΕΠΙΛΕΞΤΕ ΑΡΧΕΙΟ να γίνει : "press to select the document"

Τα ΕΝΗΜΕΡΩΣΗ και ΑΚΥΡΩΣΗ να αλλαχθούν στην αγγλική (θεωρώ όπως τα έχετε στον κώδικα)

**Comment by cbouras** [comment]
Αν δεν μπορεί να γίνει στα αγγλικά ή αν δεν μπορεί να προστεθεί το αγγλικό λεκτικό δίπλα να μας το πει η ομάδα των προγραμματιστών ώστε να προβλεφθεί στο εγχειρίδιο.

**Comment by cbouras** [comment]
όταν αποθηκεύσεις ένα έγγραφο στο refresh εξαφανίζεται το 9.1. Instructions.

**Comment by sadamaki** [comment]
Στην από 14.02.2019  συνάντηση που είχαμε απαιτήθηκε να μεταφραστεί ή να είναι δίγλωσσο το tab, πρέπει να γίνουν τα εξής 

Στο μπλέ φόντο το τίτλος "Επισυναπτόμενα Έγγραφα" να γίνει : Attachments

(και στο Εκτυπωτικό να εκτυπώνεται με την αγγλική).
Στον πίνακα που ανοίγει κατά την προσθήκη εγγράφων να γίνουν τα εξής :
9. Να αλλαχθεί το λεκτικό των πεδίων :
-Φορέας”=να γίνει =Beneficiary
-“Κατηγορία Εγγράφου”, να γίνει =category of document
και να έχει επιλογή από τιμή : =1 document
-“Στοιχεία – Περιγραφή Εγγράφου”, να γίνει =Description
“-Παρατηρήσεις” να γίνει =Comments
-“Αρχείο”, να γίνει =Document
-Το ΕΠΙΛΕΞΤΕ ΑΡΧΕΙΟ να γίνει : =Press to select the Document"

Τα ΕΝΗΜΕΡΩΣΗ και ΑΚΥΡΩΣΗ να αλλαχθούν στην αγγλική (θεωρώ όπως τα έχετε στον κώδικα)

**Comment by izirganou** [comment]
υλοποιήθηκε από τον Γιάννη
