### ISSUE TITLE
INTERREG 9. ΟΔΗΓΙΕΣ -ΣΥΝΝΗΜΕΝΑ ΑΡΧΕΙΑ

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#218]
όπως συναινέσει η ΕΥΚΕ πρώτα 

-Να βγάλουμε το κείμενο στις Οδηγίες που υπάρχει αυτή τη στιγμή, και στη θέση του να βάλουμε το εξής (που να λέει στον δικαιούχο ότι θα πρέπει να επισυνάψει μόνο 2 αρχεία) :+1: 

Υou are required to attach only 2 documents:
·        Annex I-2 in pdf form
·        Budget Table in excel form

**Comment by Aris-93** [comment]
Επιλύθηκε

**Comment by sadamaki** [comment]
Xρήστο είσαι σύμφωνος με το παραπάνω;

**Comment by cbouras** [comment]
Είμαι ΟΚ. Να σημειώσω ότι το τελικό accept θα το δώσει το interreg. Εμείς να έχουμε όσο το δυνατόν πιο πλήρεις.
