### ISSUE TITLE
INTERREG 10.  ΟΡΙΣΤΙΚΟΠΟΙΗΣΗ ΚΑΙ ΥΠΟΒΟΛΗ ΤΗΣ ΕΠΕΝΔΥΤΙΚΗΣ ΠΡΟΤΑΣΗΣ

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#219]
Eπιβεβαίωση πρώτα απο ΕΥΚΕ, μιας που ίσως χρειαστεί να διορθώσει τα αγγλικά μου  : 

Στο 10, υπάρχουν οι παρακάτω φράσεις που καθοδηγούν το χρήστη, όπως αλλαχθούν σε : 

-Για να ολοκληρωθεί η ενέργεια πρέπει να πατήσετε το κουμπί της υποβολής.  = 
 (Υου should proceed to Submit in order to finalize the Application. Applications completed but “not submitted” will remain in the system as “drafts and will not be evaluated/assessed. Also, applications which have not been submitted electronically will not be evaluated/assessed. )

-Παρακαλώ, πατήστε στο κουμπί Έλεγχος Ορθότητας Δήλωσης, για να επιβεβαιωθεί η ορθότητα των στοιχείων της υποβολής.=(Select “Έλεγχος Ορθότητας” (verification of correctness) in order to check for mistakes, omissions and other control messages)

-Προσοχή μετά την υποβολή της πρότασης δεν έχετε την δυνατότητα για περαιτέρω επεξεργασία των στοιχείων. (Attention: Corrections are not allowed after the “submission” of the application.)

-Εκτυπώσεις (Exports)

-Εκτύπωση Υποβολής (.pdf) Πατήστε τον παραπάνω σύνδεσμο για να εκτυπώσετε =
(Submission export report (pdf). Click the hyperlink above to print)

-Το κουμπί ΕΛΕΓΧΟΣ ΟΡΘΌΤΗΤΑΣ να γίνει =Verification of correctness

-Το κουμπί YΠΟΒΟΛΗ  να γίνει =Submission ή καλύτερα Submit?

-Ο έλεγχος των δεδομένων της δήλωσης υπέδειξε τα παρακάτω σφάλματα - ελλείψεις.Διορθώστε τα σημεία που παρουσιάζονται στον παρακάτω πίνακα και προσπαθήστε ξανά.
(The control messages are of the following form-Please complete  all required information in the electronic system, check for mistakes and omissions  and try again).

-Δεν υπήρξαν σφάλματα κατά τον έλεγχο, μπορείτε να προχωρήσετε σε Υποβολή =
(Νo errors were identified; you may proceed to Submit)

**Comment by cbouras** [comment]
Σταυρούλα. Κάνουμε τις αλλαγές όπως τις αναφέρεις. Οι αγγλικές διατυπώσεις όπως έχω αναφέρει και σε mail δεν είναι δική μας δουλειά. Αν υπάρχουν εκφραστικά λάθη θα τα διορθώσει το interreg.

**Comment by sadamaki** [comment]
όπως γίνουν οι προαναφερόμενες αλλαγές.

**Comment by sadamaki** [comment]
Στο ΤΑΒ 10 ",ΟΡΙΣΤΙΚΟΠΟΙΗΣΗ ΚΑΙ ΥΠΟΒΟΛΗ ΤΗΣ ΕΠΕΝΔΥΤΙΚΗΣ ΠΡΟΤΑΣΗΣ"  υπάρχουν οι παρακάτω φράσεις που καθοδηγούν το χρήστη, όπως έχουν και την αγγλική τους διατύπωση μέσα στην παρένθεση:

-Για να ολοκληρωθεί η ενέργεια πρέπει να πατήσετε το κουμπί της υποβολής.  = 
 (Υου should proceed to Submit in order to finalize the Application. Applications completed but “not submitted” will remain in the system as “drafts and will not be evaluated/assessed. Also, applications which have not been submitted electronically will not be evaluated/assessed. )

-Παρακαλώ, πατήστε στο κουμπί Έλεγχος Ορθότητας Δήλωσης, για να επιβεβαιωθεί η ορθότητα των στοιχείων της υποβολής.=(Select “Έλεγχος Ορθότητας” (verification of correctness) in order to check for mistakes, omissions and other control messages)

-Προσοχή μετά την υποβολή της πρότασης δεν έχετε την δυνατότητα για περαιτέρω επεξεργασία των στοιχείων=(Attention: Corrections are not allowed after the “submission” of the application.)

-Εκτυπώσεις= (Exports)

-Εκτύπωση Υποβολής (.pdf) Πατήστε τον παραπάνω σύνδεσμο για να εκτυπώσετε =
(Submission export report (pdf). Click the hyperlink above to print)

-Το κουμπί ΕΛΕΓΧΟΣ ΟΡΘΌΤΗΤΑΣ να έχει και τη διατύπωση  =Verification of correctness

-Το κουμπί YΠΟΒΟΛΗ να έχει και τη διατύπωση=Submit

-Ο έλεγχος των δεδομένων της δήλωσης υπέδειξε τα παρακάτω σφάλματα - ελλείψεις.Διορθώστε τα σημεία που παρουσιάζονται στον παρακάτω πίνακα και προσπαθήστε ξανά.=
(The control messages are of the following form-Please complete all required information in the electronic system, check for mistakes and omissions and try again).

-Δεν υπήρξαν σφάλματα κατά τον έλεγχο, μπορείτε να προχωρήσετε σε Υποβολή =
(Νo errors were identified; you may proceed to Submit)

**Comment by galanosel** [comment]
Δεν υπάρχει δυνατότητα μετάφραση των buttons και των αρχικών μηνυμάτων της οθόνης

Τα μηνύματα που παράγονται απο τον έλέγχο ορθότητας έχουν μεταφραστεί

**Comment by sadamaki** [comment]
Στη συνάντηση που είχαμε με το interreg, είπαμε μήπως γίνεται να παραμείνουν ως έχουν τα λεκτικά στην ελληνική, όμως να βάλουμε σε παρένθεση δίπλα από κάθε φράση την αντίστοιχη αγγλική ΄΄οπως αναφέρω παραπάνω. 
Είναι σημαντικό διότι θα μπουν και Βούλγαροι.

**Comment by sadamaki** [comment]
Στη συνάντηση που είχαμε με το interreg, είπαμε τα περιφερειακά μηνύματα, να έχουν και την ελληνική και την αγγλική διατύπωση :

Στο ΤΑΒ 10 ",ΟΡΙΣΤΙΚΟΠΟΙΗΣΗ ΚΑΙ ΥΠΟΒΟΛΗ ΤΗΣ ΕΠΕΝΔΥΤΙΚΗΣ ΠΡΟΤΑΣΗΣ" υπάρχουν οι παρακάτω φράσεις,  να γίνουν και στην αγγλική τους διατύπωση με slash:

-Για να ολοκληρωθεί η ενέργεια πρέπει να πατήσετε το κουμπί της υποβολής. /Υου should proceed to Submit in order to finalize the Application. Applications completed but “not submitted” will remain in the system as “drafts and will not be evaluated/assessed. Also, applications which have not been submitted electronically will not be evaluated/assessed. 

-Παρακαλώ, πατήστε στο κουμπί Έλεγχος Ορθότητας Δήλωσης, για να επιβεβαιωθεί η ορθότητα των στοιχείων της υποβολής./Select “Έλεγχος Ορθότητας” (verification of correctness) in order to check for mistakes, omissions and other control messages.

-Προσοχή μετά την υποβολή της πρότασης δεν έχετε την δυνατότητα για περαιτέρω επεξεργασία των στοιχείων/Attention: Corrections are not allowed after the “submission” of the application.)

-Εκτυπώσεις/Export Report

-Εκτύπωση Υποβολής (.pdf) Πατήστε τον παραπάνω σύνδεσμο για να εκτυπώσετε /Submission export report (pdf). Click the hyperlink above to print)

-Το κουμπί ΕΛΕΓΧΟΣ ΟΡΘΌΤΗΤΑΣ να γίνει  =ΕΛΕΓΧΟΣ ΟΡΘΌΤΗΤΑΣ/Verification of correctness

-Το κουμπί YΠΟΒΟΛΗ να γίνει =YΠΟΒΟΛΗ/Submit

-Ο έλεγχος των δεδομένων της δήλωσης υπέδειξε τα παρακάτω σφάλματα - ελλείψεις.Διορθώστε τα σημεία που παρουσιάζονται στον παρακάτω πίνακα και προσπαθήστε ξανά./The control messages are of the following form-Please complete all required information in the electronic system, check for mistakes and omissions and try again.

-Δεν υπήρξαν σφάλματα κατά τον έλεγχο, μπορείτε να προχωρήσετε σε Υποβολή/Νo errors were identified; you may proceed to Submit.

**Comment by izirganou** [comment]
υλοποιήθηκε από τον Γιάννη
