### ISSUE TITLE
ΕΠΙΧΕΙΡΟΥΜΕ ΕΞΩ : ΓΕΝΙΚΟ

### ISSUE THREAD

**Issue by psakellis56** [mou-gr/regions#22]
Καρτέλα 1.1: να καταργηθεί η δυνατότητα υποβολής αίτησης από ΥΠΟ ΣΥΣΤΑΣΗ επιχειρήσεις

**Comment by apanagio** [comment]
Θα υλοποιηθεί

**Comment by galanosel** [comment]
Υλοποιήθηκε παρακαλώ ελέγξτε staging

**Comment by psakellis56** [comment]
Καταργήθηκε το ΥΠΟ ΣΥΣΤΑΣΗ αλλά μπήκε άλλο στη θέση του.
Στη Δράση υποβάλλουν πρόταση μόνο υφιστάμενες επιχειρήσεις, άρα χρειάζεται να υπάρχει μόνο μία επιλογή

**Comment by galanosel** [comment]
Υλοποιήθηκε και θα ανέβει στην staging

**Comment by psakellis56** [comment]
είμαστε ΟΚ!
