### ISSUE TITLE
Κοινωνία Κληρονόμων και ΝΠΔΔ

### ISSUE THREAD

**Issue by psakellis56** [mou-gr/regions#23]
Καρτέλα 1.1: Κοινωνία Κληρονόμων και ΝΠΔΔ δεν είναι επιλέξιμες νομικές μορφές για τη Δράση

**Comment by apanagio** [comment]
Θα υλοποιηθεί

**Comment by galanosel** [comment]
Υλοποιήθηκε και θα ανέβει στην staging

**Comment by psakellis56** [comment]
είμαστε ΟΚ!
