### ISSUE TITLE
νέα ΓΕΝΙΚΗ καρτέλα με τα γενικά Στοιχεία της Πρόσκλησης

### ISSUE THREAD

**Issue by psakellis56** [mou-gr/regions#24]
Να δημιουργηθεί νέα ΓΕΝΙΚΗ καρτέλα με τα γενικά Στοιχεία της Πρόσκλησης (Σημείο 1.1 ΕΝΤΥΠΟΥ ΥΠΟΒΟΛΗΣ)

**Comment by apanagio** [comment]
Είναι δύσκολο να γίνει. 
Είναι απαραίτητη τέτοια καρτέλα εφόσον ο επενδυτής δεν θα πρέπει να συμπληρώσει κάτι εκει;

**Comment by psakellis56** [comment]
Με τον πίνακα αυτόν ουσιαστικά δένουμε την Δράση με τους στόχους/άξονες/προτεραιότητες του ΕΠΑΝΕΚ.
Από εκεί θα τραβήξουμε μετά στοιχεία για να συμπληρώνονται τα ΓΕΝΙΚΑ πεδία του ΟΠΣ. Επίσης, είναι χρήσιμο πεδίο "ταυτότητας" σε όλες τις εκτυπώσεις.
Μπορεί να δημιουργηθεί κάτι απλό που απλώς να φαίνεται σε όλες τις εκτυπώσεις ?

**Comment by cbouras** [comment]
Τα στοιχεία της πρόσκλησης δεν έχει νόημα να είναι στην υποβολή του δικαιούχου. Θα εμφανίζονται όμως στην Γνωμοδοτική Ενταξης όπου ΓΙΑ ΟΛΕΣ ΤΙΣ ΠΡΑΞΕΙΣ η Διαχειριστική Αρχή/ ΕΦΔ θα πρέπει να συμπληρώσει όλα τα κωδικοποιημένα στοιχεία του ΟΠΣ ΕΣΠΑ ώστε να μπορούν να εισαχθούν τα ΤΔΠ . Να σημειώσω ότι τα περισσότερα θα έρχονται έτοιμα και προσυμπληρωμένα. Για κάποια όμως θα πρέπει να επενερήσει η ΔΑ/ΕΦΔ και να τα ΕΞΕΙΔΙΚΕΎΣΕΙ με βάσει το κάθε έργο.

**Comment by psakellis56** [comment]
Οκ, το issue κλείνει στο στάδιο της υποβολής και θα επανεξεταστεί παρακάτω.
Η γενική απαίτηση θα είναι : στο Τεχνικό Παράρτημα Ένταξης (εκτυπωτικό) να εμφανίζονται τα γενικά Στοιχεία της Πρόσκλησης (Σημείο 1.1 ΕΝΤΥΠΟΥ ΥΠΟΒΟΛΗΣ)
