### ISSUE TITLE
'ΕΛΕΓΧΟΣ -TAB 1.1 ΒΑΣΙΚΑ ΣΤΟΙΧΕΙΑ ΕΠΕΝΔΥΣΗΣ 

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#247]
Στο tab 1.1 to πεδίο "Ποσό Απομειώσεων Εγγυητικών Επιστολών", φαίνεται να είναι 0,00 ενώ υπάρχει ποσό απομείωσης εγγυητικής στο Tab 6.3 στο σχετικό πεδίο.
Θα πρέπει να ενημερώνεται το πεδίο "ποσό απομειώσεων εγγυητικών επιστολών" με την σωστή τιμή/

**Comment by galanosel** [comment]
Διορθώθηκε παρακαλώ ελέγξτε στην staging
