### ISSUE TITLE
έλεγχος για πλήρη διαχειριστική χρήση 12μ

### ISSUE THREAD

**Issue by psakellis56** [mou-gr/regions#25]
ΚΑΡΤΕΛΑ 1.1: Να γίνεται έλεγχος της ημερομηνίας σύστασης μιας επιχείρησης με την ημερομηνία υποβολής αίτησης. Να μην επιτρέπεται η υποβολή αν αυτή είναι <12 μηνών

**Comment by apanagio** [comment]
Δεν μπορεί να γίνει. Μπορεί να ελέγχεται στην αξιολόγηση.
Μπορούμε να βάλουμε ενημερωτικό banner άμα θέλετε

**Comment by psakellis56** [comment]
Στην αξιολόγηση θα ελέγχεται έτσι και αλλιώς. Απλά θα ήταν καλύτερα αν μας "προστάτευε" και το σύστημα.
Το banner είναι καλή λύση

**Comment by YIANIS66** [comment]
Να μπει ενημερωτικό banner με την επισήμανση : Η επιχείρηση απαιτείται να έχει συσταθεί τουλάχιστον δώδεκα (12) μήνες πριν την ημερομηνία υποβολής της αίτησης χρηματοδότησης.

**Comment by galanosel** [comment]
Υλοποιήθηκε παρακάλω ελέγξετε το στην staging

**Comment by psakellis56** [comment]
Είμαστε ΟΚ!
 Το issue κλείνει
