### ISSUE TITLE
INTERREG - 1.4 Κ.Α.Δ. ΕΠΕΝΔΥΣΗΣ (NACE CODE)

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#251]
To πεδίο "Nace Code Activation Code" να γίνει  "Nace Code Activation Date"

(Interface Και εκτυπωτικό)

**Comment by Aris-93** [comment]
Επιλύθηκε

**Comment by sadamaki** [comment]
Nαι μια χαρά, απλά στη staging σήμερα δεν ανοίγει το εκτυπωτικό Υποβολής Interreg , μάλλον είναι θέμα server?

Line 41:         Response.OutputStream.Write(serverResponse, 0, serverResponse.Length); Line 42:         Response.End(); Line 43:     } Line 44:
--
