### ISSUE TITLE
Aίτημα Ελέγχου και Έλεγχος (ΠΕΠ)- 5.6 Παραδοτέα

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#252]
Έγινε μια αλλαγή στο πεδίο "Ενότητες Εργασίας" του πίνακα 3.6 Παραδοτέα.
Στον τρόπου που εμφανίζεται η λίστα μέσα στο εν λόγω πεδίο (ΣΤΕΡ)

Το ίδιο πρέπει να αντιγράψεις όπου υπάρχει πίνακας Παραδοτέα.

**Comment by JimLavrentzos** [comment]
Fixed for all PEP on Staging
