### ISSUE TITLE
Εκτυπωτικό-Παρατηρήσεις στο εξώφυλλο 

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#256]
Να μεταφραστεί το εξώφυλλο στα αγγλικά :

Ελληνική Δημοκρατία= Hellenic Democracy
Υπουργείο Οικονομίας και Ανάπτυξης (ΥΠΟΙΚΑ)= Hellenic Ministry of Economy and Development
Φόρμα Υποβολής= Application Submission 
Kωδικός Πράξης=Project Code 
Δικαιούχος= Beneficiary
Mε τη συγχρηματοδότησης της Ελλάδας και της ΕΕ=?? Θα το αφήσουμε να υπάρχει μεταφρασμένο ή να το βγάλουμε?

**Comment by sadamaki** [comment]
όπου έχει αποτυπωθεί θεωρείται λάθος η μετάφραση να τη διορθώσουμε (διότι ενώ έχουν σταλεί παρατηρήσεις να μεταφραστούν δεν μας έχουν στείλει τη μετάφραση)

**Comment by apanagio** [comment]
διορθώθηκε
