### ISSUE TITLE
Εκτυπωτικό-Παρατηρήσεις σε πεδία εκτυπωμένων πινάκων 2. LEGAL REPRESENTATIVE INFORMATION

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#258]
Φαίνεται να εκτυπώνεται 2 φορές το πεδίο με τίτλο ΕΠΩΝΥΜΟ (ενώ υπάρχει ήδη το πεδίο last name). 

2. LEGAL REPRESENTATIVE INFORMATION (representative information), να ΜΗΝ εκτυπώνεται το πεδίο ΕΠΩΝΥΜΟ (2 φορές)

**Comment by apanagio** [comment]
Το κοιτάμε θα προσπαθήσουμε να το διορθώσουμε

**Comment by izirganou** [comment]
δεν έχει υλοποιηθεί, το έστειλαν ξανά ως παρατηρηση

**Comment by izirganou** [comment]
Σελ.3 - 1.2 Legal Representative Information: Διαγραφή του πεδίου «Επώνυμο», είναι στα ελληνικά και περιττό, καθώς υπάρχει πιο κάτω το σωστό πεδίο στα αγγλικά “Last Name”. Εμφανίζεται δύο (2) φορές, μία φορά για κάθε εταίριο.

**Comment by apanagio** [comment]
υπάρχει διπλοεγγραφή στο διαχειριστικό

**Comment by sadamaki** [comment]
Δημήτρη επειδή λείπει ο Άρης στον πίνακα 1.2Legal Representative Information  του εκτυπωτικού εμφανίζεται  το πεδίο ΕΠΩΝΥΜΟ, να το σβήσουμε . (γιατί θέλουμε Να εμφανίζεται μόνο το πεδίο LAST NAME)

**Comment by sadamaki** [comment]
done staging και παραγωγικό

**Comment by JimLavrentzos** [comment]
Fixed
