### ISSUE TITLE
Εκτυπωτικό-Παρατηρήσεις σε πεδία  3. BENEFICIARY ENTERPRISE PARTNER/SHAREHOLDER INFORMATION (IF ANY)

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#259]
3. BENEFICIARY ENTERPRISE PARTNER/SHAREHOLDER INFORMATION
(IF ANY)

Foreign Shareholder/Partner= οι απαντήσεις του εν λόγω πεδίου να είναι στην αγγλική (yes/no)
Country =να είναι στην αγγλική GREECE (μάλλον το πρόβλημα ξεκινά από την επιλογή για ΕΛΛΑΔΑ να έχει GREECE )

**Comment by apanagio** [comment]
διορθώθηκε

**Comment by sadamaki** [comment]
Δεν εντόπισα καμία διόρθωση.
Πήγαινε στην IN1GB-0001234

-Foreign Shareholder/Partner=Εξακολουθεί και εκτυπώνει στην ελληνική την απάντηση του πεδίου (ενώ θα έπρεπε να εκτυπώνει είτε YES είτε ΝΟ, ανάλογα με το αν το είχε τικάρει ή όχι στο interface)

Country=εκτυπώνει το ΕΛΛΑΔΑ ενώ όταν έχει χώρα ΕΛΛΑΔΑ θα έπρεπε να εκτυπώνει GREECE (το πρόβλημα ξεκινάει απο το interface όπου στη λίστα με τις χώρες η ΕΛΛΑΔΑ δεν φαίνεται να έχει μεταφραστεί σε GREECE)

**Comment by izirganou** [comment]
δεν έχει υλοποιηθεί, το έστειλαν ξανά ως παρατηρηση

**Comment by izirganou** [comment]
Στο πεδίο «Foreign Shareholder/Partner» η απάντηση ΝΑΙ/ΟΧΙ εμφανίζεται στα ελληνικά. Να γίνει αγγλική YES/NO. Στο σύστημα η επιλογή ΝΑΙ γίνεται με ‘τικ’ ενός κουτιού. 
Στο πεδίο «Country» η απάντηση ΕΛΛΑΔΑ είναι στα ελληνικά. Να γίνει GREECE.

**Comment by sadamaki** [comment]
1.3 BENEFICIARY ENTERPRISE PARTNER/SHAREHOLDER INFORMATION
(IF ANY) :
Στο πεδίο «Country», στην εμφανιζόμενη λίστα η επιλογή "ΕΛΛΑΔΑ", να γίνει GREECE.

**Comment by sadamaki** [comment]
Το παραπάνω δεν το υλοποιήσαμε διότι αν γίνει, θα φαίνεται GREEECE σε όλες τις δράσεις. πχ Γεωργοί, ΠΕΠ κλπ.
Το θέλουμε; 
Μια άλλη λύση είναι να φτιάξει κάποιος μια 2η λίστα χωρών με το GREECE. Και αυτή η 2η λίστα χωρών να χρησιμοποιείται για το INTEREG.

**Comment by izirganou** [comment]
Επηρεάζει κι άλλες δράσεις.
