### ISSUE TITLE
ΑΦΜ - διασταυρώσεις

### ISSUE THREAD

**Issue by psakellis56** [mou-gr/regions#26]
ΚΑΡΤΕΛΕΣ 1.2 και 1.3: δέχεται να καταχωριστεί ΦΥΣΙΚΟ Πρόσωπο ως νόμιμος εκπρόσωπος/υπεύθυνος έργου ή/και μέτοχος που να έχει το ίδιο ΑΦΜ με το νομικό πρόσωπο με νομική μορφή ΑΕ ή δύο διαφορετικά φυσικά πρόσωπα να καταχωριστούν με το ίδιο ΑΦΜ. Γενικώς, εκτός του έλεγχου εγκυρότητας ΑΦΜ, δεν γίνεται κανένας άλλος έλεγχος/διασταύρωση στα ΑΦΜ που δηλώνονται. Άρα μπορεί το ίδιο ΑΦΜ να δηλωθεί σε πολλούς ανθρώπους και νομικές μορφές

**Comment by apanagio** [comment]
Τι έλεγχοι θέλετε να γίνονται;

**Comment by psakellis56** [comment]
Θα ήταν χρήσιμο να μην έχουμε dublicates στις καταχωρήσεις (πχ το ίδιο ΑΦΜ σε δύο εταίρους, το ίδιο ΑΦΜ στο δικαιούχο και στην συνεργαζόμενη/συνδεδεμένη εταιρία κλπ).

Βέβαια δεν ξέρω αν μπορούν να μπουν έλεγχοι απαγορευτικοί. Ίσως να ελέγχεται αν ένα ΑΦΜ (αριθμητικό πεδίο) έχει καταχωριστεί κάπου παραπάνω από μία φορές και να βγαίνει στο τέλος ένα warning και όχι απαγόρευση υποβολής (γιατί πχ στις ατομικές πρέπει να επιτρέπεται). 

 να γίνει.

**Comment by cbouras** [comment]
Το να ανεβάσουμε ελέγχους για ΑΦΜ για διάφορους συνδυασμούς περιπτώσεων κάνει πολύπλοκο το σύστημα. Ο δικαιούχος υποβάλλει μία δήλωση και είναι υποχρεωμένος να προσέχει τα data που βάζει. Το σύστημα είναι υποχρεωμένο να κάνει λογικούς ελεγχους σε σχέση με την Πρόσκληση

**Comment by psakellis56** [comment]
Οκ παιδιά, προφανώς είναι σωστό αυτό που γράφει ο Χρήστος, εμείς απλά το είδαμε και το είπαμε. Προφανώς έχει απασχολήσει και στο παρελθόν και έχει ξεπεραστεί.
Αν θέλετε, μπορεί το issue να κλείσει

**Comment by YIANIS66** [comment]
Να κλείσει το issue αφού είναι πολύπλοκη διαδικασία.
