### ISSUE TITLE
Εκτυπωτικό-Παρατηρήσεις σε πεδία 9.INVESTMENT PLAN FINANCES

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#260]
9.INVESTMENT PLAN FINANCES
Φαίνεται να εκτυπώνεται 2 φορές το πεδίο ΤΕΚΜΗΡΙΩΣΗ και DOCUMENTATION
ας εκτυπώνεται μόνο το DOCUMENTATION

**Comment by apanagio** [comment]
Θα το δούμε και αυτό, αλλά όχι με μεγάλη προτεραιότητα

**Comment by izirganou** [comment]
δεν έχει υλοποιηθεί, το έστειλαν ξανά ως παρατηρηση

**Comment by izirganou** [comment]
8.	Σελ.5 & 6 - 7.1 Table of Expenditures: Διαγραφή του πεδίου «Τεκμηρίωση», είναι στα ελληνικά και δε χρειάζεται γιατί υπάρχει το ίδιο πεδίο από κάτω στα αγγλικά “Documentation”. Εμφανίζεται δύο (2) φορές το πεδίο, μία για κάθε εταίρο.

**Comment by apanagio** [comment]
υπάρχει διπλοεγγραφή στο διαχειριστικό

**Comment by sadamaki** [comment]
Δημήτρη επειδή λείπει ο Άρης στον πίνακα 7.1 του εκτυπωτικού εμφανίζεται 2πλό το πεδίο DOCUMENTATION. Να εμφανίζεται μία φορά (ανά δικαιούχο)

**Comment by sadamaki** [comment]
done staging και παραγωγικό

**Comment by JimLavrentzos** [comment]
Fixed
