### ISSUE TITLE
Εκτυπωτικό-Παρατηρήσεις σε πεδία 10.ΣΥΓΚΕΝΤΡΩΡΙΚΟΣ ΠΙΝΑΚΑΣ ΔΑΠΑΝΩΝ

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#261]
10.ΣΥΓΚΕΝΤΡΩΡΙΚΟΣ ΠΙΝΑΚΑΣ ΔΑΠΑΝΩΝ

Να γίνει στην αγγλική ο τίτλος του πίνακα - και οι τίτλοι των στηλών =
ΣΥΓΚΕΝΤΡΩΤΙΚΟΣ ΠΙΝΑΚΑΣ ΔΑΠΑΝΩΝ=TOTAL INVESTMENT PLAN FINANCES
Κατηγορία Δαπάνης =Expenditure Category
Συνολικό Κόστος(€) =Total Amount(€) 
Μη Επιλέξιμο Κόστος(€)=Non eligible amount (€) 
Επιλέξιμο Κόστος(€) =Eligible amount(€) 
Δημόσια Δαπάνη (€)=Public Expenditure (€)

Συνολικά= Totals

**Comment by apanagio** [comment]
διορθώθηκε

**Comment by sadamaki** [comment]
Expense Category 
Total Budget(€) 
Non Eligible Budget(€)
 Eligible Budget(€) 
Public Expenditure(€)
