### ISSUE TITLE
Εκτυπωτικό-Παρατηρήσεις σε πεδία 12. INDICATORS

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#262]
12. INDICATORS

Ο τίτλος στη στήλη ΤΙΜΗ να γίνει στην αγγλική- Amount

**Comment by apanagio** [comment]
Και αυτή η υλοποίηση θα πάρει χρόνο.

Προτείνω να μείνει όπως έχει προς το παρόν

**Comment by izirganou** [comment]
υλοποιήθηκε από τον Γιάννη
