### ISSUE TITLE
Εκτυπωτικό-Παρατηρήσεις σε πεδία 14. ΣΥΝΗΜΜΈΝΑ ΑΡΧΕΙΑ

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#263]
14. ΣΥΝΗΜΜΕΝΑ ΑΡΧΕΙΑ

Ο τίτλος του πίνακα στην εκτύπωση να γίνει =ATTACHED DOCUMENTS

Και =
Ο τίτλος στη στήλη Αρχείο= να γίνει Document
Παρομοίως το  Μέγεθος =να γίνει Size
Παρομοίως το Περιγραφή να γίνει= Document Decription
 Παρομοίως το Σχόλια να γίνει Comments

**Comment by apanagio** [comment]
δεν είναι εύκολη η υλοποίηση, 
το σημειώνω και θα το διορθώσουμε, αλλά θα πάρει χρόνο

**Comment by izirganou** [comment]
δεν έχει υλοποιηθεί, το έστειλαν ξανά ως παρατηρηση

**Comment by apanagio** [comment]
done
