### ISSUE TITLE
Εκτυπωτικό-Παρατηρήσεις σε πεδία στην τελευταία σελίδα 

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#264]
Στην αγγλική τα =

Ημερομηνία= Date
Yπογραφή= Signature
Σφραγίδα= Stamp

**Comment by apanagio** [comment]
υλοποιήθηκε

**Comment by sadamaki** [comment]
Σκάει το εκτυπωτικό γενικά =
Line 118:        response.OutputStream.Write(serverResponse, 0, serverResponse.Length); Line 119:        response.End(); Line 120:    }
--

**Comment by apanagio** [comment]
fixed
