### ISSUE TITLE
INTERREG - 6.1. INVESTMENT PLAN IDENTITY

### ISSUE THREAD

**Issue by cbouras** [mou-gr/regions#265]
1. Τα labels από κεφαλαία να γίνουν μικρά.
2. Στο σημείο 2. να αφαιρεθεί το citizen's. Δεν βγάζει νόημα. Θα γίνει Summary of the proposed investment plan for publicity.

**Comment by izirganou** [comment]
δεν έχει υλοποιηθεί ακόμα

**Comment by Aris-93** [comment]
υλοποιήθηκε

**Comment by izirganou** [comment]
ok
