### ISSUE TITLE
INTERREG-Link "Information" κάτω απο το μενού "Interreg"

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#268]
Πατώντας πάνω στο link "Information" , πρέπει να μεταφραστούν όπως =

Στο μπλε φόντο πάνω-πάνω το "Πληροφορίες" να γίνει "Information"

Το "Επιλέξτε τον σύνδεσμο για να αποθηκεύσετε το αρχείο" να γίνει =Choose link in order to save the file/document

**Comment by izirganou** [comment]
υλοποιήθηκε από τον Γιάννη
