### ISSUE TITLE
ατομική επχση και πλήθος εταίρων

### ISSUE THREAD

**Issue by psakellis56** [mou-gr/regions#27]
ΚΑΡΤΕΛΕΣ 1.2 & 1.3: Στην ατομική επιχείρηση επιτρέπεται να μπουν παραπάνω από ένας εταίροι ενώ αυτό δεν είναι σωστό

**Comment by apanagio** [comment]
Δεν μπορεί να γίνει αυτός ο έλεγχος να ελέγχεται στην αξιολόγηση

**Comment by psakellis56** [comment]
Εμείς το είδαμε και το επισημάναμε. Αφού μας ζητήθηκε το STAGING να τελειώσει σήμερα και αύριο να πάμε παραγωγικά, σίγουρα δεν μπορεί να γίνει
