### ISSUE TITLE
INTERREG -Link "My Submissions"

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#270]
όταν πατάει πάνω στο My Submissions", του εμφανίζεται η μάσκα με τις εγγραφές έργων/προτάσεων.

Τα λεκτικά στις 3 τελευταίες στήλες να γίνουν δίγλωσσα : 

Ημ/νια Οριστικοποίησης= Ημ/νια Οριστικοποίησης/ Submission Date

Xρήστης Οριστικοποίησης= Xρήστης Οριστικοποίησης/Submission User

Κατάσταση = Κατάσταση/Status

Mέσα στη στήλη "Κατάσταση" όταν έχει "Σχέδιο" να εμφανίζεται δίγλωσσο = Σχέδιο/Draft

Mέσα στη στήλη "Κατάσταση" όταν έχει "Hλεκτρονική Υποβολή " να εμφανίζεται δίγλωσσο = Hλεκτρονική Υποβολή/Submitted

**Comment by izirganou** [comment]
υλοποιήθηκε από τον Γιάννη
