### ISSUE TITLE
INTERREG -Link "My Submissions"

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#271]
Έχοντας πατήσει στο my submissions, δεξιά στην οθόνη εκεί που είναι το link "Eπεξεργασία" 

να γίνει δίγλωσσο :+1: 
"Επεξεργασία/Application Edit"

(σημείωση =αυτή τη στιγμή αν μπεις με χρήστη επενδυτή δεν βλέπει το "ακύρωση" άρα δεν στέλνω απαίτηση να γίνει δίγλωσσο και το "ακύρωση" και όλα όσα ανοίγουν στον πίνακα για να αποθηκεύσει την ακύρωση)

**Comment by izirganou** [comment]
υλοποιήθηκε από τον Γιάννη
