### ISSUE TITLE
INTERREG-Link "my submissions"

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#272]
Έχοντας πατήσει στο my submissions, δεξιά στην οθόνη κάτω από το link "Eπεξεργασία/Application Edit" να βάλουμε τo link ¨Ακύρωση" και για χρήστη επενδυτή, την οποία δυνατότητα "ακύρωσης" θα την έχει/βλέπει μόνο όταν είναι ακόμη σε κατάσταση "σχέδιο/draft" η πρόταση

να γίνει δίγλωσσο 
"¨Ακύρωση/Delete"

(σημείωση και όλα όσα ανοίγουν στον πίνακα της Ακύρωσης, να είναι δίγλωσσα.)

**Comment by izirganou** [comment]
H επιλογή Ακύρωση υπήρχε, τώρα δεν υπάρχει ...
