### ISSUE TITLE
INTERREG-Link "My Submissions"

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#273]
Πατώντας στο "My Submissions", κάτω από το Link "επεξεργασία" υπάρχουν τα 

Εκτυπώσεις.
και
Εκτυπώσεις Αποφάσεων 
Να γίνουν :

To "Εκτυπώσεις" να γίνει =."Εκτυπώσεις/ExportFile"

Το "Εκτυπώσεις Αποφάσεων" να γίνει = "Εκτυπώσεις Αποφάσεων"/Publicity Approved Grants 

To "Εκτύπωση Υποβολής (.pdf)" να γίνει
" "Εκτύπωση Υποβολής (.pdf)"/Submitted Application ExportFile(.pdf)"

**Comment by izirganou** [comment]
υλοποιήθηκε από τον Γιάννη
