### ISSUE TITLE
εκτυπωτικό -λογότυπο-interreg

### ISSUE THREAD

**Issue by izirganou** [mou-gr/regions#276]
Συνημμένα το λογότυπο του Υπουργείου στην αγγλική γλώσσα για να χρησιμοποιηθεί στη φόρμα υποβολής.
![logo_ypian_neo_en_big](https://user-images.githubusercontent.com/46712519/53552964-3afdbb00-3b45-11e9-979b-01a40a406ec3.jpg)

**Comment by apanagio** [comment]
Θα διορθωθεί (Τρίτη 5/3)

**Comment by apanagio** [comment]
done

**Comment by izirganou** [comment]
Στην παραγωγική το εκτυπωτικό δεν εμφανίζει το λογότυπο 
Στη staging είναι οκ.

**Comment by izirganou** [comment]
διορθώθηκε
