### ISSUE TITLE
εκτυπωτικό 4.2 -interreg

### ISSUE THREAD

**Issue by izirganou** [mou-gr/regions#277]
όταν χώρα Ελλάδα εμφανίζει και  municipality (Boulgaria)
όταν  χώρα Βουλγαρία εμφανίζει και municipality ( Greece)
το φέρνει από την καρτέλα καταχώρησης

**Comment by apanagio** [comment]
Θα διορθωθεί αργότερα

**Comment by izirganou** [comment]
ΕΥΚΕ – ΜΟΔ. Δεν θεωρούμε ότι επηρεάζει την λειτουργικότητα δεδομένου του γεγονότος ότι το κάθε ένα από αυτά τα πεδία γεμίζει με την σωστή τιμή

**Comment by izirganou** [comment]
7.	Σελ.4 - 4.2 Location of Investment: Στα στοιχεία του Έλληνα εταίρου, εμφανίζεται στο εκτυπωτικό και το πεδίο Municipality (Bulgaria). Αντίστοιχα και στα στοιχεία του Βούλγαρου εταίρου, εμφανίζεται στο εκτυπωτικό το πεδίο Municipality (Greece). Είναι μεν κενά τα αντίστοιχα έξτρα πεδία, ωστόσο, γιατί να εμφανίζονται;

**Comment by izirganou** [comment]
Δεν επηρεάζει τη λειτουργικότητα του συστήματος.
