### ISSUE TITLE
εκτυπωτικό -interreg εξώφυλλο

### ISSUE THREAD

**Issue by izirganou** [mou-gr/regions#278]
Αντικατάσταση disclaimer «Co-Funded by Greece and the EU» με το ακόλουθο:  The Cooperation Programme Interreg V-A "Greece-Bulgaria 2014-2020" is co-funded by the European Union (ERDF) and National Funds of Greece and Bulgaria.

**Comment by apanagio** [comment]
Θα μπει το κείμενο: Co-funded by the European Union (ERDF) and National Funds που είναι ανεξάρτητο από τη δράση
