### ISSUE TITLE
Εταίροι με συνολικό ποσοστό > 100%

### ISSUE THREAD

**Issue by psakellis56** [mou-gr/regions#28]
ΚΑΡΤΕΛΑ 1.3: Δέχεται να καταχωρηθούν περισσότερα Φυσικά Πρόσωπα ως εταίροι και το συνολικό ποσοστό να είναι > 100%

**Comment by galanosel** [comment]
Λύθηκε το πρόβλημα και έχει ενημερωθεί σχετικά η staging
