### ISSUE TITLE
εκτυπωτικό -υποσέλιδο - interreg

### ISSUE THREAD

**Issue by izirganou** [mou-gr/regions#280]

**Comment by izirganou** [comment]
9.	Υποσέλιδο: Η ημέρα στην ημερομηνία υποβολής είναι στα ελληνικά «Πεμ». 
ας φύγει εντελώς το ίδιο και η ώρα 
η ώρα εμφανίζεται όπου υπάρχει και ημερομηνία

**Comment by apanagio** [comment]
fixed, 
θέλει αναβάθμιση
Η ώρα καλό είναι να μείνει γιατί χρειάζεται όταν προκύπτει θέμα με εκπρόθεσμες κτλ
