### ISSUE TITLE
ΑΙΤΗΜΑ ΤΡΟΠΟΠΟΙΗΣΗΣ -8.1 

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#283]
8.1 
8.1 Πίνακας read only -Αρχικές Τιμές= δεν φαίνεται να φέρνει όλα τα πεδία που έχει ο σχετικός πίνακας για τα ΠΕΠ, για τα ΚΑΛΟ, για ΚΜΕ2 και ΚΜΕ3

8.1 Πίνακας επεξεργάσιμος -ΝΕΕΣ ΤΙΜΕΣ = ΝΑ γίνει το σχετικό customize ανά Πρόσκληση.

**Comment by JimLavrentzos** [comment]
Fixed

**Comment by sadamaki** [comment]
Επιπλέον για  στον πίνακα 8.1 ΒΑΣΕΙ ΙΣΧΥΟΝΤΟΣ ΤΕΧΝΙΚΟΥ ΠΑΡΑΡΤΗΜΑΤΟΣ, ΣΕ ορισμένα ΠΕΠ, δεν φαίνεται να έχει γίνει customize (μιας που αν δείτε φαίνεται να λείπουν το  πεδίο  ΚΑΔ ).Ας δείτε ξανά σε ποια υπάρχει αστοχία.

**Comment by sadamaki** [comment]
ΑΜΘΡ3-0000770: 
ΣΤΟ το Αίτημα Τροποποίησης , ΣΤΟΝ 8.1 ΒΑΣΕΙ ΙΣΧΥΟΝΤΟΣ ΤΕΧΝΙΚΟΥ ΠΑΡΑΡΤΗΜΑΤΟΣ,  θα έπρεπε να φέρνει τιμές στα πεδία  ΚΑΔ και ΤΟΠΟΣ ΥΛΟΠΟΙΗΣΗΣ. (στον από κάτω πίνακα 8.1 ΒΑΣΕΙ ΤΡΟΠΟΠΟΙΗΣΗΣ βλέπω να φέρνει τιμές στο ΚΑΔ και ΤΟΠΟ ΥΛΟΠΟΙΗΣΗΣ). 
Η δαπάνη 1.2 θα έπρεπε στον πίνακα 8.1 ΒΑΣΕΙ ΙΣΧΥΟΝΤΟΣ ΤΕΧΝΙΚΟΥ ΠΑΡΑΡΤΗΜΑΤΟΣ να έχει τιμή 45.000, μιας που για το έργο αυτό υπάρχει τελευταία εγκεκριμένη ΑΞΙΟΛΟΓΗΣΗ ΕΝΣΤΑΣΗΣ με τιμή 45.000).
Στον 8.1 ΒΑΣΕΙ ΤΡΟΠΟΠΟΙΗΣΗΣ η δαπάνη 1.2 έρχεται σωστά με τιμή 45.000. όμως γιατί γενικά ο πίνακας αυτός είναι κιτρινισμένος ? Δεν θα έπρεπε να είναι κιτρινισμένος εφόσον ακόμη δεν έχω μπει μέσα στον πίνακα να κάνω τροποποιήσεις.
Στον 2.3 ΜΕΤΟΧΟΥΣ γιατί ο πίνακας είναι από μόνος του κιτρινισμένος, ενώ δεν έχω μπει ακόμη μέσα να κάνω τροποποιήσεις? (τον μέτοχο τον άλλαξα σε ΝΟΜΙΚΟ ΠΡΟΣΩΠΟ με επωνυμία ΠΑΠΑΓΑΛΟΣ στην Αξιολόγηση Ένστασης)
Θα πρέπει να δείτε ξανά τον τρόπο που κληρονομεί το ΑΙΤΗΜΑ ΤΡΟΠΟΠΟΙΗΣΗΣ.

**Comment by sadamaki** [comment]
Ενώ πχ αν το ΑΙΤΗΜΑ ΤΡΟΠΟΠΟΙΗΣΗΣ ξεκινήσει μετά από εγκεκριμένη ΓΝΩΜΟΔΟΤΙΚΗ ΕΝΤΑΞΗΣ φαίνεται ο πίνακας 8.1 να κληρονομεί σωστά τα data του (και στα δύο σημεία του, δλδ στο "8.1 Αναλυτικός Πίνακας Δαπανών Βάσει Ισχύοντος Τεχνικού Παραρτήματος", και στο "8.2 Αναλυτικός Πίνακας Δαπανών Βάσει Τροποποίησης)
