### ISSUE TITLE
ΑΙΤΗΜΑ ΤΡΟΠΟΠΟΙΗΣΗΣ -10. ΥΠΟΒΕΒΛΗΜΕΝΑ ΣΥΝΗΜΜΕΝΑ ΑΡΧΕΙΑ]	

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#284]
Στο βήμα 10, από όσο είδαμε φαίνεται να φέρνει τα υποβεβλημένα συνημμένα αρχεία που υπάρχουν στο βήμα 11 [ΥΠΟΒΕΒΛΗΜΕΝΑ ΣΥΝΗΜΜΕΝΑ ΑΡΧΕΙΑ] της "Γνωμοδοτικής ΄Ένταξης",
Σωστά? 
Αν όμως μετά τη Γνωμοδοτική Ένταξης έχει γίνει Αξιολόγηση ΄Ένστασης, τότε τα αρχεία που υπάρχουν στο βήμα 13. ΣΥΝΗΜΜΕΝΑ ΑΡΧΕΙΑ ΕΠΙΤΡΟΠΗΣ ΕΝΣΤΑΣΕΩΝ], δεν θα έπρεπε και αυτά να μεταφέρονται στο βήμα 10 του Αιτήματος Τροποποίησης?

ΑΙΤΗΜΑ ΤΡΟΠΟΠΟΊΗΣΗΣ απαίτηση από ΕΥΚΕ : Στο βήμα 10, να έρχεται αν είναι εφικτό ως attached το τελευταίο εκτυπωτικό Τεχνικού Παραρτήματος (ΕΊΤΕ από την Γνωμοδοτική Ενταξης είτε απο την Αξιολόγηση Έντασης αν έχει) , καθώς και το αρχείο I2 που είχε επισυνάψει στην Υποβολή του ο δικαιούχος .

**Comment by JimLavrentzos** [comment]
Νίκο, δες το σε παρακαλώ

**Comment by galanosel** [comment]
Έχει υλοποιηθέι

**Comment by sadamaki** [comment]
Να καταγράψουμε τα τελικά όπως έχει υλοποιηθεί:
-Σβήσαμε από όλα τo tab 10. , που αρχικά είχε τίτλο "υποβεβλημένα συνημμένα αρχεία" ΚΑΙ στη θέση του "φέραμε" ως 10 το -[ΣΥΝΗΜΜΕΝΑ ΑΡΧΕΙΑ ΑΙΤΗΜΑΤΟΣ ΤΡΟΠΟΠΟΙΗΣΗΣ].

Αρα η προαναφερόμενη απαίτηση της ΕΥΚΕ ( να έρχεται αν είναι εφικτό ως attached το τελευταίο εκτυπωτικό Τεχνικού Παραρτήματος (ΕΊΤΕ από την Γνωμοδοτική Ενταξης είτε απο την Αξιολόγηση Έντασης αν έχει) , καθώς και το αρχείο I2 που είχε επισυνάψει στην Υποβολή του ο δικαιούχος .), ΔΕΝ ΘΑ ΥΛΟΠΟΙΗΘΕΙ.
