### ISSUE TITLE
 ΑΙΤΗΜΑ ΤΡΟΠΟΠΟΙΗΣΗΣ -11. [ΣΥΝΗΜΜΕΝΑ ΑΡΧΕΙΑ ΑΙΤΗΜΑΤΟΣ ΤΡΟΠΟΠΟΙΗΣΗΣ]	

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#285]
11. [ΣΥΝΗΜΜΕΝΑ ΑΡΧΕΙΑ ΑΙΤΗΜΑΤΟΣ ΤΡΟΠΟΠΟΙΗΣΗΣ] : Στο βήμα 11, δεν πρέπει να φέρνει συνημμένα αρχεία ΑΠΟ άλλη ενέργεια (πχ από Γνωμοδοτική Ένταξης που κάνει τώρα), αλλά να είναι κενός για να  κάνει attached τα αρχεία που αφορούν το εκτάστοτε Αίτημα Τροποποίησης.

**Comment by sadamaki** [comment]
Και να κληρονομούνται στην Αξιολόγηση Τροποποίησης λογικά.

**Comment by galanosel** [comment]
Έχει υλοποιηθεί.

Παρακαλώ επιβεβαιώστε και κλείστε το issue

**Comment by sadamaki** [comment]
Έχει υλοποιηθεί στο Αιτημα Τροποποίησης.
όσον αφορά την Αξιολόγηση Τροποποίησης να κληρονομούνται (λογικά) δεν το έχω τεστάρει, μιας που στη staging σήμερα δεν υπάρχει το μενού ΑΞΙΟΛΟΓΗΣΗ ΤΡΟΠΟΠΟΙΗΣΗΣ
