### ISSUE TITLE
ΑΙΤΗΜΑ ΤΡΟΠΟΠΟΙΗΣΗΣ -7.1 ΦΥΣΙΚΟ ΑΝΤΙΚΕΙΜΕΝΟ

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#287]
7.1= να αφαιρεθεί το helptext,  μιας και δεν έχει νόημα- αφού δεν σε αφήνει να προσθέσεις

**Comment by JimLavrentzos** [comment]
Όπως έχει υλοποιηθεί, αν σβηστεί το helptext εδώ στο 7.1 , θα σβηστεί και στην υποβολή στην καρτέλα 6.1

**Comment by sadamaki** [comment]
όχι δεν το θέλουμε να σβηστεί από το αντίστοιχο της Υποβολής, άστο να υπάρχει, ολοκληρώνω το issue.
Δεν θα υλοποιηθεί.
