### ISSUE TITLE
Ορισμός των Επιλέξιμων ΚΑΔ στη Δράση

### ISSUE THREAD

**Issue by psakellis56** [mou-gr/regions#29]
Καρτέλα 1.4: δηλώθηκαν τα επιλέξιμα ΚΑΔ 10.41.23.01, 10.41.23.02, 25.30.13 και 10.41.53.01 (δείτε δημοσιευμένο Παράρτημα) και όλα χτυπάνε στον έλεγχο ορθότητας (καρτέλα 10). Γενικά πρέπει να οριστούν οι Επιλέξιμοι ΚΑΔ της Δράσης

**Comment by apanagio** [comment]
Παρακαλώ στείλτε μια λίστα με τους επιλέξιμες ΚΑΔ.
Η λίστα θα πρέπει να έχει μόνο "," κόμμα ανάμεσα στους διαφορετικους ΚΑΔ

**Comment by psakellis56** [comment]
Δεν ξέρω πως μπορώ να το κάνω αυτό που ζητάς. Τα επιλέξιμα ΚΑΔ είναι ένα XL με περίπου 3000 γραμμές. Εμείς είδαμε ότι ο έλεγχος ορθότητας εμφανίζει μήνυμα λάθους ενώ επιλέξαμε επιλέξιμο ΚΑΔ και το σημειώσαμε.

**Comment by psakellis56** [comment]
Σε συνέχεια τηλεφωνικής επικοινωνίας με το Λευτέρη, σας στείλαμε XL με τα επιλέξιμα ΚΑΔ του ΕΠΙΧΕΙΡΟΥΜΕ ΕΞΩ

**Comment by galanosel** [comment]
Η λίστα με τους επιλέξιμους ΚΑΔ για την δράση ενημερώθηκε. 
Παρακαλώ ελέγξετε στην staging ότι δέχεται μόνο τους επιλέξιμους ΚΑΔ.

**Comment by psakellis56** [comment]
Δοκιμάστηκαν οι μη επιλέξιμοι ΚΑΔ 55.10.10.01 και  85.51.10.02 και το βρήκε ο έλεγχος ορθότητας.
Το issue μπορεί να κλείσει!
