### ISSUE TITLE
ΑΙΤΗΜΑ ΤΡΟΠΟΠΟΙΗΣΗΣ-ΠΕΠ ΜΕΤΑΠΤΩΣΗΣ

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#293]
STAGING ΔΕ2ΔΕ-0001147-

-8.1 μετονομασία πινάκων όπως στα απλοποιημένα ΠΕΠ (όχι ΑΡΧΙΚΕΣ και ΝΕΕΣ ΤΙΜΕΣ που φέρνει τώρα).
-Να γίνει customize στον πίνακα 8.1 ΝΕΕΣ ΤΙΜΕΣ που υπάρχει τώρα (έχει περίεργα πεδία)

**Comment by JimLavrentzos** [comment]
Fixed
