### ISSUE TITLE
ΑΙΤΗΜΑ ΤΡΟΠΟΠΟΙΗΣΗΣ-ΠΕΠ ΜΕΤΑΠΤΩΣΗΣ

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#294]
Μάλλον το πρόβλημα στα ΠΕΠ ΜΕΤΑΠΤΩΣΗΣ ξεκινάει από την ενέργεια της Γνωμοδοτικής ΄'Ενταξης και Γνωμοδοτικής ΄Ένστασης, ενώ πάω και αλλάζω ποσό δαπάνης στον 7.1, θα έπρεπε να σκάνε έλεγχοι ορθότητας για τις αποδεκτές τιμές στον πίνακα 7.3 ΧΡΗΜΑΤΟΔΟΤΙΚΟ ΣΧΗΜΑ (όπως δλδ έχουμε υλοποιήσει σε όλα τα απλοποιημένα ΠΕΠ).
Δεν φαίνεται όμως να γίνεται κανένας έλεγχος, άρα και στις μεταγενέστερες ενέργειες πχ ΑΙΤΗΜΑ ΤΡΟΠΟΠΟΙΗΣΗΣ δεν γίνεται κανένας έλεγχος.
Δεν γνωρίζω πως έχει υλοποιηθεί εξ αρχής στα έργα μετάπτωσης γενικά το θέμα με ελέγχους ορθότητας. Φοβάμαι μην δώσουν στο τέλος μεγαλύτερα ποσά επιχορήγησης.

ΔΕ2ΔΕ-0001147 staging. ΔΔ στον πίνακα 7.1 78.769,09 € , ενώ στον πίνακα 7.3 80.369,10
και με αφήνει να οριστικοποιήσω με διαφορετικές τιμές ΔΔ μεταξύ τους.

ΕΡΩΤΗΜΑ =θΕΩΡΩ ΠΩς πρέπει να επαναφέρουμε τους ελέγχους ορθότητας γενικά παντού στα έργα της μετάπτωσης, για να μπορέσουν να λειτουργήσουν και στο ΑΙΤΗΜΑ ΤΡΟΠΟΠΟΊΗΣΗς;.

**Comment by sadamaki** [comment]
Αλέξη τελικά είπαμε να μην βάλουμε στο ΑΙΤΗΜΑ ΤΡΟΠΟΠΟΙΗΣΗΣ ελέγχους ορθότητας που αφορούν τα budget rules? Σωστά? Παρακαλώ επειδή το issue το είχα στείλει πριν τη συνάντηση μας, να καταλήξουμε στο ότι στα ΠΕΠ ΜΕΤΑΠΤΩΣΗΣ για ΑΙΤΗΜΑ ΤΡΟΠΟΠΟΙΗΣΗΣ δεν θα έχουμε ελέγχους ορθότητας για budget rules.

Θα έχουμε όμως πολύ σωστά τον παρακάτω έλεγχος ορθότητας που βλέπω να υπάρχει στο ΑΙΤΗΜΑ ΤΡΟΠΟΠΟΙΗΣΗΣ, ΌΤΑΝ μετά από τροποποίηση δαπάνης υπερβεί τον ενταγμένο/επιχοηγούμενο : 

"Ο συνολικός Επιλέξιμος Προϋπολογισμός δεν πρέπει να υπερβαίνει τον εγκεκριμένο (85461,37 €)".

**Comment by apanagio** [comment]
Ναι έτσι είναι.
