### ISSUE TITLE
ημερομηνία προσθήκης ΚΑΔ πριν τη σύσταση της επιχείρησης

### ISSUE THREAD

**Issue by psakellis56** [mou-gr/regions#30]
Καρτέλα 1.4: έχει δηλωθεί ΚΑΔ επένδυσης με ημερομηνία προσθήκης προγενέστερη της σύστασης της εταιρείας και έγινε αποδεκτό (πχ στην Ν7ΕΕ-0000105 ο 25.30.13 με ημερομηνία προσθήκης 30/11/2015 ενώ η σύσταση της επιχείρησης είναι 1/1/2016)

**Comment by apanagio** [comment]
Θα υλοποιηθεί

**Comment by galanosel** [comment]
Υλοποιήθηκε και θα ανέβει στην staging

**Comment by psakellis56** [comment]
είμαστε ΟΚ!
