### ISSUE TITLE
Τίτλος και Είδος Επένδυσης

### ISSUE THREAD

**Issue by YIANIS66** [mou-gr/regions#31]
Καρτέλα 4.1: Ο τίτλος Πράξης να προσυμπληρώνεται με την επωνυμία της επιχείρησης (το ίδιο και στα Αγγλικά). Στο είδος επένδυσης να υπάρχει ως ΜΟΝΗ επιλογή η φράση «Συμμετοχή σε έκθεση/εκθέσεις εκτός Ελλάδας» και να καταργηθούν όλες οι άλλες επιλογές.

**Comment by apanagio** [comment]
Η προσυμπλήρωση δεν γίνεται.
οι επιλογές θα περιοριστούν σε αυτές που αναφέρετε

**Comment by psakellis56** [comment]
Είμαστε ΟΚ. 
Την προσυμπλήρωση την προτείναμε για να μην καταχωρείται η επωνυμία σε δύο σημεία (καταχωρείται και στην καρτέλα 1.1).

**Comment by apanagio** [comment]
Επανέρχομαι γιατί μετά από επικοινωνία με τον Χρήστο Μπούρα τέθηκε το εξής: Η κατηγοριοποίηση αυτή προκύπτει από το ΟΠΣ ΕΣΠΑ και πρέπει να γίνει η υποβολή του ΤΔΠ με αυτήν την κατηγοριοποίηση. Μπορούμε να αφαιρέσουμε επιλογές αλλά όχι να προσθέσουμε άλλες. Στην περίπτωση μας η μόνη επιλογή που έχει νόημα είναι το "άλλο" οπότε θα πρότεινα να αφαιρεθεί τελείως το πεδίο και στα ΤΔΠ να μπαίνει παντού η επιλογή "άλλο".

**Comment by psakellis56** [comment]
Ας μείνει η επιλογή "'Αλλο" (λείπει ο τόνος) και βλέπουμε τι θα κάνουμε στα ΤΔΠ.
Ίσως να μπει ένα επεξηγηματικό πεδίο του τύπου : "Για την Δράση ΕΠΙΧΕΙΡΟΥΜΕ ΕΞΩ παρακαλούμε προχωρήστε στην επιλογή "Άλλο"".

**Comment by cbouras** [comment]
Ο Τίτλος πράξης είναι ένα πεδίο απαραίτητο για να μπορούμε να υποβάλλουμε τα ΤΔΠ στο ΟΠΣ ΕΣΠΑ. Η λογική να αντιγράφουμε μόνο την επωνυμία της επιχείρησης δεν είναι αποδεκτή από την ΕΥΣΣΑ. Στα ΤΔΠ μέχρι σήμερα κάναμε μία αλχημεία: Δράση + Επωνυμία της Επιχείρισης. Είναι οριακό αλλά το αποδέχονται. Το σωστό ειναι να το περιγράφει ο Δικαιούχος. Δυνητικά θα μπορούσε να γίνει αυτός ο συνδιασμός και να προσυμπληρώνεται. Αν το θέλει το ΕΠΑΝΕΚ κανένα πρόβλημα.

**Comment by psakellis56** [comment]
Χρήστο, έχω κάνει λάθος. Τα σχόλια αφορούν στο πεδίο "είδος επένδυσης" και όχι στο πεδίο "τίτλος πράξης" που προφανώς είναι σωστό αυτό που λες και έτσι πρέπει να μείνει.
Ίσως να προσθέσουμε την επιλογή στο "είδος επένδυσης" (αφού έτσι και αλλιώς με ΓΑΚ Αρθ 19 πάμε) και να ενημερωθεί και το ΟΠΣ στον πυρήνα του για να τη δέχεται στα ΤΔΠ

**Comment by cbouras** [comment]
Το είδος επένδυσης είναι δυστυχώς πεδίο του ΤΔΠ του ΟΠΣ ΕΣΠΑ. Το έχουμε βάλει για να πάρουμε την  πληροφορία για το πεδίο EIDOS_EPENDYSH του XML του ΤΔΠ που μας επιτρέπει τις εξής τιμές:
	<xsd:restriction base="xsd:integer">
			<xsd:enumeration value="5221"/>
			<xsd:enumeration value="5222"/>
			<xsd:enumeration value="5223"/>
			<xsd:enumeration value="5224"/>
			<xsd:enumeration value="5225"/>
			<xsd:enumeration value="5226"/>
			
			
			
			
			
			

Αυτές τις τιμές θα τις βρείς στο αρχείο: http://www.ops.gr/Ergorama/fileUploads/WebServices/datatypes.zip

Αν πρέπει να προσθέσουμε επιπλέον εξειδικεύσεις θα πρέπει να ενημερωθεί ο πυρήνας του ΟΠΣ με αίτημα σας και μετά να επικαιροποιηθεί το εν λόγω αρχείο.
Άσε Παναγιώτη, μετά τις κρυάδες όλων των άλλων ΤΔΠ και τα δεδομένα που ρίχναμε στο ΟΠΣ είπαμε να πάρουμε τα μέτρα μας....

**Comment by cbouras** [comment]
κάτι ξέφυγε
			<xsd:enumeration value="5221"/>
			<xsd:enumeration value="5222"/>
			<xsd:enumeration value="5223"/>
			<xsd:enumeration value="5224"/>
			<xsd:enumeration value="5225"/>
			<xsd:enumeration value="5226"/>
			<-- Νέα Κατασκευή -->
			<-- Επέκταση -->
			<-- Μετατρ./εκσυγχρ. -->
			<-- Αλλαγή τόπου -->
			<-- Δημ. με εξαγορά -->
			<-- Αλλο -->

**Comment by psakellis56** [comment]
Εντάξει παιδιά, ο Χρήστος μας κάλυψε όλους.
Προτείνουμε : 
είτε να παραμείνει ενεργή μόνο η επιλογή "Άλλο" και να είναι μη ενεργά  όλα τα άλλα 
είτε να μπει ένα επεξηγηματικό πεδίο του τύπου : "Για την Δράση ΕΠΙΧΕΙΡΟΥΜΕ ΕΞΩ παρακαλούμε προχωρήστε στην επιλογή "Άλλο"".

**Comment by galanosel** [comment]
Υλοποιήθηκε παρακαλώ ελέγξετε staging

**Comment by psakellis56** [comment]
Είμαστε ΟΚ. Το issue κλείνει
