### ISSUE TITLE
Διάρκεια υλοποίησης επένδυσης

### ISSUE THREAD

**Issue by YIANIS66** [mou-gr/regions#32]
Καρτέλα 4.1: Διάρκεια σε μήνες να μην δέχεται τιμή > 30

**Comment by apanagio** [comment]
Δεν μπορεί να γίνει. Μπορεί να ελέγχεται στην αξιολόγηση.
Επίσης μπορούμε να βάλουμε ενημερωτικό banner αν θέλετε

**Comment by psakellis56** [comment]
Στην αξιολόγηση θα ελέγχεται έτσι και αλλιώς. Απλά θα ήταν καλύτερα αν μας "προστάτευε" και το σύστημα.
Το banner είναι καλή λύση

**Comment by YIANIS66** [comment]
Να μπει Banner : Η προθεσμία ολοκλήρωσης των έργων δεν μπορεί να υπερβαίνει τους τριάντα (30) μήνες.

**Comment by galanosel** [comment]
Υλοποιήθηκε παρακαλώ ελέγξετε staging

**Comment by psakellis56** [comment]
Είμαστε ΟΚ. Το issue κλείνει
