### ISSUE TITLE
Επεξήγηση αναφορικά με τον τόπο επένδυσης

### ISSUE THREAD

**Issue by YIANIS66** [mou-gr/regions#33]
Καρτέλα 4.2 : Να προστεθεί ως επεξηγηματικό πεδίο η φράση : «Δηλώνεται η Περιφέρεια στην οποία βρίσκεται η έδρα της επιχείρησης ή εκείνη στην οποία είναι εγκατεστημένη η μονάδα/τόπος παραγωγής του προϊόντος που προορίζεται για προβολή».

**Comment by apanagio** [comment]
Θα υλοποιηθεί

**Comment by galanosel** [comment]
Υλοποιήθηκε παρακαλώ ελέγξετε στην staging

**Comment by psakellis56** [comment]
Είμαστε ΟΚ!
