### ISSUE TITLE
Τήρηση εθνικών κανόνων - έλεγχος ορθότητας

### ISSUE THREAD

**Issue by YIANIS66** [mou-gr/regions#34]
ΚΑΡΤΕΛΑ 5.1: Η απάντηση και στις δύο ερωτήσεις να είναι υποχρεωτικά ΝΑΙ. Ο έλεγχος ορθότητας (καρτέλα 10) να αποκλείει την υποβολή με απαντήσεις : ΟΧΙ.

**Comment by apanagio** [comment]
θα υλοποιηθεί. Έχει ξανααναφερθεί #47
