### ISSUE TITLE
Περιγραφή επενδυτικού σχεδίου (συμμετοχή σε έκθεση)

### ISSUE THREAD

**Issue by YIANIS66** [mou-gr/regions#35]
Καρτέλα 6.1: να καταργηθούν όλες οι επιμέρους ερωτήσεις. Να παραμείνει ένα πεδίο στο οποίο ο δικαιούχος θα μπορεί να εισάγει ελεύθερο κείμενο και να απαντήσει στις ερωτήσεις που του δίνονται ως οδηγίες ή να γράψει ακόμη μερικά σημεία που επιθυμεί

**Comment by apanagio** [comment]
Αυτά τα πεδία τα έχει προδιαγράψει η ΕΥΚΕ, προσθέτω και τον Χρήστο Μπούρα @cbouras στην συζήτηση για να συμφωνήσουμε

**Comment by cbouras** [comment]
Αποτελούν πεδία του ΤΔΠ για το ΟΠΣ ΕΣΠΑ. Στις μέχρι τώρα δράσεις του ΕΠΑΝΕΚ σε αυτά βάζαμε ότι νάναι. Τώρα θα συμπληρώνονται από τον δικαιούχο. Για περισσότερες λεπτομέρειες για τα εν λόγω πεδία μιλήστε με την ΕΥ ΟΠΣ.

**Comment by psakellis56** [comment]
Αντιπροτείνουμε να παραμείνουν τα πεδία ενεργές μόνο οι ερωτήσεις 1, 2 ίσως κια η 5 και όλες οι άλλες να μην είναι ενεργές προς συμπλήρωση. 
Η δράση είναι απλή. Συμμετοχή σε εκθέσεις, σύμβουλος και τίποτε άλλο.
Δεν έχει ούτε μεθοδολογία, ούτε αναμενόμενα αποτελέσματα ούτε δημιουργία ΕΜΕ

**Comment by cbouras** [comment]
Αν κρατήσουμε μονο αυτά που λεει ο Παναγιώτης τότε όταν φτιάξουμε το ΤΔΠ θα ρίξουμε (--) παύλες στα άλλα και θα γεμίσουμε με (--) την SFC. Εγώ προτείνω να τα αφήσουμε και ότι γράψουν. Για τις ΕΜΕ μόνο προτείνω να μην είναι υποχρεωτικό για την εν λόγω δράση. Δεν την περνάμε στο ΟΠΣ ΕΣΠΑ την εν λόγω ερώτηση.

**Comment by tsitsopoulosexo** [comment]
Καλησπέρα
αν και δεν είμαι ειδικός στα θέματα του ΤΔΠ που τα γνωρίζετε καλύτερα προτείνω να υπάρχει σημείωση σε μορφή μηνύματος ότι στις 2-9 να βάζουν μία τελεία ενώ στο 10 (έχει γίνει στο ΠΣΚΕ στο πρόγραμμα της ΝΚΕ) να βγαίνει απευθείας προσυμπληρωμένη η φράση : Προβολή και προώθηση των προϊόντων της επιχείρησης για τη δημιουργία νέων συνεργασιών, ενίσχυση του επιχειρηματικού προφίλ και αύξηση των πωλήσεων. Επίσης 0 στις ΕΜΕ. Συμφωνώ με τον Παναγιώτη να μη τους βάζουμε να γράφουν χωρίς λόγο.

**Comment by cbouras** [comment]
Καλησπέρα,
Δεν ειναι αποδεκτό να βγει μύνημα για να συμπληρώνει ο δικαιούχος τελείες σε πεδία που είναι υποχρεωτικά για τα συγχρηματοδοτούμενα. Δεν θέλω να επεκταθώ με περισσότερα σχόλια για το σχόλιο του  tsitsopoulosexo. Ωστόσο να σημειώσω ότι υπάρχουν εκπαιδευτικά σεμινάρια που κάνει τόσο η ΜΟΔ όσο και το ΕΚΔΔΑ για το ΕΣΠΑ και τις κρατικές ενισχύσεις και καλό είναι να τα παρακολουθήσει κάποιος που ασχολείται με τέτοια προγράμματα.

**Comment by YIANIS66** [comment]
Να μείνουν οι ερωτήσεις. Η 6, 8 και η 11 να μην είναι ενεργές.

**Comment by galanosel** [comment]
Υλοποιήθηκε παρακαλώ ελέγξετε στην staging

**Comment by psakellis56** [comment]
Είμαστε ΟΚ, το issue μπορεί να κλείσει
