### ISSUE TITLE
απαίτηση για  EBITDA

### ISSUE THREAD

**Issue by psakellis56** [mou-gr/regions#36]
ΚΑΡΤΕΛΑ 1.5: Να αλλάξει τίτλο σε «Στοιχεία επιχείρησης που αξιολογούνται» και μέσα να προστεθεί πεδίο συμπλήρωσης για το Λειτουργικό Αποτέλεσμα προς φόρων, τόκων και αποσβέσεων. Να ελέγχεται στον έλεγχο ορθότητας (Καρτέλα 10) με την απαίτηση για  EBITDA > 0. Να μην επιτρέπει την υποβολή της αίτησης

**Comment by apanagio** [comment]
Το κλείνω και παρακαλώ να μεταφέρουμε την κουβέντα εδώ #38  γιατί υπάρχουν επικαλύψεις.
