### ISSUE TITLE
Άδεια λειτουργίας

### ISSUE THREAD

**Issue by YIANIS66** [mou-gr/regions#37]
ΚΑΡΤΕΛΑ 6.2: Να μεταφερθεί στην Ενότητα 1 ως χωριστή καρτέλα, να αλλάξει ο τίτλος από «Πίνακας αδειών» σε «Άδεια λειτουργίας» και να διαγραφεί το επεξηγηματικό πεδίο καθώς είναι λάθος. Άδεια λειτουργίας (ή ισοδύναμο έγγραφο) απαιτείται για όλες τις επιχειρήσεις που θέλουν να υποβάλουν πρόταση.

**Comment by apanagio** [comment]
Η μεταφορά μας δυσκολεύει πολύ. Καλό είναι να αποφευχθεί.
Ο τίτλος θα αλλάξει
Το επεξηγηματικό θα φύγει

**Comment by galanosel** [comment]
Άλλαξε ο τίτλος και έφυγε το επεξηγηματικό παρακαλώ ελέξτε στην staging

**Comment by psakellis56** [comment]
Οκ για τίτλο και επεξηγηματικό.
Προτείναμε να αλλάξει θέση γιατί αφορά κυρίως την επιχείρηση και δευτερευόντως το επιχειρηματικό σχέδιο. Ας μείνει εκεί.

Το issue μπορεί να κλείσει
