### ISSUE TITLE
Στοιχεία επιχείρησης - αξιολόγηση

### ISSUE THREAD

**Issue by YIANIS66** [mou-gr/regions#38]
Καρτέλα 6.3 :  όλη καρτέλα (όλες οι ερωτήσεις) να μεταφερθούν στην καρτέλα 1.5 με τον νέο τίτλο «Στοιχεία επιχείρησης που αξιολογούνται». Η απάντηση σε όλες τις ερωτήσεις να είναι υποχρεωτικά ΝΑΙ. Ο έλεγχος ορθότητας (καρτέλα 10) να αποκλείει την υποβολή με απαντήσεις : ΟΧΙ

**Comment by apanagio** [comment]
Θα υλοποιηθεί

**Comment by galanosel** [comment]
Η μεταφορά των στοιχείων της καρτέλας 6.3 στην καρτέλα 1.5 υλοποίηθηκε μπορείτε να το ελέγξετε στην staging.

Ο έλεγχος ορθότητας δεν μπορεί να γίνει, θα πρέπει να ελέγχεται στην αξιολόγηση

**Comment by psakellis56** [comment]
Η μεταφορά ΟΚ, αλλά δεν άλλαξε ο τίτλος της καρτέλας.
Θα τον αλλάξετε ή είναι δύσκολο ?
 Για τον έλεγχο ορθότητας συζητάμε συνολικά για όλα στο 47

**Comment by galanosel** [comment]
Δεν υπάρχει δυνατότητα αλλαγής του τίτλου στο tab. 
Υπάρχει όμως δυνατότητα αλλαγής τίτλου του πίνακα μέσα στο tab.
Παρακαλώ ελέγξετε staging

**Comment by psakellis56** [comment]
Είμαστε ΟΚ!
Το issue μπορεί να κλείσει
