### ISSUE TITLE
ΑΦΜ διασταύρωση στοιχείων

### ISSUE THREAD

**Issue by psakellis56** [mou-gr/regions#40]
ΚΑΡΤΕΛΑ 2.1 & 2.2 Ομοίως με τις παρατηρήσεις για το ΑΦΜ στις καρτέλες 1.2 και 1.3, δέχεται το ίδιο ΑΦΜ στον δικαιούχο και στην Συνεργαζόμενη/Συνδεδεμένη με αυτόν οντότητα

**Comment by apanagio** [comment]
το κλείνω και ας μεταφέρουμε την κουβέντα στο #26
