### ISSUE TITLE
Δαπάνες - επιχορηγηση

### ISSUE THREAD

**Issue by YIANIS66** [mou-gr/regions#41]
Καρτέλα 7.1 : οι δαπάνες και η αναλογούσα δημόσια δαπάνη δεν δουλεύουν σωστά. Ειδικότερα :
•	Δεν έχουν οριστεί οι δύο κατηγορίες δαπανών (Συμμετοχή σε εκθέσεις και Αμοιβές συμβούλων)
•	Να δημιουργηθεί νέο  πεδίο με τίτλο «Χώρα διοργάνωσης (εφόσον την γνωρίζετε)». Είναι μεν ενδεικτική αλλά μπορεί πολλοί να την γνωρίζουν
•	Να δημιουργηθεί νέο  πεδίο με τίτλο «Ημερ/νια διοργάνωσης (εφόσον την γνωρίζετε)». Ομοίως ως ανωτέρω. Θα συμπληρώνεται η τελευταία ημέρα της έκθεσης
•	Δεν έχουμε προσαύξηση της έντασης ενίσχυσης. Η ένταση ενίσχυσης είναι ΟΡΙΖΟΝΤΙΟ ποσοστό έως 50% σε όλους και για όλες τις κατηγορίες δαπανών
•	δεν δουλεύει σωστά ο υπολογισμός της αναλογούσας επιχορήγησης (έχουν λάθος οι πράξεις). 
Τέλος δεν δουλεύει σωστά ο έλεγχος ορθότητας (ενότητα 10) για την Καρτέλα 7.1

**Comment by apanagio** [comment]
Απαντάω inline:

Καρτέλα 7.1 : οι δαπάνες και η αναλογούσα δημόσια δαπάνη δεν δουλεύουν σωστά. Ειδικότερα :
• Δεν έχουν οριστεί οι δύο κατηγορίες δαπανών (Συμμετοχή σε εκθέσεις και Αμοιβές συμβούλων)
>>Υλοποιήθηκε (παρακαλώ στείλτε μου τους περιορισμούς που ενδεχομένως έχουν αυτές οι δαπάνες)

• Να δημιουργηθεί νέο πεδίο με τίτλο «Χώρα διοργάνωσης (εφόσον την γνωρίζετε)». Είναι μεν ενδεικτική αλλά μπορεί πολλοί να την γνωρίζουν
>>Δεν μπορεί να γίνει. Να μπαίνει στην τεκμηρίωση

• Να δημιουργηθεί νέο πεδίο με τίτλο «Ημερ/νια διοργάνωσης (εφόσον την γνωρίζετε)». Ομοίως ως ανωτέρω. Θα συμπληρώνεται η τελευταία ημέρα της έκθεσης
>>Δεν μπορεί να γίνει. Να μπαίνει στην τεκμηρίωση

• Δεν έχουμε προσαύξηση της έντασης ενίσχυσης. Η ένταση ενίσχυσης είναι ΟΡΙΖΟΝΤΙΟ ποσοστό έως 50% σε όλους και για όλες τις κατηγορίες δαπανών
>>Υλοποιήθηκε

• δεν δουλεύει σωστά ο υπολογισμός της αναλογούσας επιχορήγησης (έχουν λάθος οι πράξεις).
Παρακαλώ αναφέρετε συγκεκριμένα το λάθος, ή αν θέλετε τον κωδικό πρότασης στο ΠΣΚΕ όπου παρατηρείται το λαθος. Πιθανότατα τώρα που ορίστηκαν σωστά οι δαπάνες και η ένταση ενίσχυσης να έχει διορθωθεί.

Τέλος δεν δουλεύει σωστά ο έλεγχος ορθότητας (ενότητα 10) για την Καρτέλα 7.1
>>Διορθώθηκε

**Comment by psakellis56** [comment]
Κατηγορίες δαπανών :  ΟΚ
Θα το σκεφτούμε λίγο αν θα βάλουμε ενεργούς περιορισμούς ή θα τα λέμε απλά στο επεξηγηματικό πεδίο (δείτε παρακάτω)

Χώρα διοργάνωσης, ημερομηνία : Μπορούμε να φτιάξουμε ένα επεξηγηματικό πεδίο όπου θα τους λέμε τι πρέπει να συμπληρώνουν στην Τεκμηρίωση ? Αν ναι, θα σας πούμε τι κείμενο θα εμφανίζεται εκεί

Ένταση ενίσχυσης : ΟΚ

Υπολογισμοί αναλογούσας ΔΔ : ΟΚ τώρα που κλειδώσαμε την ένταση ενίσχυσης
(πριν αν πχ δήλωνες ένταση 30%, υπολόγιζε το ίδιο ποσοστό ως προσαύξηση και τελικά εμφάνιζε αναλογούσα ΔΔ στο 60%)

Στην καρτέλα 10 το λάθος παραμένει καθώς εμφανίζει το μήνυμα "Ο συνολικός επιλέξιμος προυπολογισμός της υπερβαίνει την μέγιστη επιsτρεπόμενη τιμή" που για την πρόταση Ν7ΕΕ 0000105 με τις δαπάνες που δηλώσαμε δεν είναι σωστό μήνυμα.

**Comment by tsitsopoulosexo** [comment]
Στο έντυπο υποβολής που αποτελεί παράρτημα στην αναλυτική πρόσκληση υπάρχει πίνακας σχετικά με αυτά που λέει ο Πάνος, Ο Πίνακας αποτελεί την αποτύπωση βασικών στοιχείων που περιγράφονται στο 9.1. ως ελεύθερο κείμενο. Εφόσον δεν μπορούν να γίνουν αυτά που εύλογα ζήτησε , τουλάχιστον στην τεκμηρίωση ας μπει μία παρένθεση που να εξηγεί τι να συμπληρώσουν οι επενδυτές Π.χ. Τεκμηρίωση (αναφορά στην ονομασία έκθεσης, χώρας, τόπος, ημερομηνία διοργάνωσης εφόσον τα γνωρίζετε). Δεν είναι δύσκολο, καθώς υπάρχουν αντίστοιχα πεδία σε άλλα σημεία. Γενικότερα είναι καλό όσο το δυνατό να έχουμε πληροφορίες που να διευκολύνουν χρονικά την αξιολόγηση αλλά και την υλοποίηση.

**Comment by psakellis56** [comment]
Το issue έκλεισε χωρίς να έχει λυθεί.
Περιμένουμε το ΟΚ για να μπει επεξηγηματικό πεδίο
Περιμένουμε να διορθωθεί ο έλεγχος ορθότητας

**Comment by psakellis56** [comment]
Οι έλεγχοι ορθότητας στις δαπάνες είναι ΟΚ. Κλείνω το issue και θα φτιάξουμε δύο καινούργια issues για infotexts στις Καρτέλες 7.1 και 7.3
