### ISSUE TITLE
!!!!

### ISSUE THREAD

**Issue by YIANIS66** [mou-gr/regions#44]
ΚΑΡΤΕΛΑ 7.4: Να διαγραφεί

**Comment by apanagio** [comment]
Υλοποιήθηκε.
Να επισημάνω μόνο ότι κάποιοι δείκτες θα πρέπει να περάσουν στο ΟΠΣ-ΕΣΠΑ στη φάση των τεχνικών δελτίων. Παρακαλώ εξασφαλίστε ότι έχει οριστεί ποιοι δείκτες είναι αυτοί και από που θα παίρνουν τιμές
