### ISSUE TITLE
δεν λειτουργεί στο 2.2 η Περίοδος Αναφοράς

### ISSUE THREAD

**Issue by psakellis56** [mou-gr/regions#45]
ΚΑΡΤΕΛΑ 2.2  δεν λειτουργεί στο 2.2 η Περίοδος Αναφοράς

**Comment by apanagio** [comment]
Παρακαλώ στείλτε τις δυνατές τιμές από τις οποίες θα πρέπει να επιλέγει ο επενδυτής

**Comment by YIANIS66** [comment]
να μπουν τα τρία (3) έτη (κλεισμένες διαχειριστικές χρήσεις) που προηγούνται του έτους υποβολής της αίτησης χρηματοδότησης. Για τις επιχειρήσεις που έχουν κλείσει λιγότερες διαχειριστικές χρήσεις η υποχρέωση υποβολής προσαρμόζεται αντίστοιχα. π.χ. υποβολή αίτησης 2018 να προσκομιστούν στοιχεία για 2017, 2016, 2015.

**Comment by YIANIS66** [comment]
Να προστεθεί και το έτος 2014.

**Comment by psakellis56** [comment]
Είμαστε ΟΚ. To issue έκλεισε.
