### ISSUE TITLE
Έλεγχος ορθότητας

### ISSUE THREAD

**Issue by YIANIS66** [mou-gr/regions#46]
ΚΑΡΤΕΛΑ 8: Η απάντηση και στις δύο ερωτήσεις να είναι υποχρεωτικά ΑΠΟΔΕΧΟΜΑΙ. Ο έλεγχος ορθότητας (καρτέλα 10) να αποκλείει την υποβολή με απαντήσεις : ΔΕΝ ΑΠΟΔΕΧΟΜΑΙ

**Comment by apanagio** [comment]
Υλοποιήθηκε
