### ISSUE TITLE
Έλεγχοι Ορθότητας Συνολικά

### ISSUE THREAD

**Issue by YIANIS66** [mou-gr/regions#47]
ΚΑΡΤΕΛΑ 10: Να εμπλουτιστεί με περισσότερους ελέγχους. Πχ:
•	ΕΒΙΤDA > 0
•	ΕΞΑΓΩΓΕΣ >= 2% του ΚΕ
•	Υποχρεωτικές απαντήσεις με ΝΑΙ στις ερωτήσεις της καρτέλας 1.5 (αυτές που μεταφέραμε από την καρτέλα 6.3)
•	Υποχρεωτικές απαντήσεις με ΝΑΙ στις ερωτήσεις της καρτέλας 5.1
•	Υποχρεωτικές απαντήσεις με ΑΠΟΔΕΧΟΜΑΙ στις ερωτήσεις της καρτέλας 8.

**Comment by apanagio** [comment]
Απαντάω inline:

ΚΑΡΤΕΛΑ 10: Να εμπλουτιστεί με περισσότερους ελέγχους. Πχ:
• ΕΒΙΤDA > 0
Δεν μπορεί να γίνει, θα πρέπει να ελέγχεται στην αξιολόγηση

• ΕΞΑΓΩΓΕΣ >= 2% του ΚΕ
Δεν μπορεί να γίνει, θα πρέπει να ελέγχεται στην αξιολόγηση

• Υποχρεωτικές απαντήσεις με ΝΑΙ στις ερωτήσεις της καρτέλας 1.5 (αυτές που μεταφέραμε από την καρτέλα 6.3)
Δεν μπορεί να γίνει, θα πρέπει να ελέγχεται στην αξιολόγηση

• Υποχρεωτικές απαντήσεις με ΝΑΙ στις ερωτήσεις της καρτέλας 5.1
Θα γίνει

• Υποχρεωτικές απαντήσεις με ΑΠΟΔΕΧΟΜΑΙ στις ερωτήσεις της καρτέλας 8.
Θα γίνει

Εναλλακτικά μπορούμε αν θέλετε να ενσωματώσουμε όλα όσα πρέπει να αποδεχτεί ο επενδυτής σε ένα ενιαίο κείμενο όπως είναι στην καρτέλα 8 και να είναι υποχρεωτική η απάντηση με "Αποδέχομαι" στο τέλος

**Comment by galanosel** [comment]
Σχετικά με τα 

• Υποχρεωτικές απαντήσεις με ΝΑΙ στις ερωτήσεις της καρτέλας 5.1
Υλοποιήθηκε και θα ανέβει staging 

• Υποχρεωτικές απαντήσεις με ΑΠΟΔΕΧΟΜΑΙ στις ερωτήσεις της καρτέλας 8.
Έχει υλοποιηθεί παρακαλώ ελέγξετε το στην staging

**Comment by psakellis56** [comment]
Παραμένει η ανάγκη για υποχρεωτικές απαντήσεις με ΝΑΙ στις ερωτήσεις της Καρτέλας 1.5. Δεν μπορεί να γίνει ??

Οι λοιποί έλεγχοι δουλεύουν.

Τα ΕΒΙΤDA και Εξαγωγές τα συζητάμε στο απαίτηση για 2% ΕΞΑΓΩΓΕΣ #42" όπου ζητήσαμε τα αλφαριθμητικά να είναι > 0.

**Comment by apanagio** [comment]
Μπήκε μοναδική επιλογή το ΝΑΙ

**Comment by psakellis56** [comment]
Είμαστε ΟΚ. To issue κλείνει
