### ISSUE TITLE
Κατηγορίες Δαπανών - συνολικό και επιλέξιμο μέρος

### ISSUE THREAD

**Issue by psakellis56** [mou-gr/regions#48]
Προτείνουμε στην οθόνη καταχώρησης ποσών στις Κατηγορίες δαπανών (Καρτέλα 7.1) να προστεθεί πεδίο με τίτλο "Συνολικό ποσό (€)" και μορφή αριθμός (μόνο θετικές τιμές). Είναι απαραίτητο καθώς το Φυσικό και Οικονομικό αντικείμενο της κάθε δαπάνης (όχι μόνο του ΕΠΙΧΕΙΡΟΥΜΕ ΕΞΩ) πιστοποιείται από τον ΕΦΔ και παραλαμβάνεται στο συνολικό και όχι στο επιλέξιμο μέρος του. Αν ο επενδυτής δηλώνει μόνο τα επιλέξιμο μέρος κάθε δαπάνης καταρχήν δεν ξέρουμε πόσο είναι το συνολικό άρα δεν μπορούμε να ελέγξουμε εύλογο πριν τη δούμε αλλά έχουμε και προβλήματα με εξοφλήσεις λογιστικές εγγραφές κλπ που όλα γίνονται στο συνολικό ποσό και όχι μόνο στο επιλέξιμο.

**Comment by tsitsopoulosexo** [comment]
Συμφωνώ με τον Πάνο. Είναι σημαντικό να γνωρίζουμε το φυσικό αντικείμενο (π.χ. αριθμός εκθέσεων) και το πλήρες οικονομικό αντικείμενο (συνολικός και επιχορηγούμενο π/υ) βάσει των οποίων θα γίνει η επαλήθευση-πιστοποίηση δαπανών.

**Comment by apanagio** [comment]
Κάνουμε μία προσπάθεια να απλοποιηθεί η διαδικασία υποβολής επενδυτικών σχεδίων για να μπορέσουν να επιταχυνθούν οι χρόνοι ανάπτυξης και διαχείρισης του συστήματος. Θεωρώ ότι μπορεί η διαδικασία χρηματοδότησης επενδυτικών σχεδίων να λειτουργήσει ομαλά και χωρίς την αποτύπωση των μη επιλέξιμων δαπανών. Από την πλευρά του επενδυτή θεωρώ ότι είναι πιο απλό να μας υποβάλει μόνο τις επιλέξιμες δαπάνες.

**Comment by cbouras** [comment]
Ένας επενδυτής όταν υποβάλλει ένα επενδυτικό σχέδιο στην πλειοψηφία των περιπτώσεων το υποβάλλει με την λογική ότι είναι όλες οι δαπάνες επιλέξιμες. Η μη επιλεξιμότητα προκύπτει στην φάση της αξιολόγησης και αργότερα του ελέγχου. Οπότε στην υποβολή δεν μας δημιουργεί πρόβλημα η υπάρχουσα υλοποίηση. Πόσοι είναι αυτοί που θα ξέρουν και θα υποβάλλουν μη επιλέξιμες δαπάνες εκ των προτέρων?

**Comment by psakellis56** [comment]
Ίσως δεν το έχουμε διατυπώσει καλά. Το πρόβλημα είναι στο Φυσικό αντικείμενο. Ο ΕΦΔ πρέπει από την αρχή να ξέρει αν το Φυσικό αντικείμενο που θα παραλάβει υπερβαίνει το επιλέξιμο (πχ τις 50.000€ σε μία συμμετοχή με περίπτερο > 50τμ) και όχι να το διαπιστώσει από τα παραστατικά εκ των υστέρων. Υπάρχουν πολλές εκθέσεις που θα κοστίζουν πιο πολύ, οι επενδυτές θα αναλαμβάνουν το κόστος αυτό από μόνοι τους και εμείς θα το μάθουμε απολογιστικά στο τέλος.

Και γενικά πως μπορούμε να μιλάμε μόνο σε επιλέξιμο κόστος χωρίς να γνωρίζουμε την αξία του αναλογούντος Φυσικού αντικειμένου ? 

Σε κάθε περίπτωση, εμείς διατυπώνουμε τα υπέρ και τα κατά και ο ΕΦΔ που είναι ο πραγματικός χρήστης εξέφρασε τη γνώμη του

**Comment by YIANIS66** [comment]
Καλημέρα και από μένα.
Θεωρώ ότι ο συνολικός προϋπολογισμός της αίτησης χρηματοδότησης πρέπει υποχρεωτικώς να αποτυπώνεται στο σύστημα ασχέτως του ύψους της επιλεξιμότητας. 
Θα υπάρξουν περιπτώσεις αιτήσεων με προϋπολογισμό 40.000 € με ένα παραστατικό από τον διοργανωτή της έκθεσης προς τον επενδυτή, με επιλέξιμη δαπάνη λόγω ορίων τα 35.000€. Η πιστοποίηση αυτή απαιτεί έλεγχο και επιλεξιμότητα των 40.000€, αποτύπωση των εξοφλήσεων στο ύψος των 40.000 €, εγγραφές στα 40.000€ για να κλείσει η πιστοποίηση στα επιλέξιμα 35.000€. 
Η υποβολή και πιστοποίηση δαπανών 35.000€ σε τιμολόγιο αξίας 40.000€ δεν καθιστά το παραστατικό πλήρως εξοφλημένο.

**Comment by apanagio** [comment]
Δεν καταλαβαίνω από τα παραπάνω επιχειρήματα γιατί πρέπει να είναι δηλωμένος ο μη επιλέξιμος προϋπολογισμός στη φάση της αξιολόγησης.

**Comment by apanagio** [comment]
Έχει εμπλουτιστεί ο πίνακας δήλωσης δαπανών 7.1 με πεδίο για το μη επιλέξιμο κομμάτι των δαπανών.

Έχει ενημερωθεί αντίστοιχα ο πίνακας 7.3 του χρηματοδοτικού σχήματος καθώς και οι έλεγχοι ορθότητας

**Comment by psakellis56** [comment]
Εμφανίστε το μη επιλέξιμο κομμάτι κάθε δαπάνης στην ΠΡΟΕΠΙΣΚΟΠΗΣΗ ώστε να καταλαβαίνουμε τη συνολική δαπάνη και το issue μπορεί να κλείσει.
Θα φτιάξουμε δύο καινούργια issue για δύο infotext στις Καρτέλες 7.1 και 7.3

**Comment by apanagio** [comment]
Υλοποιήθηκε

**Comment by psakellis56** [comment]
Δεν βλέπουμε το ΜΗ ΕΠΙΛΕΞΙΜΟ κομμάτι κάθε δαπάνης στην αρχική καρτέλα (προεπισκόπηση).

**Comment by galanosel** [comment]
Παρακαλώ ελέγξετε την staging

**Comment by psakellis56** [comment]
Καλημέρα,

Α) Μπορεί να εμφανιστεί η πληροφορία και στον πρώτο πάνω πάνω πίνακα (στον βασικό) ?
Β) Μπορείτε να μορφοποιήσετε τους αριθμούς (κόμματα, δεκαδικά) ?
Γ) Το ποσοστό στο τέλος (Δημόσια δαπάνη / επιλέξιμο (%)) είναι λάθος. Έπρεπε να είναι 50% και όχι 99% και 1%, στην πρόταση Ν7ΕΕ-0000105

**Comment by apanagio** [comment]
Α) υλοποιήθηκε
Β) το κοιτάμε, θα απαντήσουμε στο τέλος της μέρας
Γ) Ο υπολογισμός είναι σωστός, αλλά ειναι λάθος το label κανονικά έιναι Δ.Δ / Σύνολο Δ.Δ Το διορθώσαμε και τώρα που θα αναβαθμίσουμε την staging θα φανεί η αλλαγή

**Comment by apanagio** [comment]
Β) υλοποιήθηκε, 

αναβαθμίζουμε staging και σας ενημερώνουμε πότε θα φανούν οι αλλαγές

**Comment by psakellis56** [comment]
Γ) Η πληροφορία αυτή δεν έχει χρησιμότητα στο ΕΠΙΧΕΙΡΟΥΜΕ γιατί δεν υπάρχει περιορισμός ως προς τα επιμέρους όρια και την αναλογία μεταξύ των κατηγοριών δαπανών. Στα άλλα προγράμματα παίζει ρόλο, αλλά όχι στο ΕΠΙΧΕΙΡΟΥΜΕ ΕΞΩ. Ίσως θα μπορούσε και να κρυφτεί από τη Δράση αυτή

**Comment by apanagio** [comment]
Αυτό το κομμάτι του κώδικα είναι ενιαίο και με τις υπόλοιπες δράσεις, οπότε καλύτερα να μην το διαφοροποιήσουμε

**Comment by galanosel** [comment]
Η staging αναβαθμίστηκε παρακαλώ ελέγξετε τα Α, Β

**Comment by psakellis56** [comment]
Τα Α και Β είναι ΟΚ.
Στο Γ έχει λάθη ο τίτλος στην τελευταία στήλη του Πίνακα (αυτή με το ποσοστό) στην ΠΡΟΕΠΙΣΚΟΠΗΣΗ.
Ορθογραφικό στον πρώτο πίνακα και ξεχασμένος ο παλιός τίτλος στον δεύτερο

**Comment by galanosel** [comment]
Διορθώθηκαν τα ορθογραφικά στο Γ. 
Παρακαλώ ελέγξετε staging

**Comment by psakellis56** [comment]
Είμαστε ΟΚ. Το issue μπορεί να κλείσει
