### ISSUE TITLE
INFOTEXT στην Καρτέλα 7.1 (Δαπάνες)

### ISSUE THREAD

**Issue by psakellis56** [mou-gr/regions#53]
Παρακαλούμε να δημιουργηθεί infotext στην καρτέλα 7.1 με το παρακάτω λεκτικό : 

"Παρακαλούμε προχωρήστε στην καταχώρηση δαπανών ανά κατηγορία φροντίζοντας ώστε στα αιτούμενα κόστη : 
- το επιλέξιμο σκέλος των δαπανών κάθε κατηγορίας να υπακούει στα επιμέρους μέγιστα όρια της κατηγορίας (πχ μέχρι 50.000€ / έκθεση για περίπτερο άνω των 50 τμ) σύμφωνα με την Αναλυτική Πρόκληση της Δράσης, 
- το άθροισμα του επιλέξιμου σκέλους των δαπανών όλων των κατηγοριών να μην υπερβαίνει το μέγιστο επιχορηγούμενο Π/Υ (100.000€),
- το τυχόν μη επιλέξιμο σκέλος κάθε καταχωρισθείσας δαπάνης (δηλαδή η διαφορά μεταξύ του συνολικού και του επιλέξιμου κόστους) να καταχωριστεί στο πεδίο "Μη επιλέξιμο ποσό",
- στο πεδίο ΤΕΚΜΗΡΙΩΣΗ να αναφέρετε, εφόσον τα γνωρίζετε, κάθε διευκρινιστικό στοιχείο ή στοιχείο ταυτότητας της υποβαλλόμενης δαπάνης (πχ τμ περιπτέρου, τόπος, ημερομηνία διοργάνωσης έκθεσης, λοιπά επιμέρους κόστη κλπ).

Ως δαπάνες νοούνται είτε η συμμετοχή σε έκθεση είτε η αμοιβή συμβούλου υποστήριξης. Η καταχώρηση δαπανών μπορεί να γίνει είτε με ξεχωριστή εγγραφή για κάθε διακριτή δαπάνη (συμμετοχή σε έκθεση) είτε συγκεντρωτικά τηρώντας τους ανωτέρω κανόνες".

Αν θέλει ο ΕΦΕΠΑΕ ας προσθέσει φράσεις

**Comment by galanosel** [comment]
Υλοποιήθηκε παρακαλώ ελέγξετε staging

**Comment by psakellis56** [comment]
Καλημέρα, χρόνια πολλά και καλά!
Είμαστε ΟΚ, το issue μπορεί να κλείσει
