### ISSUE TITLE
INFOTEXT στην Καρτέλα 7.3 (Χρημ σχήμα)

### ISSUE THREAD

**Issue by psakellis56** [mou-gr/regions#54]
Παρακαλούμε να δημιουργηθεί infotext στην καρτέλα 7.3 με το παρακάτω λεκτικό : 

"Παρακαλούμε προχωρήστε στην καταχώρηση τιμών, όπου επιτρέπεται, φροντίζοντας ώστε : 
- στην Ιδιωτική συμμετοχή (Πεδία Α.1 ή/και Α.2) να περιλαμβάνεται το τυχόν μη επιλέξιμο σκέλος των δαπανών που καταχωρίστηκαν στην Καρτέλα 7.1"

Προσοχή στη συμπλήρωση των τιμών προκειμένου να υπάρχουν συμφωνίες με την καρτέλα 7.1 ως προς το συνολικό επιχορηγούμενο προϋπολογισμό (συνολικό επιλέξιμο ποσό στην καρτέλα 7.1) και την αιτούμενη επιχορήγηση (σύνολο δημόσιας δαπάνης στην καρτέλα 7.1)".

Αν θέλει ο ΕΦΕΠΑΕ ας προσθέσει φράσεις

**Comment by galanosel** [comment]
Υλοποιήθηκε παρακαλώ ελέγξετε staging

**Comment by psakellis56** [comment]
Λείπει από το infotext το παρακάτω : 

Προσοχή στη συμπλήρωση των τιμών προκειμένου να υπάρχουν συμφωνίες με την καρτέλα 7.1 ως προς το συνολικό επιχορηγούμενο προϋπολογισμό (συνολικό επιλέξιμο ποσό στην καρτέλα 7.1) και την αιτούμενη επιχορήγηση (σύνολο δημόσιας δαπάνης στην καρτέλα 7.1).

**Comment by galanosel** [comment]
Υλοποιήθηκε παρακαλώ ελέγξετε staging

**Comment by psakellis56** [comment]
Είμαστε ΟΚ, το issue μπορεί να κλείσει
