### ISSUE TITLE
ΦΟΡΜΑ ΠΡΟΣΚΛΗΣΗΣ - TAB 1 - ΓΕΝΙΚΑ ΣΤΟΙΧΕΙΑ ΠΡΟΣΚΛΗΣΗΣ

### ISSUE THREAD

**Issue by cbouras** [mou-gr/regions#61]
Οι ημερομηνίες έναρξης και λήξης υποβολής να αφαιρεθούν διότι έχουν προβλεφθεί σε άλλο σημείο της εφαρμογής.

**Comment by galanosel** [comment]
Η αλλαγή πραγματοποιήθηκε θα εμφανιστεί το επόμενο διάστημα στο url που χρησιμοποιούμε ως "staging".
