### ISSUE TITLE
Γενικά Στοιχεία Πρόσκλησης - Εφαρμοστέος Κανονισμός / Καθεστώς Ενίσχυσης

### ISSUE THREAD

**Issue by cbouras** [mou-gr/regions#62]
Αντί για drop down box με τιμές 01. Deminimis και 02. 651 θα χρειαστούμε λίστα με check boxes για την επιλογή όσων άρθρων απαιτούνται.

**Comment by galanosel** [comment]
Υλοποιήθηκε, η αλλαγή θα φανεί τις επόμενες ημέρες στο url που χρησιμοποιούμε ως "staging"
