### ISSUE TITLE
Θεματικοί Στόχοι, Επενδυτικές Προτεραιότητες, Ειδικοί Στόχοι

### ISSUE THREAD

**Issue by cbouras** [mou-gr/regions#63]
Να προστεθεί εγγραφή για το ΑΤΠ. Θα πρέπει να γίνει ένας μετασχηματισμός.
Εφόσον προστεθεί το ATP που το χρειαζόμαστε για το ΤΔΠ, αυτό περιέχει την απαραίτητη πληροφορία και δεν χρειάζεται να κάνουμε χρήση των πεδίων (Επιχειρησιακό Πρόγραμμα, Αξονας, Ταμείο, Κατηγορία Περιφέρειας - αυτά τα πεδία δεν τα στέλνουμε στο ΟΠΣ ΕΣΠΑ.). Για το ΕΣΠΑ δεν μας χρειάζονται. Να δούμε όμως αν μας χρειάζονται για το Leader.

**Comment by galanosel** [comment]
Προστέθηκε, η αλλαγή θα φανεί τις επόμενες ημέρες στο url που χρησιμοποιούμε ως "staging"
