### ISSUE TITLE
Προβλεπόμενος Δείκτης Παρακολούθησης

### ISSUE THREAD

**Issue by cbouras** [mou-gr/regions#64]
Για τους δείκτες δεν μας χρειάζεται η πληροφορία:
Επιχειρησιακό Πρόγραμμα
Άξονας Προτεραιότητας
Ταμείο
Επενδυτική Προτεραιότητα

**Comment by galanosel** [comment]
Αφαιρέθηκαν όλα τα πεδία εκτός απο το "Επιχειρησιακό Πρόγραμμα", η αλλαγή θα φανεί τις επόμενες ημέρες στο url που χρησιμοποιούμε ως "staging"
Αρχικά το "Επιχειρησιακό Πρόγραμμα" αρχικά δεν το είχαμε συμπεριλάβει στα πεδία που πρέπει να αφαιρεθούν. Παρακαλώ επιβεβαιώστε ότι πρέπει να διαγραφεί το εν λόγω πεδίο.
