### ISSUE TITLE
Ενισχυόμενες Κατηγορίες - Επιπρόσθετα Στοιχεία Πρόσκλησης - ΚΑΔ / NACE

### ISSUE THREAD

**Issue by cbouras** [mou-gr/regions#65]
Δεν χρειάζεται το συγκεκριμένο, αφού οι δείκτες είναι σε λίστα σε άλλο σημείο της πρόσκλησης.

**Comment by galanosel** [comment]
Το πεδίο αφαιρέθηκε, η αλλαγή θα φανεί τις επόμενες ημέρες στο url που χρησιμοποιούμε ως "staging"
