### ISSUE TITLE
ΚΩΔΙΚΟΠΟΙΗΣΗ ΚΑΘΕΣΤΩΤΩΝ ΠΡΟΣΚΛΗΣΗΣ

### ISSUE THREAD

**Issue by cbouras** [mou-gr/regions#68]
Το πεδίο Εφαρμοστέος Κανονισμός / Καθεστώς Ενίσχυσης θα επιτρέπει την επιλογή παραπάνω από ένα καθεστώς ενίσχυσης - άρθρο. Επισυνάπτεται σχετική λίστα. Το drop - down box θα αλλάξει σε λιστα με check boxes.
[κωδικοποίηση ΚΡΑΤΙΚΩΝ ΕΝΙΣΧΥΣΕΩΝ ΣΤΟ ΟΠΣ ΕΣΠΑ.xlsx](https://github.com/mou-gr/regions/files/1757728/default.xlsx)

**Comment by galanosel** [comment]
Υλοποιήθηκε, η αλλαγή θα φανεί τις επόμενες ημέρες στο url που χρησιμοποιούμε ως "staging"
