### ISSUE TITLE
Προδιαγραφές για ελέγχους ορθότητας 

### ISSUE THREAD

**Issue by galanosel** [mou-gr/regions#7]
Θα χρειαστούμε προδιαγραφές για ελέγχους ορθότητας στα παρακάτω tabs του ΠΣΚΕ:

1) 6,1 Φυσικό Αντικείμενο
2) 8.1 Αποδοχή Όρων και Προϋποθέσεων

**Comment by cbouras** [comment]
Θα πρέπει να συμπληρωθούν.

**Comment by galanosel** [comment]
Υλοποιήθηκε και θα ανέβει staging

**Comment by galanosel** [comment]
Έχει υλοποιηθεί παρακαλώ ελέγξετε το στην staging
