### ISSUE TITLE
ΣΥΜΒΑΣΗ ΕΚΧΩΡΗΣΗΣ - ΕΚΔΟΤΡΙΑ ΤΡΑΠΕΖΑ

### ISSUE THREAD

**Issue by cbouras** [mou-gr/regions#71]
Να αντικατασταθεί το ελεύθερο πεδίο με λίστα τιμών. Αν θέλουμε στατιστικά δεν θα βγάλουμε άκρη. Η λίστα τιμών υπάρχει στο κείμενο ανάλυσης των προκαταβολών.
Το λεκτικό Δικαιούχος Επιχείρησης να αφαιρεθεί το ς. 
Διακούχος Επιχείρηση δεν μπορεί να είναι άλλη από την ίδια την επιχείρηση. Οπότε θα υπάρχει λίστα τιμών με τις επιχειρήσεις που συμμετέχουν στο έργο.

**Comment by galanosel** [comment]
Υλοποιήθηκε παρακαλώ ελέγξετε στην staging.

To πεδίο "Δικαιούχος Επιχείρησης" το αφαίρεσα καθώς υπάρχει το πεδίο "Δικαιούχος" στην αρχή της φόρμας όπου καταχωρείται η πληροφορία που θέλουμε.
