### ISSUE TITLE
ΥΛΟΠΟΙΗΣΗ ΕΠΕΝΔΥΣΗΣ

### ISSUE THREAD

**Issue by cbouras** [mou-gr/regions#72]
1. Τα δύο tabs με τις ερωτήσεις που ζητάμε από τον δικαιούχο να απαντήσει περιλαμβάνουν όλα τα ερωτήματα στην λίστα. Προτείνω στην λίστα να εμφανίζονται τα 2 πρώτα και όταν ανοίγεις να εμφανίζονται τα υπόλοιπα.
2. Η λίστα των ερωτημάτων είναι διαφορετική μεταξύ των ειδών ελέγχου (ενδιάμεσου ή τελικού). Προτείνω ΕΦΕΠΑΕ, ΕΠΑΝΕΚ και ΕΥΚΕ να συνεργαστούν για την παράδοση μίας εννιαίας λίστας ανά περίπτωση ελέγχου.
3. Επαναφέρω το θέμα: Είναι αναγκαίο ο δικαιούχος να απαντά τα ερωτήματα που θα απαντήσει και ο ελεγκτής; Η προσέγγιση της ΕΥΚΕ είναι: Ο δικαιούχος υποβάλει αίτηση και δικαιολογητικά και ο ελεγκτής απαντά στα ερωτήματα.

**Comment by galanosel** [comment]
1. Υλοποιήθηκε παρακαλώ ελέγξετε staging
