### ISSUE TITLE
ΠΡΟΟΔΟΣ ΥΛΟΠΟΙΗΣΗΣ ΦΥΣΙΚΟΥ ΚΑΙ ΟΙΚΟΝΟΜΙΚΟΥ ΑΝΤΙΚΕΙΜΕΝΟΥ - ΠΑΡΑΣΤΑΤΙΚΑ

### ISSUE THREAD

**Issue by cbouras** [mou-gr/regions#73]
1. Με το που πατάς + δημιουργεί έγγραφή με εσωτερικό κωδικό PurchaseVoucherID και μετά μπαίνεις στην φόρμα. Φαντάζομαι ότι το PurchaseVoucherID  είναι εσωτερικό κρυφό αριθμητήρι και δεν θα φαίνεται στο παραγωγικό περιβάλλον ή αν είναι να φαίνεται να του δώσουμε ένα τίτλο.
2. Ο Προμηθευτής δεν μπορεί να είναι ελεύθερο πεδίο. Θα πρέπει να έρχεται με λίστα τιμών από τον προηγούμενο πίνακα.
3. Η σειρά θα πρέπει να είναι ΑΦΜ Προμηθευτή, Προμηθευτής, Αξία χωρίς ΦΠΑ και Αξία Με ΦΠΑ.
4.  Προτείνω να προστεθεί και πεδίο για ΦΠΑ.
5. Δεν μπορώ να αποθηκεύσω τα δεδομένα του παραστατικού (got response:
{"status":"1", "rowid":"", "messages":[{"message 1":"Error while handling request.\nDetails: Object reference not set to an instance of an object."}]})

**Comment by galanosel** [comment]
1. Το PurchaseVoucherID  δεν εμφανίζεται πλέον
2. Δεν έχουμε πλέον φόρμα καταχώρησης των στοιχείων των προμηθευτών γι' αυτό είναι free text το πεδίο "Προμηθευτής".
3. Υλοποιήθηκε
4. Δεν υπάρχει column στην βάση για την υποδοχή αυτής της πληροφορίας. Παρακαλώ ενημερώστε μας αν είναι απαραίτητο να προστεθεί το πεδίο προκειμένου να αλλάξω το σχήμα της βάσης.
5. Επιλύθηκε
