### ISSUE TITLE
ΕΙΔΟΣ ΑΙΤΗΜΑΤΟΣ ΕΠΑΛΗΘΕΥΣΗΣ

### ISSUE THREAD

**Issue by cbouras** [mou-gr/regions#74]
Πριν από τα γενικά στοιχεία του δικαιούχου προτείνεται να εισαχθεί ένα επιπλέον tab 
Στοιχεία Αιτήματος Επαλήθευσης
Με δεδομένα:

Είδος Αιτήματος Επαλήθευσης
Αριθμός Αιτήματος

**Comment by galanosel** [comment]
Καλησπέρα σας, 

Υλοποιήθηκε, η προσθήκη θα φανεί τις επόμενες ημέρες στο url που χρησιμοποιούμε ως "staging"
