### ISSUE TITLE
2.2. ΣΤΟΙΧΕΙΑ ΛΗΨΗΣ ΔΑΝΕΙΟΥ

### ISSUE THREAD

**Issue by cbouras** [mou-gr/regions#75]
2.2. | ΣΤΟΙΧΕΙΑ ΛΗΨΗΣ   ΔΑΝΕΙΟΥ
-- | --
ΑΑ | ΔΙΚΑΙΟΥΧΟΣ | ΑΡΙΘΜΌΣ   ΣΎΜΒΑΣΗΣ ΔΑΝΕΙΟΥ | ΕΚΔΌΤΡΙΑ   ΤΡΆΠΕΖΑ | ΗΜΕΡΟΜΗΝΊΑ   ΔΑΝΕΙΑΚΉΣ ΣΎΜΒΑΣΗΣ | ΔΙΆΡΚΕΙΑ   ΙΣΧΎΟΣ ΔΑΝΕΙΑΚΉΣ ΣΎΜΒΑΣΗΣ | ΎΨΟΣ   ΔΑΝΕΊΟΥ | Ακαθάριστο   Ισοδύναμο ενίσχυσης (για ΧΜ) | ΑΡΙΘΜΟΣ   ΤΡΑΠΕΖΙΚΟΥ ΛΟΓΑΡΙΑΣΜΟΥ – ΤΡΑΠΕΖΙΚΟΥ ΙΔΡΥΜΑΤΟΣ

**Comment by galanosel** [comment]
Υλοποιήθηκε, η αλλαγή θα φανεί τις επόμενες ημέρες στο url που χρησιμοποιούμε ως "staging"
