### ISSUE TITLE
ΣΤΟΙΧΕΙΑ ΑΙΤΗΜΑΤΟΣ ΕΠΑΛΗΘΕΥΣΗΣ

### ISSUE THREAD

**Issue by cbouras** [mou-gr/regions#76]
Στο 1.1. στα στοιχεία αιτήματος επαλήθευσης δεν θα πρέπει να εισάγει παραπάνω από μία εγγραφή.

**Comment by galanosel** [comment]
Υλοποιήθηκε παρακαλώ ελέγξτε staging
