### ISSUE TITLE
ΓΕΝΙΚΑ ΣΤΟΙΧΕΙΑ ΔΙΚΑΙΟΥΧΟΥ

### ISSUE THREAD

**Issue by cbouras** [mou-gr/regions#77]
Στα Γενικά Στοιχεία Δικαιούχου το helptext δεν έχει κάποιο νόημα:
Η επιχείρηση απαιτείται να έχει συσταθεί τουλάχιστον δώδεκα (12) μήνες πριν την ημερομηνία υποβολής της αίτησης χρηματοδότησης.

**Comment by tsitsopoulosexo** [comment]
Συμφωνώ με το Χρήστο. Δεν έχει νόημα για ενταγμένους στη Δράση. 

Ιωάννης Τσιτσόπουλος

**Comment by galanosel** [comment]
Υλοποιήθηκε παρακαλώ ελέγξτε στην staging
