### ISSUE TITLE
ΣΤΟΙΧΕΙΑ ΕΠΕΝΔΥΣΗΣ

### ISSUE THREAD

**Issue by cbouras** [mou-gr/regions#79]
1. Το Λεκτικό που υπάρχει ως helpdtext δεν έχει νόημα στον Έλεγχο. Προτείνω να αφαιρεθεί
2. Τα πεδία δεν θα είναι επεξεργάσιμα
3. Να προστεθεί ο Κωδικός MIS: Θα έρχεται προσυμπληρωμένο από το ΟΠΣ ΕΣΠΑ

**Comment by galanosel** [comment]
Υλοποιήθηκε με την επόμενη αναβάθμιση της staging θα φανούν όλες οι αλλαγές
