### ISSUE TITLE
ΝΑΛΥΣΗ ΤΗΣ ΕΠΕΝΔΥΤΙΚΗΣ ΠΡΑΞΗΣ (ΕΡΓΟΥ) ΚΑΤΑ ΚΑΤΗΓΟΡΙΑ ΕΠΙΛΕΞΙΜΗΣ ΔΑΠΑΝΗΣ

### ISSUE THREAD

**Issue by cbouras** [mou-gr/regions#81]
1. Δεν χρειάζεται να υπάρχει το helptext στον έλεγχο.
2. Για τα ΠΕΠ φαντάζομαι ότι θα έρχεται ο Πίνακας των Κατηγοριών Δαπανών που υπάρχουν εκεί.

**Comment by galanosel** [comment]
1. Το helptext αφαιρέθηκε
2. Ναι

**Comment by tsitsopoulosexo** [comment]
Καλησπέρα και απο μένα.
Αναμένω να ολοκληρωθεί το σύνολο της εργασίας για να τα δω στο σύνολο και να τοποθετηθώ. 
Φαντάζομαι ότι θα μας ενημερώσετε προκειμένου να κάνουμε testing. 
Ωστόσο θέλω να επισημάνω τα εξής :+1: 
Εχω αποστείλει πλήρεις και αναλυτικές απαντήσεις επί του αρχικού σχεδίου τον Ιούλιο. Ο Χ. Μπούρας απάντησε και έστειλε χρήσιμες επισημάνσεις.

Αναμένω να δω εάν τα σημεία στα οποία υπήρχε συμφωνία υλοποιήθηκαν. 
Μέχρι τώρα βλέπω π.χ τα εξής : 
1) Στο δάνειο δεν  υπάρχει η ερώτηση εάν το δάνειο είναι μέσω χρηματοοικονομικών εργαλείων. Το ότι έχει ΑΙΕ ο πίνακας δε βοηθά πλήρως καθώς ο επενδυτής την έννοια ΑΙΕ δεν την καταλαβαίνει πλήρως , πιστέψτε με.
Αν υπήρχε πρώτα η ερώτηση (αν η απάντηση είναι ΝΑΙ συμπληρώνει το ΑΙΕ) και μετά ο πίνακας.
Αν δε σας ικανοποιεί τότε να μπει ως βοηθητικό help 
H συμπλήρωση του ΑΙΕ στον πίνακα λαμβάνει χώρα μόνο όταν το δάνειο που λαμβάνει ο Δικαιούχος είναι μέσω χρηματοοικονομικών εργαλείων του ΕΣΠΑ (π.χ. ΤΕΠΙΧΙΙ, ...)

2) Πολλά πεδία δε λειτουργεί το detail που πατάμε και δε βλέπουμε τι γίνεται.

3) Στον πίνακα με την ανάλυση της επενδυτικής πράξης επισημαίνω το εξής πολύ σημαντικό ζήτημα.
Ολες οι δράσεις επιχειρηματικότητας έχουν όρια ανά κατηγορία δαπάνης και σε ορισμένες εξ΄ αυτών εντός της ίδιας κατηγορίας υποκατηγορίες δαπανών με επίσης όρια. Αυτά θα πρέπει να αποτυπωθούν  ΥΠΟΧΡΕΩΤΙΚΑ στον τελικό πίνακα για να γνωρίζει ο δικαιούχος το ορθό ποσό επιχορήγησης που θα λάβει και τον αντίστοιχο επιλέξιμο επιχορηγούμενο π/υ.

Η εν λόγω παρατήρηση έχει πολύ σημαίνοντα ρόλο στην πιστοποίηση όπου : α) είτε θα υπάρχει αντίστοιχος πίνακας όπως στις 4 δράσεις όπου υπάρχει ο τελικός πίνακας πιστοποίησης με τον τελικό πιστοποιημένο-επιχορηγούμενο μετά την τήρηση των ορίων ανά κατηγορία δαπάνης βάσει του οποίου υπολογίζεται η επιχορήγηση
β) είτε θα πρέπει ο υφιστάμενος πίνακας που έχετε δημιουργήσει βάσει παραστατικών να συμπληρωθεί με πίνακα πιστοποίησης όπου θα δούμε τον τρόπο τήρησης των ορίων (ίσως και με χρήση εξωσυστημικής διαδικασίας όπου το αρχείο θα αναρτάται στην πιστοποίηση).

4) Μη ξεχάσετε το θέμα των τροποποιήσεων που εντάσσονται στο αίτημα επαλήθευσης και όχι ως ξεχωριστό αίτημα τροποποίησης.

Ευχαριστώ.
