### ISSUE TITLE
5.2. ΔΑΠΑΝΕΣ

### ISSUE THREAD

**Issue by cbouras** [mou-gr/regions#82]
Τα πεδία Προμηθευτής και ΑΦΜ Προμηθευτή δεν πρέπει να είναι και στις ΔΑΠΑΝΕΣ και στα ΠΑΡΑΣΤΑΤΙΚΑ. Θεωρώ ότι πρέπει τα καταγράφει μόνο σε ένα σημείο και αυτό είναι τα Παραστατικά. Προτείνω να αφαιρεθούν από τις ΔΑΠΑΝΕΣ τα πεδία αυτά.

**Comment by galanosel** [comment]
Υλποιήθηκε

**Comment by galanosel** [comment]
Υλοποιήθηκε
