### ISSUE TITLE
1.1 ΣΤΟΙΧΕΙΑ ΑΙΤΗΜΑΤΟΣ ΕΠΑΛΗΘΕΥΣΗΣ

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#85]
Για ΠΕΠ , όπως διαμορφωθεί κατάλληλα η οθόνη 1.1 ΣΤΟΙΧΕΙΑ ΑΙΤΗΜΑΤΟΣ ΕΠΑΛΗΘΕΥΣΗΣ 

(αυτή τη στιγμή φέρνει περίεργη όψη, πχ ΔΕΡ7-0000765])

**Comment by galanosel** [comment]
Θα ενημερωθεί το json της οθόνης απο τον αρμόδιο dev

**Comment by sadamaki** [comment]
δονε
