### ISSUE TITLE
5.5. ΠΛΗΡΩΜΕΣ

### ISSUE THREAD

**Issue by cbouras** [mou-gr/regions#86]
Στο tab των Πληρωμών επαναλαμβάνονται τα στοιχεία λογιστικής εγγραφής που υπάρχουν και στο tab των Παραστατικών. Θεωρώ ότι πρέπει να μείνουν τα πεδία Είδος Βιβλίου, Είδος Εγγραφής, Αριθμός Εγγραφής, Ημερομηνία Εγγραφής και Σελίδα Βιβλίου μόνο στις Πληρωμές. Δεν είναι ανάγκη να τα έχουμε σε δύο σημεία. Ας επιβεβαιώσει και ο ΕΦΕΠΑΕ.

**Comment by tsitsopoulosexo** [comment]
Τα πεδία αριθμός εγγραφής, σελίδα βιβλίου είναι παντελώς αδιάφορα. Μας αρκεί το είδος βιβλίου, η ημερομηνία εγγραφής και το είδος εγγραφής. Ποτέ δε συμπληρώναμε τα άλλα. Υπάρχει κάποια υποχρέωση από το ΣΔΕ για αυτά που ζητώ να μην υπάρχουν;
