### ISSUE TITLE
Αίτημα Ενδιάμ. Ελέγχ. : 1.1 ΣΤΟΙΧΕΙΑ ΑΙΤΗΜΑΤΟΣ ΕΠΑΛΗΘΕΥΣΗΣ : Έλεγχος ορθότητας 

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#87]
1.1 ΣΤΟΙΧΕΙΑ ΑΙΤΗΜΑΤΟΣ ΕΠΑΛΗΘΕΥΣΗΣ : Έλεγχος ορθότητας 

Εφόσον μείνει ασυμπλήρωτος ο πίνακας 1.1 και το πεδίο " Είδος Αιτήματος Επαλήθευσης" , τότε υποχρεωτικό μήνυμα στον έλεγχο ορθότητας :

1.1 Όπως συμπληρώσετε το πεδίο "Είδος Αιτήματος Επαλήθευσης" του πίνακα 1.1 Στοιχεία Αιτήματος Επαλήθευσης

**Comment by galanosel** [comment]
Υλοποίηθηκε έλεγχος τουλάχιστον μίας εγγραφής σε αυτή την οθόνη
Θα φανεί με την επόμενη αναβάθμιση της staging

**Comment by sadamaki** [comment]
[1.1] Ελάχιστος αριθμός εγγραφών: 1
