### ISSUE TITLE
Αίτημα Ελέγχου : Tab 1.4 =Helptext

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#88]
1.4 ΣΤΟΙΧΕΙΑ ΜΕΤΟΧΩΝ Ή ΕΤΑΙΡΩΝ ΤΟΥ ΦΟΡΕΑ/ΕΠΙΧΕΙΡΗΣΗ : ΕΠΙΧΕΙΡΟΥΜΕ ΕΞΩ
Εφόσον ο πίνακας στο Αίτημα Ενδιάμεσου Ελέγχου παραμείνει read only, όπως σβήσουμε το helptext που αυτή τη στιγμή φαίνεται να υπάρχει στο tab 1.4 :
"Αν υπάρχουν πολλοί μέτοχοι, να καταχωρηθούν μόνο όσοι έχουν μερίδιο ≥25% ή οι πέντε με το μεγαλύτερο ποσοστό αν υπάρχουν εκατοντάδες μικρομέτοχοι".

**Comment by galanosel** [comment]
Υλοποιήθηκε παρακαλώ ελέγξετε staging

**Comment by sadamaki** [comment]
ναι ελέχθηκε η staging, ειναι οκ
