### ISSUE TITLE
ΠΕΠ -Αίτημα Ενδιάμεσου Ελέγχου : tab 1.4

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#89]
ΠΕΠ -Αίτημα Ενδιάμεσου Ελέγχου : tab 1.4 ΣΤΟΙΧΕΙΑ ΜΕΤΟΧΩΝ Ή ΕΤΑΙΡΩΝ ΤΟΥ ΦΟΡΕΑ/ΕΠΙΧΕΙΡΗΣΗ :

-Στη συνάντηση μας είχαμε πει στο Αίτημα Ελέγχου να γίνει read only το tab 1.4    ΣΤΟΙΧΕΙΑ ΜΕΤΟΧΩΝ Ή ΕΤΑΙΡΩΝ ΤΟΥ ΦΟΡΕΑ/ΕΠΙΧΕΙΡΗΣΗ.

-Εφόσον γίνει read only (ακόμη και να θέλει τα κάνει Τροποποίηση, είχαμε πει τα τροποποιημένα θα τα δηλώνει ο ελεγκτής στην ενέργεια του Ελέγχου) , να μην εμφανίζεται πλέον το helptext που υπάρχει ανά ΠΕΠ στο tab 1.4

**Comment by galanosel** [comment]
Το tab 1.4 έχει γίνει read only
