### ISSUE TITLE
Μέτοχοι <= 100%

### ISSUE THREAD

**Issue by apanagio** [mou-gr/regions#9]
Στον πίνακα  θα πρέπει να ελέγχεται το άθροισμα των ποσοστών των εταίρων/ μετόχων δηλ. να μην είναι μεγαλύτερο από το 100%

**Comment by apanagio** [comment]
Θα υλοποιηθεί

**Comment by galanosel** [comment]
Υλοποιήθηκε - Παρακαλώ τσεκάρετε

**Comment by mariaelanet** [comment]
Δεν έχει γίνει αλλαγή και δεν το βγάζει σαν σφάλμα στον έλεγχο ορθότητας

**Comment by galanosel** [comment]
Έχει υλοποιηθεί και θα ανέβει staging
