### ISSUE TITLE
Επιχειρούμε ΕΞΩ -Αίτημα Ενδιάμεσου Ελέγχου -Tab 1.7 Tόπος Υλοποίησης

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#90]
Υπάρχει νόημα να εμφανίζεται το helptext? (μιας που έγινε read only? ) Eκτός και αν ζητήσει η Διαχειριστική να ανοίξει ο πίνακας για να μπορεί πχ ο χρήστης να αποτυπώνει εδώ τυχόν τροποποίηση τόπου υλοποίησης.

"Δηλώνεται η Περιφέρεια στην οποία βρίσκεται η έδρα της επιχείρησης ή εκείνη στην οποία είναι εγκατεστημένη η μονάδα/τόπος παραγωγής του προϊόντος που προορίζεται για προβολή"

**Comment by galanosel** [comment]
Παρακαλώ δώστε μας οδηγία σχετικά με το αν πρέπει να αφαιρέσουμε το helptext

**Comment by sadamaki** [comment]
Xρήστο, γνωρίζεις κάτι ;
