### ISSUE TITLE
3.1 ΥΛΟΠΟΙΗΣΗ ΤΗΣ ΕΠΕΝΔΥΣΗΣ(1) -Έλεγχος ορθότητας

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#94]
Έλεγχος ορθότητας= Μήπως θα πρέπει να υλοποιηθεί κάποιος έλεγχος ορθότητας τουλάχιστον μίας εγγραφής στον πίνακα? (αν είναι συνεργατικά και θέλει να υποβάλλει αίτημα ελέγχου για παραπάνω του ενός δικαιούχου τότε λογικά θα είναι στην ευθύνη του?)

**Comment by galanosel** [comment]
Υλοποιήθηκε έλεγχος τουλάχιστον μίας εγγραφής στον πίνακα.
Παρακαλώ ελέγξετε staging

**Comment by sadamaki** [comment]
[3.1] Ελάχιστος αριθμός εγγραφών: 1

Υλοποιήθηκε με τον παραπάνω έλεγχο ορθότητας όταν ο πίνακας είναι κενός.
