### ISSUE TITLE
3.2 ΥΛΟΠΟΙΗΣΗ ΤΗΣ ΕΠΕΝΔΥΣΗΣ(2)-Έλεγχος Ορθότητας

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#97]
Έλεγχος Ορθότητας -Υποχρεωτική μία εγγραφή στον πίνακα (αν είναι συνεργατικά και θέλει να υποβάλλει αίτημα ελέγχου για παραπάνω από έναν δικαιούχο, πώς θα μπορούσε να ελεγχθεί?)

**Comment by galanosel** [comment]
Υλοποιήθηκε έλεγχος τουλάχιστον μίας εγγραφής στον πίνακα.
Παρακαλώ ελέγξετε staging

**Comment by sadamaki** [comment]
[3.2] Ελάχιστος αριθμός εγγραφών: 1

Υλοποιήθηκε με τον παραπάνω έλεγχο ορθότητας όταν ο πίνακας είναι κενός.
