### ISSUE TITLE
5.2 Δαπάνες -Έλεγχος ορθότητας 

### ISSUE THREAD

**Issue by sadamaki** [mou-gr/regions#99]
Με έλεγχο ορθότητας να ελέγχεται υποχρεωτική τουλάχιστον μία εγγραφή για τον πίνακα 5.2 .
Συμφωνείτε?

**Comment by galanosel** [comment]
Ο έλεγχος προστέθηκε

**Comment by sadamaki** [comment]
Ν7ΕΕ-0000884

Αυτή τη στιγμή καμμία εγγραφή στον πίνακα 5.2 Δαπάνες, και παρόλα αυτά δεν εμφανίζεται κανένας έλεγχος ορθότητας σχετικός (αναβάθμιση στη staging έκανε ο Μουστάκας χθες στις 1836)

**Comment by galanosel** [comment]
Επιλύθηκε θα φανεί με την επόμενη αναβάθμιση της staging

**Comment by sadamaki** [comment]
[5.2] Ελάχιστος αριθμός εγγραφών: 1
